//File: TestO.c 
//Generated by TMC Converter(C)2009-2013
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--4:
//function [r,y]=TestO(p) 

//% calculate roots of a polynom

//

//r = roots(p);

void tmcTestO(int nargout, int nargin,tmsMatrix *r,tmsMatrix *y
,tmsMatrix *p) {
tmsMatrix **reg=tmcCreateRegFrame(8);

TRY
TMC_DBG_PUSH_STACK_VAR("TestO",3,
p,"p",
r,"r",
y,"y");


//CALL function
tmcReallocRegister(reg[2]);
tmcroots(1,1, reg[2], p);

tmcAssign(r,reg[2]);
//statement here,line 4

// % Lines 5--5:
//y = polyval(p,r);



//CALL function
tmcReallocRegister(reg[6]);
tmcpolyval(1,2, reg[6], p, r);

tmcAssign(y,reg[6]);
//statement here,line 5

// % Lines 6--8:
//

//

label_1: ; //end Function
FINALLY
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(3);

ENDFINALLY
}

//FUNCTION DEFINITION BEGIN
//statement here,line 8

// % Lines 9--9:
