//File: TestO.c 
//Generated by TMC Converter(C)2009-2013
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--6:
//function [F,Mag,Ph]=TestO(f1,d1,f2,d2, NumFreqs)

//% [F,Mag,Ph]=TestO(1000,0.07,1500,0.7, 100)

//% Calculate 2nd-order filter frequency responce 

//

//if NumFreqs <2 || f1<= 0 || f2 <=0 

//    F=0; Mag=0; Ph=0;

void tmcTestO(int nargout, int nargin,tmsMatrix *F,tmsMatrix *Mag,tmsMatrix *Ph
,tmsMatrix *f1,tmsMatrix *d1,tmsMatrix *f2,tmsMatrix *d2,tmsMatrix *NumFreqs) {
tmsMatrix **reg=tmcCreateRegFrame(70);
tmsMatrix *Fmin=tmcNewMatrix();
tmsMatrix *Fmax=tmcNewMatrix();
tmsMatrix *w1=tmcNewMatrix();
tmsMatrix *w2=tmcNewMatrix();
tmsMatrix *w=tmcNewMatrix();
tmsMatrix *num=tmcNewMatrix();
tmsMatrix *den=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("TestO",15,
f1,"f1",
d1,"d1",
f2,"f2",
d2,"d2",
NumFreqs,"NumFreqs",
F,"F",
Mag,"Mag",
Ph,"Ph",
Fmin,"Fmin",
Fmax,"Fmax",
w1,"w1",
w2,"w2",
w,"w",
num,"num",
den,"den");


tmcScalar(reg[4],2.000000000000000e+000);
tmcLt(reg[5],NumFreqs,reg[4]);
if(tmcIsTrue(reg[5])) {
	tmcAssignTrue(reg[2]); goto label_5;} // return(true) boolean_or expr

tmcScalar(reg[7],0.000000000000000e+000);
tmcLe(reg[8],f1,reg[7]);
tmcAssignBool(reg[2],reg[8]);
label_5: ; //end boolean expr
if(tmcIsTrue(reg[2])) {
	tmcAssignTrue(reg[1]); goto label_4;} // return(true) boolean_or expr

tmcScalar(reg[10],0.000000000000000e+000);
tmcLe(reg[11],f2,reg[10]);
tmcAssignBool(reg[1],reg[11]);
label_4: ; //end boolean expr
if(tmcIsFalse(reg[1])) goto label_3; // goto to the end of the clause if the expression is false
tmcScalar(reg[12],0.000000000000000e+000);

tmcAssign(F,reg[12]);
//statement here,line 6

tmcScalar(reg[14],0.000000000000000e+000);

tmcAssign(Mag,reg[14]);
//statement here,line 6

tmcScalar(reg[16],0.000000000000000e+000);

tmcAssign(Ph,reg[16]);
//statement here,line 6

// % Lines 7--7:
//    return;

goto label_1; //branch to FUNCTION exit
//statement here,line 7

// % Lines 8--8:
//end

goto label_2; //branch to end IF
label_3: ; //end IF clause
label_2: ; //end IF
//statement here,line 8

// % Lines 9--10:
//

//Fmin = min(f1,f2)*0.2;



//CALL function
tmcReallocRegister(reg[20]);
tmcReallocRegister(reg[21]);
tmcmin(1,2, reg[20], reg[21], f1, f2,NULL);
tmcScalar(reg[22],2.000000000000000e-001);
tmcMul(reg[23],reg[20],reg[22]);

tmcAssign(Fmin,reg[23]);
//statement here,line 10

// % Lines 11--11:
//Fmax = max(f1,f2)/0.2;



//CALL function
tmcReallocRegister(reg[27]);
tmcReallocRegister(reg[28]);
tmcmax(1,2, reg[27], reg[28], f1, f2,NULL);
tmcScalar(reg[29],2.000000000000000e-001);
tmcDiv(reg[30],reg[27],reg[29]);

tmcAssign(Fmax,reg[30]);
//statement here,line 11

// % Lines 12--12:
//F = logspace( log10(Fmin),log10(Fmax), NumFreqs ); 


//CALL function
tmcReallocRegister(reg[33]);
tmclog10(1,1, reg[33], Fmin);

//CALL function
tmcReallocRegister(reg[35]);
tmclog10(1,1, reg[35], Fmax);

//CALL function
tmcReallocRegister(reg[37]);
tmclogspace(1,3, reg[37], reg[33], reg[35], NumFreqs);

tmcAssign(F,reg[37]);
//statement here,line 12

// % Lines 13--13:
//w1 = f1*2*pi; w2 = f2*2*pi;


tmcScalar(reg[40],2.000000000000000e+000);
tmcMul(reg[41],f1,reg[40]);
//CALL function
tmcReallocRegister(reg[42]);
tmcpi(1,0, reg[42]);
tmcMul(reg[43],reg[41],reg[42]);

tmcAssign(w1,reg[43]);
//statement here,line 13


tmcScalar(reg[46],2.000000000000000e+000);
tmcMul(reg[47],f2,reg[46]);
//CALL function
tmcReallocRegister(reg[48]);
tmcpi(1,0, reg[48]);
tmcMul(reg[49],reg[47],reg[48]);

tmcAssign(w2,reg[49]);
//statement here,line 13

// % Lines 14--14:
//w = F * 2*pi;


tmcScalar(reg[52],2.000000000000000e+000);
tmcMul(reg[53],F,reg[52]);
//CALL function
tmcReallocRegister(reg[54]);
tmcpi(1,0, reg[54]);
tmcMul(reg[55],reg[53],reg[54]);

tmcAssign(w,reg[55]);
//statement here,line 14

// % Lines 15--15:
//[Mag,Ph,num,den]=resp2nd(w1,d1,w2,d2,w);






//CALL function
tmcReallocRegister(reg[62]);
tmcReallocRegister(reg[63]);
tmcReallocRegister(reg[64]);
tmcReallocRegister(reg[65]);
tmcresp2nd(4,5, reg[62], reg[63], reg[64], reg[65], w1, d1, w2, d2, w);

tmcAssign(Mag,reg[62]);

tmcAssign(Ph,reg[63]);

tmcAssign(num,reg[64]);

tmcAssign(den,reg[65]);
//statement here,line 15

// % Lines 16--26:
//% figure(10);

//% subplot(2,1,1);

//% plot(F, Mag,'b');

//% subplot(2,1,2);

//% plot(F, Ph,'b');

//

//

//

//

//

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(den);
tmcFreeLocalVar(num);
tmcFreeLocalVar(w);
tmcFreeLocalVar(w2);
tmcFreeLocalVar(w1);
tmcFreeLocalVar(Fmax);
tmcFreeLocalVar(Fmin);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(15);

ENDFINALLY
}

//FUNCTION DEFINITION BEGIN
//statement here,line 26

// % Lines 27--27:
