//File: btlCalcCommut.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--3:
//function [tht,AbsOffsetCorr,AdvUsecCorr] =btlCalcCommut

//

//JV_tests   = [750000,1000000,1500000,2000000,3000000];

void tmcbtlCalcCommut(int nargout, int nargin,tmsMatrix *tht,tmsMatrix *AbsOffsetCorr,tmsMatrix *AdvUsecCorr
) {
tmsMatrix **reg=tmcCreateRegFrame(335);
tmsMatrix *JV_tests=tmcNewMatrix();
tmsMatrix *FileNames=tmcNewMatrix();
tmsMatrix *Thetas_min_a=tmcNewMatrix();
tmsMatrix *cnt=tmcNewMatrix();
tmsMatrix *www=tmcNewMatrix();
tmsMatrix *Iq_ave=tmcNewMatrix();
tmsMatrix *Thetas=tmcNewMatrix();
tmsMatrix *Y1=tmcNewMatrix();
tmsMatrix *Y2=tmcNewMatrix();
tmsMatrix *I2=tmcNewMatrix();
tmsMatrix *lena=tmcNewMatrix();
tmsMatrix *Ha=tmcNewMatrix();
tmsMatrix *thta=tmcNewMatrix();
tmsMatrix *Thetas_simul=tmcNewMatrix();
tmsMatrix *Ha_simul=tmcNewMatrix();
tmsMatrix *Iq_simul=tmcNewMatrix();
tmsMatrix *Y=tmcNewMatrix();
tmsMatrix *I=tmcNewMatrix();
tmsMatrix *NumPoles=tmcNewMatrix();
tmsMatrix *BitsPerRev=tmcNewMatrix();
tmsMatrix *EangleCorrRes=tmcNewMatrix();
tmsMatrix *Thetas_min=tmcNewMatrix();
tmsMatrix *len=tmcNewMatrix();
tmsMatrix *ElecVel=tmcNewMatrix();
tmsMatrix *AngleElecCorr=tmcNewMatrix();
tmsMatrix *H=tmcNewMatrix();
tmsMatrix *w=tmcNewMatrix();
tmsMatrix *s=tmcNewMatrix();
tmsMatrix *w0=tmcNewMatrix();
tmsMatrix *w1=tmcNewMatrix();
tmsMatrix *d0=tmcNewMatrix();
tmsMatrix *d1=tmcNewMatrix();
tmsMatrix *P=tmcNewMatrix();
tmsMatrix *ph=tmcNewMatrix();
tmsMatrix *Mag=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("btlCalcCommut",38,
tht,"tht",
AbsOffsetCorr,"AbsOffsetCorr",
AdvUsecCorr,"AdvUsecCorr",
JV_tests,"JV_tests",
FileNames,"FileNames",
Thetas_min_a,"Thetas_min_a",
cnt,"cnt",
www,"www",
Iq_ave,"Iq_ave",
Thetas,"Thetas",
Y1,"Y1",
Y2,"Y2",
I2,"I2",
lena,"lena",
Ha,"Ha",
thta,"thta",
Thetas_simul,"Thetas_simul",
Ha_simul,"Ha_simul",
Iq_simul,"Iq_simul",
Y,"Y",
I,"I",
NumPoles,"NumPoles",
BitsPerRev,"BitsPerRev",
EangleCorrRes,"EangleCorrRes",
Thetas_min,"Thetas_min",
len,"len",
ElecVel,"ElecVel",
AngleElecCorr,"AngleElecCorr",
H,"H",
w,"w",
s,"s",
w0,"w0",
w1,"w1",
d0,"d0",
d1,"d1",
P,"P",
ph,"ph",
Mag,"Mag");

tmcScalar(reg[1],7.500000000000000e+005);
tmcScalar(reg[2],1.000000000000000e+006);
tmcScalar(reg[3],1.500000000000000e+006);
tmcScalar(reg[4],2.000000000000000e+006);
tmcScalar(reg[5],3.000000000000000e+006);
tmcCollectColumns(reg[6],5,reg[1],reg[2],reg[3],reg[4],reg[5]);
tmcCollectRows(reg[7],1,reg[6]);

tmcAssign(JV_tests,reg[7]);
//statement here,line 3

// % Lines 4--10:
//

//FileNames={'BtlMotor1_comm_jv750000_13p6V.mat', ...

//'BtlMotor1_comm_jv1000000_13p6V.mat',  ...                        

//'BtlMotor1_comm_jv1500000_13p6V.mat' ,  ...                                          

//'BtlMotor1_comm_jv2000000_13p6V.mat' ,  ...                 

//'BtlMotor1_comm_jv3000000_6p9V.mat'  ,  ...                   

//};

tmcCreateString(reg[9],"BtlMotor1_comm_jv750000_13p6V.mat");
tmcCreateString(reg[10],"BtlMotor1_comm_jv1000000_13p6V.mat");
tmcCreateString(reg[11],"BtlMotor1_comm_jv1500000_13p6V.mat");
tmcCreateString(reg[12],"BtlMotor1_comm_jv2000000_13p6V.mat");
tmcCreateString(reg[13],"BtlMotor1_comm_jv3000000_6p9V.mat");
tmcCollectCellColumns(reg[14],5,reg[9],reg[10],reg[11],reg[12],reg[13]);
tmcCollectCellRows(reg[15],1,reg[14]);

tmcAssign(FileNames,reg[15]);
//statement here,line 10

// % Lines 11--11:
//Thetas_min_a=[];

tmcCreateMatrixEmpty(reg[17]);

tmcAssign(Thetas_min_a,reg[17]);
//statement here,line 11

// % Lines 12--13:
//for cnt=1:length(JV_tests)

//        www= load(FileNames{cnt});

tmcScalar(reg[19],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[21]);
tmclength(1,1, reg[21], JV_tests);
tmcCreateColonBaseLimit(reg[22],reg[19],reg[21]);
tmcForIterInit(reg[23],reg[22],cnt);
label_4: ; //FOR begin
if(tmcForIterNext(reg[23],reg[22])) goto label_3; // exit for


tmcGetByIndexCell(reg[26],FileNames,1,cnt);
//CALL function
tmcReallocRegister(reg[27]);
tmcload(1,1, reg[27], reg[26]);

tmcAssign(www,reg[27]);
//statement here,line 13

// % Lines 14--14:
//        Iq_ave =   www.Iq_ave;


tmcGetByFieldHcode(reg[31],www,0xcf590000);/* Iq_ave */

tmcAssign(Iq_ave,reg[31]);
//statement here,line 14

// % Lines 15--15:
//        Thetas = www.Thetas;


tmcGetByFieldHcode(reg[35],www,0x49b50000);/* Thetas */

tmcAssign(Thetas,reg[35]);
//statement here,line 15

// % Lines 16--17:
//        

//        Y1=min(Iq_ave);


//CALL function
tmcReallocRegister(reg[38]);
tmcReallocRegister(reg[39]);
tmcmin(1,1, reg[38], reg[39], Iq_ave,NULL,NULL);

tmcAssign(Y1,reg[38]);
//statement here,line 17

// % Lines 18--18:
//        Y2=max(Iq_ave);


//CALL function
tmcReallocRegister(reg[42]);
tmcReallocRegister(reg[43]);
tmcmax(1,1, reg[42], reg[43], Iq_ave,NULL,NULL);

tmcAssign(Y2,reg[42]);
//statement here,line 18

// % Lines 19--19:
//        [I2] =find( Iq_ave < (Y1 + 0.5*( Y2-Y1  )   )  );



tmcScalar(reg[47],5.000000000000000e-001);


tmcSub(reg[50],Y2,Y1);
tmcMul(reg[51],reg[47],reg[50]);
tmcAdd(reg[52],Y1,reg[51]);
tmcLt(reg[53],Iq_ave,reg[52]);
//CALL function
tmcReallocRegister(reg[54]);
tmcReallocRegister(reg[55]);
tmcReallocRegister(reg[56]);
tmcfind(1,1, reg[54], reg[55], reg[56], reg[53],NULL,NULL);

tmcAssign(I2,reg[54]);
//statement here,line 19

// % Lines 20--20:
//        Iq_ave=Iq_ave(I2);



tmcGetByIndex(reg[60],Iq_ave,1,I2);

tmcAssign(Iq_ave,reg[60]);
//statement here,line 20

// % Lines 21--21:
//        Thetas=Thetas(I2);



tmcGetByIndex(reg[64],Thetas,1,I2);

tmcAssign(Thetas,reg[64]);
//statement here,line 21

// % Lines 22--24:
//

//        

//        lena = length(Iq_ave);


//CALL function
tmcReallocRegister(reg[67]);
tmclength(1,1, reg[67], Iq_ave);

tmcAssign(lena,reg[67]);
//statement here,line 24

// % Lines 25--26:
//        

//        Ha = [Thetas(:).^2, Thetas(:), ones(lena,1)];


tmcCreateMagicColon(reg[70]);
tmcGetByIndex(reg[71],Thetas,1,reg[70]);
tmcScalar(reg[72],2.000000000000000e+000);
tmcPowerScalar(reg[73],reg[71],reg[72]);

tmcCreateMagicColon(reg[75]);
tmcGetByIndex(reg[76],Thetas,1,reg[75]);

tmcScalar(reg[78],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[79]);
tmcones(1,2, reg[79], lena, reg[78]);
tmcCollectColumns(reg[80],3,reg[73],reg[76],reg[79]);
tmcCollectRows(reg[81],1,reg[80]);

tmcAssign(Ha,reg[81]);
//statement here,line 26

// % Lines 27--27:
//        thta = (Ha'*Ha)\(Ha'*Iq_ave(:)); % Iq_ave = Thetas^2*thta(1) + Thetas*thta(2)+thta(3)


tmcTranspose(reg[84],Ha);

tmcMul(reg[86],reg[84],Ha);

tmcTranspose(reg[88],Ha);

tmcCreateMagicColon(reg[90]);
tmcGetByIndex(reg[91],Iq_ave,1,reg[90]);
tmcMul(reg[92],reg[88],reg[91]);
tmcLeftDiv(reg[93],reg[86],reg[92]);

tmcAssign(thta,reg[93]);
//statement here,line 27

// % Lines 28--29:
//    

//    Thetas_simul = [Thetas(1):1:Thetas(end)];  


tmcScalar(reg[96],1.000000000000000e+000);
tmcGetByIndex(reg[97],Thetas,1,reg[96]);

tmcGetEnd(reg[99],Thetas,1,1);
tmcGetByIndex(reg[100],Thetas,1,reg[99]);
tmcScalar(reg[101],1.000000000000000e+000);
tmcCreateColonBaseIncLimit(reg[102],reg[97],reg[101],reg[100]);
tmcCollectColumns(reg[103],1,reg[102]);
tmcCollectRows(reg[104],1,reg[103]);

tmcAssign(Thetas_simul,reg[104]);
//statement here,line 29

// % Lines 30--30:
//    Ha_simul = [Thetas_simul(:).^2, Thetas_simul(:), ones(length(Thetas_simul),1)];


tmcCreateMagicColon(reg[107]);
tmcGetByIndex(reg[108],Thetas_simul,1,reg[107]);
tmcScalar(reg[109],2.000000000000000e+000);
tmcPowerScalar(reg[110],reg[108],reg[109]);

tmcCreateMagicColon(reg[112]);
tmcGetByIndex(reg[113],Thetas_simul,1,reg[112]);

//CALL function
tmcReallocRegister(reg[115]);
tmclength(1,1, reg[115], Thetas_simul);
tmcScalar(reg[116],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[117]);
tmcones(1,2, reg[117], reg[115], reg[116]);
tmcCollectColumns(reg[118],3,reg[110],reg[113],reg[117]);
tmcCollectRows(reg[119],1,reg[118]);

tmcAssign(Ha_simul,reg[119]);
//statement here,line 30

// % Lines 31--32:
//

//    Iq_simul=Ha_simul*thta;



tmcMul(reg[123],Ha_simul,thta);

tmcAssign(Iq_simul,reg[123]);
//statement here,line 32

// % Lines 33--35:
//%     figure(1000);

//%      plot(Thetas,Iq_ave,'r.-',Thetas_simul,Iq_simul,'b');grid on;

//     [Y,I]=min(Iq_simul);


//CALL function
tmcReallocRegister(reg[126]);
tmcReallocRegister(reg[127]);
tmcmin(2,1, reg[126], reg[127], Iq_simul,NULL,NULL);

tmcAssign(Y,reg[126]);

tmcAssign(I,reg[127]);
//statement here,line 35

// % Lines 36--36:
//     Thetas_min_a(cnt)=Thetas_simul(I);



tmcGetByIndex(reg[132],Thetas_simul,1,I);


tmcGetRefByIndex(pRefHelper,Thetas_min_a,1,cnt);
tmcAssign(pRefHelper,reg[132]);
//statement here,line 36

// % Lines 37--37:
//end

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 37

// % Lines 38--40:
//

//

//NumPoles=3;

tmcScalar(reg[135],3.000000000000000e+000);

tmcAssign(NumPoles,reg[135]);
//statement here,line 40

// % Lines 41--41:
//BitsPerRev = 2^16;

tmcScalar(reg[137],2.000000000000000e+000);
tmcScalar(reg[138],1.600000000000000e+001);
tmcPower(reg[139],reg[137],reg[138]);

tmcAssign(BitsPerRev,reg[139]);
//statement here,line 41

// % Lines 42--43:
//

//EangleCorrRes = 2^16;

tmcScalar(reg[141],2.000000000000000e+000);
tmcScalar(reg[142],1.600000000000000e+001);
tmcPower(reg[143],reg[141],reg[142]);

tmcAssign(EangleCorrRes,reg[143]);
//statement here,line 43

// % Lines 44--45:
//

// Thetas_min = [3200,3600,4800,5400,6700];

tmcScalar(reg[145],3.200000000000000e+003);
tmcScalar(reg[146],3.600000000000000e+003);
tmcScalar(reg[147],4.800000000000000e+003);
tmcScalar(reg[148],5.400000000000000e+003);
tmcScalar(reg[149],6.700000000000000e+003);
tmcCollectColumns(reg[150],5,reg[145],reg[146],reg[147],reg[148],reg[149]);
tmcCollectRows(reg[151],1,reg[150]);

tmcAssign(Thetas_min,reg[151]);
//statement here,line 45

// % Lines 46--46:
// Thetas_min = Thetas_min_a;%[3200,3600,4800,5400,6700];



tmcAssign(Thetas_min,Thetas_min_a);
//statement here,line 46

// % Lines 47--48:
//

//len = length(JV_tests);


//CALL function
tmcReallocRegister(reg[156]);
tmclength(1,1, reg[156], JV_tests);

tmcAssign(len,reg[156]);
//statement here,line 48

// % Lines 49--50:
//

//ElecVel       =  JV_tests / BitsPerRev * NumPoles * 360;



tmcDiv(reg[160],JV_tests,BitsPerRev);

tmcMul(reg[162],reg[160],NumPoles);
tmcScalar(reg[163],3.600000000000000e+002);
tmcMul(reg[164],reg[162],reg[163]);

tmcAssign(ElecVel,reg[164]);
//statement here,line 50

// % Lines 51--51:
//AngleElecCorr =  Thetas_min / EangleCorrRes * 360;



tmcDiv(reg[168],Thetas_min,EangleCorrRes);
tmcScalar(reg[169],3.600000000000000e+002);
tmcMul(reg[170],reg[168],reg[169]);

tmcAssign(AngleElecCorr,reg[170]);
//statement here,line 51

// % Lines 52--53:
//

//H = [ElecVel(:),ones(len,1)];


tmcCreateMagicColon(reg[173]);
tmcGetByIndex(reg[174],ElecVel,1,reg[173]);

tmcScalar(reg[176],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[177]);
tmcones(1,2, reg[177], len, reg[176]);
tmcCollectColumns(reg[178],2,reg[174],reg[177]);
tmcCollectRows(reg[179],1,reg[178]);

tmcAssign(H,reg[179]);
//statement here,line 53

// % Lines 54--54:
//tht = inv(H'*H)*(H'*AngleElecCorr(:)); % AngleElecCorr = ElecVel*tht(1) + tht(2)


tmcTranspose(reg[182],H);

tmcMul(reg[184],reg[182],H);
//CALL function
tmcReallocRegister(reg[185]);
tmcinv(1,1, reg[185], reg[184]);

tmcTranspose(reg[187],H);

tmcCreateMagicColon(reg[189]);
tmcGetByIndex(reg[190],AngleElecCorr,1,reg[189]);
tmcMul(reg[191],reg[187],reg[190]);
tmcMul(reg[192],reg[185],reg[191]);

tmcAssign(tht,reg[192]);
//statement here,line 54

// % Lines 55--56:
//

//figure(50);

tmcScalar(reg[194],5.000000000000000e+001);
//CALL function
tmcReallocRegister(reg[195]);
tmcfigure(0,1, reg[195], reg[194]);
//statement here,line 56

// % Lines 57--57:
//plot(ElecVel,AngleElecCorr,'r.-',[0,ElecVel],[0,ElecVel]*tht(1)+tht(2),'b');grid on;



tmcCreateString(reg[198],"r.-");
tmcScalar(reg[199],0.000000000000000e+000);

tmcCollectColumns(reg[201],2,reg[199],ElecVel);
tmcCollectRows(reg[202],1,reg[201]);
tmcScalar(reg[203],0.000000000000000e+000);

tmcCollectColumns(reg[205],2,reg[203],ElecVel);
tmcCollectRows(reg[206],1,reg[205]);

tmcScalar(reg[208],1.000000000000000e+000);
tmcGetByIndex(reg[209],tht,1,reg[208]);
tmcMul(reg[210],reg[206],reg[209]);

tmcScalar(reg[212],2.000000000000000e+000);
tmcGetByIndex(reg[213],tht,1,reg[212]);
tmcAdd(reg[214],reg[210],reg[213]);
tmcCreateString(reg[215],"b");
//CALL function
tmcReallocRegister(reg[216]);
tmcplot(0,6, reg[216], ElecVel, AngleElecCorr, reg[198], reg[202], reg[214], reg[215]);
//statement here,line 57

tmcCreateString(reg[217],"on");
//CALL function
tmcReallocRegister(reg[218]);
tmcgrid(0,1, reg[218], reg[217]);
//statement here,line 57

// % Lines 58--59:
//

//AbsOffsetCorr = tht(2)/360 / NumPoles * BitsPerRev;


tmcScalar(reg[220],2.000000000000000e+000);
tmcGetByIndex(reg[221],tht,1,reg[220]);
tmcScalar(reg[222],3.600000000000000e+002);
tmcDiv(reg[223],reg[221],reg[222]);

tmcDiv(reg[225],reg[223],NumPoles);

tmcMul(reg[227],reg[225],BitsPerRev);

tmcAssign(AbsOffsetCorr,reg[227]);
//statement here,line 59

// % Lines 60--60:
//AdvUsecCorr   = tht(1)*1e6;


tmcScalar(reg[230],1.000000000000000e+000);
tmcGetByIndex(reg[231],tht,1,reg[230]);
tmcScalar(reg[232],1.000000000000000e+006);
tmcMul(reg[233],reg[231],reg[232]);

tmcAssign(AdvUsecCorr,reg[233]);
//statement here,line 60

// % Lines 61--64:
//

//% tht = FitLine(JV_tests,Thetas_min,1);

//

//w = logspace(-1,3,1000);

tmcScalar(reg[235],1.000000000000000e+000);
tmcNeg(reg[236],reg[235]);
tmcScalar(reg[237],3.000000000000000e+000);
tmcScalar(reg[238],1.000000000000000e+003);
//CALL function
tmcReallocRegister(reg[239]);
tmclogspace(1,3, reg[239], reg[236], reg[237], reg[238]);

tmcAssign(w,reg[239]);
//statement here,line 64

// % Lines 65--65:
//s = j*w;

//CALL function
tmcReallocRegister(reg[241]);
tmcj(1,0, reg[241]);

tmcMul(reg[243],reg[241],w);

tmcAssign(s,reg[243]);
//statement here,line 65

// % Lines 66--66:
//w0=120;w1=250;d0=0.07;d1=0.55;

tmcScalar(reg[245],1.200000000000000e+002);

tmcAssign(w0,reg[245]);
//statement here,line 66

tmcScalar(reg[247],2.500000000000000e+002);

tmcAssign(w1,reg[247]);
//statement here,line 66

tmcScalar(reg[249],7.000000000000001e-002);

tmcAssign(d0,reg[249]);
//statement here,line 66

tmcScalar(reg[251],5.500000000000000e-001);

tmcAssign(d1,reg[251]);
//statement here,line 66

// % Lines 67--67:
//P = (s.^2 + 2*d0*w0*s+w0^2)./(s.^2 + 2*d1*w1*s+w1^2)*(w1/w0)^2 ./ (s.^2) ./(s+10000)*10000;


tmcScalar(reg[254],2.000000000000000e+000);
tmcPowerScalar(reg[255],s,reg[254]);
tmcScalar(reg[256],2.000000000000000e+000);

tmcMul(reg[258],reg[256],d0);

tmcMul(reg[260],reg[258],w0);

tmcMul(reg[262],reg[260],s);
tmcAdd(reg[263],reg[255],reg[262]);

tmcScalar(reg[265],2.000000000000000e+000);
tmcPower(reg[266],w0,reg[265]);
tmcAdd(reg[267],reg[263],reg[266]);

tmcScalar(reg[269],2.000000000000000e+000);
tmcPowerScalar(reg[270],s,reg[269]);
tmcScalar(reg[271],2.000000000000000e+000);

tmcMul(reg[273],reg[271],d1);

tmcMul(reg[275],reg[273],w1);

tmcMul(reg[277],reg[275],s);
tmcAdd(reg[278],reg[270],reg[277]);

tmcScalar(reg[280],2.000000000000000e+000);
tmcPower(reg[281],w1,reg[280]);
tmcAdd(reg[282],reg[278],reg[281]);
tmcDivScalar(reg[283],reg[267],reg[282]);


tmcDiv(reg[286],w1,w0);
tmcScalar(reg[287],2.000000000000000e+000);
tmcPower(reg[288],reg[286],reg[287]);
tmcMul(reg[289],reg[283],reg[288]);

tmcScalar(reg[291],2.000000000000000e+000);
tmcPowerScalar(reg[292],s,reg[291]);
tmcDivScalar(reg[293],reg[289],reg[292]);

tmcScalar(reg[295],1.000000000000000e+004);
tmcAdd(reg[296],s,reg[295]);
tmcDivScalar(reg[297],reg[293],reg[296]);
tmcScalar(reg[298],1.000000000000000e+004);
tmcMul(reg[299],reg[297],reg[298]);

tmcAssign(P,reg[299]);
//statement here,line 67

// % Lines 68--68:
//ph=unwrap(angle(P))/pi*180 -360;


//CALL function
tmcReallocRegister(reg[302]);
tmcangle(1,1, reg[302], P);
//CALL function
tmcReallocRegister(reg[303]);
tmcunwrap(1,1, reg[303], reg[302],NULL);
//CALL function
tmcReallocRegister(reg[304]);
tmcpi(1,0, reg[304]);
tmcDiv(reg[305],reg[303],reg[304]);
tmcScalar(reg[306],1.800000000000000e+002);
tmcMul(reg[307],reg[305],reg[306]);
tmcScalar(reg[308],3.600000000000000e+002);
tmcSub(reg[309],reg[307],reg[308]);

tmcAssign(ph,reg[309]);
//statement here,line 68

// % Lines 69--69:
//Mag=20*log10(abs(P));

tmcScalar(reg[311],2.000000000000000e+001);

//CALL function
tmcReallocRegister(reg[313]);
tmcabs(1,1, reg[313], P);
//CALL function
tmcReallocRegister(reg[314]);
tmclog10(1,1, reg[314], reg[313]);
tmcMul(reg[315],reg[311],reg[314]);

tmcAssign(Mag,reg[315]);
//statement here,line 69

// % Lines 70--70:
//figure(123);

tmcScalar(reg[317],1.230000000000000e+002);
//CALL function
tmcReallocRegister(reg[318]);
tmcfigure(0,1, reg[318], reg[317]);
//statement here,line 70

// % Lines 71--71:
//subplot(2,1,1);

tmcScalar(reg[319],2.000000000000000e+000);
tmcScalar(reg[320],1.000000000000000e+000);
tmcScalar(reg[321],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[322]);
tmcsubplot(0,3, reg[322], reg[319], reg[320], reg[321]);
//statement here,line 71

// % Lines 72--72:
//plot(w,Mag,'b');



tmcCreateString(reg[325],"b");
//CALL function
tmcReallocRegister(reg[326]);
tmcplot(0,3, reg[326], w, Mag, reg[325]);
//statement here,line 72

// % Lines 73--73:
//subplot(2,1,2);

tmcScalar(reg[327],2.000000000000000e+000);
tmcScalar(reg[328],1.000000000000000e+000);
tmcScalar(reg[329],2.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[330]);
tmcsubplot(0,3, reg[330], reg[327], reg[328], reg[329]);
//statement here,line 73

// % Lines 74--74:
//plot(w,ph,'b');



tmcCreateString(reg[333],"b");
//CALL function
tmcReallocRegister(reg[334]);
tmcplot(0,3, reg[334], w, ph, reg[333]);
//statement here,line 74

// % Lines 75--83:
//% 

//% figure(124);

//% subplot(2,1,1);

//% plot(log10(w),Mag,'b');

//% subplot(2,1,2);

//% plot(log10(w),ph,'b');

//

//

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(Mag);
tmcFreeLocalVar(ph);
tmcFreeLocalVar(P);
tmcFreeLocalVar(d1);
tmcFreeLocalVar(d0);
tmcFreeLocalVar(w1);
tmcFreeLocalVar(w0);
tmcFreeLocalVar(s);
tmcFreeLocalVar(w);
tmcFreeLocalVar(H);
tmcFreeLocalVar(AngleElecCorr);
tmcFreeLocalVar(ElecVel);
tmcFreeLocalVar(len);
tmcFreeLocalVar(Thetas_min);
tmcFreeLocalVar(EangleCorrRes);
tmcFreeLocalVar(BitsPerRev);
tmcFreeLocalVar(NumPoles);
tmcFreeLocalVar(I);
tmcFreeLocalVar(Y);
tmcFreeLocalVar(Iq_simul);
tmcFreeLocalVar(Ha_simul);
tmcFreeLocalVar(Thetas_simul);
tmcFreeLocalVar(thta);
tmcFreeLocalVar(Ha);
tmcFreeLocalVar(lena);
tmcFreeLocalVar(I2);
tmcFreeLocalVar(Y2);
tmcFreeLocalVar(Y1);
tmcFreeLocalVar(Thetas);
tmcFreeLocalVar(Iq_ave);
tmcFreeLocalVar(www);
tmcFreeLocalVar(cnt);
tmcFreeLocalVar(Thetas_min_a);
tmcFreeLocalVar(FileNames);
tmcFreeLocalVar(JV_tests);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(38);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 83

// % Lines 84--84:
