//File: CheckVar1.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--3:
//function d=CheckVar1(p,r)

//

//d = polyval(p,r);

void tmcCheckVar1(int nargout, int nargin,tmsMatrix *d
,tmsMatrix *p,tmsMatrix *r) {
tmsMatrix **reg=tmcCreateRegFrame(5);

TRY
TMC_DBG_PUSH_STACK_VAR("CheckVar1",3,
p,"p",
r,"r",
d,"d");



//CALL function
tmcReallocRegister(reg[3]);
tmcpolyval(1,2, reg[3], p, r);

tmcAssign(d,reg[3]);
//statement here,line 3

// % Lines 4--5:
//

label_1: ; //end Function
FINALLY
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(3);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 5

// % Lines 6--6:
