//File: getcurloop.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--16:
//function [PropGain,IntGain,FreqLen,FreqHz,OL_Mag,OL_Ph,CL_Mag,CL_Ph,RespLen,RespTime,Resp]=getcurloop(R,L,Ts,Ovs)

//% Example: calculate open and closed loop for RL curcuit current control

//% Input: R [Ohm], L [Hn] - resistance and inductance

//%        Ts [sec] - sampling time of controller

//%        Ovs [1..1.5] - desired maximal overshoot

//% Output: 

//% PropGain,IntGain : gains of PI controller

//% FreqLen: number of frequencies in result

//% FreqHz,OL_Mag,OL_Ph,CL_Mag,CL_Ph: vectors of

//% frequencies[Hz],Magnitude[dB],Phase[deg] of open-loop and closed-loop

//% RespLen: number of points of responce

//% RespTime [sec],Resp - vectors of time and value of the close-loop step

//% response

//% Author: shmuel safonov , (C) 2017

//% The code is a part of TMC Compiler examples

//PropGain=[];IntGain=[];

void tmcgetcurloop(int nargout, int nargin,tmsMatrix *PropGain,tmsMatrix *IntGain,tmsMatrix *FreqLen,tmsMatrix *FreqHz,tmsMatrix *OL_Mag,tmsMatrix *OL_Ph,tmsMatrix *CL_Mag,tmsMatrix *CL_Ph,tmsMatrix *RespLen,tmsMatrix *RespTime,tmsMatrix *Resp
,tmsMatrix *R__input__tmc,tmsMatrix *L__input__tmc,tmsMatrix *Ts__input__tmc,tmsMatrix *Ovs__input__tmc) {
tmsMatrix **reg=tmcCreateRegFrame(618);
tmsMatrix *R=tmcNewMatrix();
tmsMatrix *L=tmcNewMatrix();
tmsMatrix *Ts=tmcNewMatrix();
tmsMatrix *Ovs=tmcNewMatrix();
tmsMatrix *D=tmcNewMatrix();
tmsMatrix *PhaseM=tmcNewMatrix();
tmsMatrix *GainM=tmcNewMatrix();
tmsMatrix *MaxW=tmcNewMatrix();
tmsMatrix *L1=tmcNewMatrix();
tmsMatrix *L2=tmcNewMatrix();
tmsMatrix *w1=tmcNewMatrix();
tmsMatrix *s1=tmcNewMatrix();
tmsMatrix *B1=tmcNewMatrix();
tmsMatrix *LL1=tmcNewMatrix();
tmsMatrix *Ki=tmcNewMatrix();
tmsMatrix *Kp=tmcNewMatrix();
tmsMatrix *II=tmcNewMatrix();
tmsMatrix *w=tmcNewMatrix();
tmsMatrix *s=tmcNewMatrix();
tmsMatrix *z=tmcNewMatrix();
tmsMatrix *Ph2=tmcNewMatrix();
tmsMatrix *Sol_opt=tmcNewMatrix();
tmsMatrix *Ovs_Opt=tmcNewMatrix();
tmsMatrix *Lopen_opt=tmcNewMatrix();
tmsMatrix *NomC=tmcNewMatrix();
tmsMatrix *Sol=tmcNewMatrix();
tmsMatrix *kk=tmcNewMatrix();
tmsMatrix *Lopen=tmcNewMatrix();
tmsMatrix *II1=tmcNewMatrix();
tmsMatrix *Ph1=tmcNewMatrix();
tmsMatrix *CL=tmcNewMatrix();
tmsMatrix *YY=tmcNewMatrix();
tmsMatrix *n=tmcNewMatrix();
tmsMatrix *kp0=tmcNewMatrix();
tmsMatrix *ki0=tmcNewMatrix();
tmsMatrix *Lopen0=tmcNewMatrix();
tmsMatrix *rden=tmcNewMatrix();
tmsMatrix *rdend=tmcNewMatrix();
tmsMatrix *sysP1d=tmcNewMatrix();
tmsMatrix *sysP2d=tmcNewMatrix();
tmsMatrix *sysPd=tmcNewMatrix();
tmsMatrix *sysPCLd=tmcNewMatrix();
tmsMatrix *num=tmcNewMatrix();
tmsMatrix *den=tmcNewMatrix();
tmsMatrix *yy=tmcNewMatrix();
tmsMatrix *ActOvs=tmcNewMatrix();
tmsMatrix *CL_Opt=tmcNewMatrix();
tmsMatrix *yy_opt=tmcNewMatrix();

tmcCopyMat(R,R__input__tmc);
tmcCopyMat(L,L__input__tmc);
tmcCopyMat(Ts,Ts__input__tmc);
tmcCopyMat(Ovs,Ovs__input__tmc);
TRY
TMC_DBG_PUSH_STACK_VAR("getcurloop",63,
R__input__tmc,"R__input__tmc",
L__input__tmc,"L__input__tmc",
Ts__input__tmc,"Ts__input__tmc",
Ovs__input__tmc,"Ovs__input__tmc",
PropGain,"PropGain",
IntGain,"IntGain",
FreqLen,"FreqLen",
FreqHz,"FreqHz",
OL_Mag,"OL_Mag",
OL_Ph,"OL_Ph",
CL_Mag,"CL_Mag",
CL_Ph,"CL_Ph",
RespLen,"RespLen",
RespTime,"RespTime",
Resp,"Resp",
R,"R",
L,"L",
Ts,"Ts",
Ovs,"Ovs",
D,"D",
PhaseM,"PhaseM",
GainM,"GainM",
MaxW,"MaxW",
L1,"L1",
L2,"L2",
w1,"w1",
s1,"s1",
B1,"B1",
LL1,"LL1",
Ki,"Ki",
Kp,"Kp",
II,"II",
w,"w",
s,"s",
z,"z",
Ph2,"Ph2",
Sol_opt,"Sol_opt",
Ovs_Opt,"Ovs_Opt",
Lopen_opt,"Lopen_opt",
NomC,"NomC",
Sol,"Sol",
kk,"kk",
Lopen,"Lopen",
II1,"II1",
Ph1,"Ph1",
CL,"CL",
YY,"YY",
n,"n",
kp0,"kp0",
ki0,"ki0",
Lopen0,"Lopen0",
rden,"rden",
rdend,"rdend",
sysP1d,"sysP1d",
sysP2d,"sysP2d",
sysPd,"sysPd",
sysPCLd,"sysPCLd",
num,"num",
den,"den",
yy,"yy",
ActOvs,"ActOvs",
CL_Opt,"CL_Opt",
yy_opt,"yy_opt");

tmcCreateMatrixEmpty(reg[1]);

tmcAssign(PropGain,reg[1]);
//statement here,line 16

tmcCreateMatrixEmpty(reg[3]);

tmcAssign(IntGain,reg[3]);
//statement here,line 16

// % Lines 17--17:
//FreqLen=0;FreqHz=[];OL_Mag=[];OL_Ph=[];CL_Mag=[];CL_Ph=[];

tmcScalar(reg[5],0.000000000000000e+000);

tmcAssign(FreqLen,reg[5]);
//statement here,line 17

tmcCreateMatrixEmpty(reg[7]);

tmcAssign(FreqHz,reg[7]);
//statement here,line 17

tmcCreateMatrixEmpty(reg[9]);

tmcAssign(OL_Mag,reg[9]);
//statement here,line 17

tmcCreateMatrixEmpty(reg[11]);

tmcAssign(OL_Ph,reg[11]);
//statement here,line 17

tmcCreateMatrixEmpty(reg[13]);

tmcAssign(CL_Mag,reg[13]);
//statement here,line 17

tmcCreateMatrixEmpty(reg[15]);

tmcAssign(CL_Ph,reg[15]);
//statement here,line 17

// % Lines 18--18:
//RespLen=0;RespTime=[];Resp=[];

tmcScalar(reg[17],0.000000000000000e+000);

tmcAssign(RespLen,reg[17]);
//statement here,line 18

tmcCreateMatrixEmpty(reg[19]);

tmcAssign(RespTime,reg[19]);
//statement here,line 18

tmcCreateMatrixEmpty(reg[21]);

tmcAssign(Resp,reg[21]);
//statement here,line 18

// % Lines 19--20:
//if nargin==0

//    R = 0.2;

//CALL function
tmcReallocRegister(reg[23]);
tmcnargin(1,0, reg[23]);
tmcScalar(reg[24],0.000000000000000e+000);
tmcEq(reg[25],reg[23],reg[24]);
if(tmcIsFalse(reg[25])) goto label_3; // goto to the end of the clause if the expression is false
tmcScalar(reg[26],2.000000000000000e-001);

tmcAssign(R,reg[26]);
//statement here,line 20

// % Lines 21--21:
//    L = 0.002;

tmcScalar(reg[28],2.000000000000000e-003);

tmcAssign(L,reg[28]);
//statement here,line 21

// % Lines 22--22:
//    Ts = 50e-6;

tmcScalar(reg[30],5.000000000000000e-005);

tmcAssign(Ts,reg[30]);
//statement here,line 22

// % Lines 23--23:
//    Ovs = 1.15;

tmcScalar(reg[32],1.150000000000000e+000);

tmcAssign(Ovs,reg[32]);
//statement here,line 23

// % Lines 24--24:
//end

goto label_2; //branch to end IF
label_3: ; //end IF clause
label_2: ; //end IF
//statement here,line 24

// % Lines 25--26:
//

//D  = 0.5*Ts;

tmcScalar(reg[34],5.000000000000000e-001);

tmcMul(reg[36],reg[34],Ts);

tmcAssign(D,reg[36]);
//statement here,line 26

// % Lines 27--27:
//PhaseM=40;GainM=-8;

tmcScalar(reg[38],4.000000000000000e+001);

tmcAssign(PhaseM,reg[38]);
//statement here,line 27

tmcScalar(reg[40],8.000000000000000e+000);
tmcNeg(reg[41],reg[40]);

tmcAssign(GainM,reg[41]);
//statement here,line 27

// % Lines 28--28:
//MaxW = (PhaseM/360)*2*pi / (Ts+D);


tmcScalar(reg[44],3.600000000000000e+002);
tmcDiv(reg[45],PhaseM,reg[44]);
tmcScalar(reg[46],2.000000000000000e+000);
tmcMul(reg[47],reg[45],reg[46]);
//CALL function
tmcReallocRegister(reg[48]);
tmcpi(1,0, reg[48]);
tmcMul(reg[49],reg[47],reg[48]);


tmcAdd(reg[52],Ts,D);
tmcDiv(reg[53],reg[49],reg[52]);

tmcAssign(MaxW,reg[53]);
//statement here,line 28

// % Lines 29--29:
//L1 = -10^(GainM/20);

tmcScalar(reg[55],1.000000000000000e+001);

tmcScalar(reg[57],2.000000000000000e+001);
tmcDiv(reg[58],GainM,reg[57]);
tmcPower(reg[59],reg[55],reg[58]);
tmcNeg(reg[60],reg[59]);

tmcAssign(L1,reg[60]);
//statement here,line 29

// % Lines 30--30:
//L2 = exp(1j*(-pi + (PhaseM/360)*2*pi));

tmcComplexScalar(reg[62],0.000000000000000e+000,1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[63]);
tmcpi(1,0, reg[63]);
tmcNeg(reg[64],reg[63]);

tmcScalar(reg[66],3.600000000000000e+002);
tmcDiv(reg[67],PhaseM,reg[66]);
tmcScalar(reg[68],2.000000000000000e+000);
tmcMul(reg[69],reg[67],reg[68]);
//CALL function
tmcReallocRegister(reg[70]);
tmcpi(1,0, reg[70]);
tmcMul(reg[71],reg[69],reg[70]);
tmcAdd(reg[72],reg[64],reg[71]);
tmcMul(reg[73],reg[62],reg[72]);
//CALL function
tmcReallocRegister(reg[74]);
tmcexp(1,1, reg[74], reg[73]);

tmcAssign(L2,reg[74]);
//statement here,line 30

// % Lines 31--31:
//w1 = linspace(0.01*MaxW,MaxW*10,2000);

tmcScalar(reg[76],1.000000000000000e-002);

tmcMul(reg[78],reg[76],MaxW);

tmcScalar(reg[80],1.000000000000000e+001);
tmcMul(reg[81],MaxW,reg[80]);
tmcScalar(reg[82],2.000000000000000e+003);
//CALL function
tmcReallocRegister(reg[83]);
tmclinspace(1,3, reg[83], reg[78], reg[81], reg[82]);

tmcAssign(w1,reg[83]);
//statement here,line 31

// % Lines 32--32:
//s1 = j*w1;

//CALL function
tmcReallocRegister(reg[85]);
tmcj(1,0, reg[85]);

tmcMul(reg[87],reg[85],w1);

tmcAssign(s1,reg[87]);
//statement here,line 32

// % Lines 33--33:
//B1=exp(-(D+Ts)*s1);



tmcAdd(reg[91],D,Ts);
tmcNeg(reg[92],reg[91]);

tmcMul(reg[94],reg[92],s1);
//CALL function
tmcReallocRegister(reg[95]);
tmcexp(1,1, reg[95], reg[94]);

tmcAssign(B1,reg[95]);
//statement here,line 33

// % Lines 34--34:
//LL1 = L1./B1.*(s1*R+s1.*s1*L);



tmcDivScalar(reg[99],L1,B1);


tmcMul(reg[102],s1,R);


tmcMulScalar(reg[105],s1,s1);

tmcMul(reg[107],reg[105],L);
tmcAdd(reg[108],reg[102],reg[107]);
tmcMulScalar(reg[109],reg[99],reg[108]);

tmcAssign(LL1,reg[109]);
//statement here,line 34

// % Lines 35--35:
//Ki=(real(LL1));


//CALL function
tmcReallocRegister(reg[112]);
tmcreal(1,1, reg[112], LL1);

tmcAssign(Ki,reg[112]);
//statement here,line 35

// % Lines 36--36:
//Kp=(imag(LL1)./w1);


//CALL function
tmcReallocRegister(reg[115]);
tmcimag(1,1, reg[115], LL1);

tmcDivScalar(reg[117],reg[115],w1);

tmcAssign(Kp,reg[117]);
//statement here,line 36

// % Lines 37--37:
//II=find(Ki>0 & Kp>0 );


tmcScalar(reg[120],0.000000000000000e+000);
tmcGt(reg[121],Ki,reg[120]);

tmcScalar(reg[123],0.000000000000000e+000);
tmcGt(reg[124],Kp,reg[123]);
tmcAndScalar(reg[125],reg[121],reg[124]);
//CALL function
tmcReallocRegister(reg[126]);
tmcReallocRegister(reg[127]);
tmcReallocRegister(reg[128]);
tmcfind(1,1, reg[126], reg[127], reg[128], reg[125],NULL,NULL);

tmcAssign(II,reg[126]);
//statement here,line 37

// % Lines 38--38:
//Ki=Ki(II);



tmcGetByIndex(reg[132],Ki,1,II);

tmcAssign(Ki,reg[132]);
//statement here,line 38

// % Lines 39--39:
//Kp=Kp(II);



tmcGetByIndex(reg[136],Kp,1,II);

tmcAssign(Kp,reg[136]);
//statement here,line 39

// % Lines 40--46:
//

//% figure(100);

//% subplot(2,1,1);

//% plot(w1,Kp,'r' );grid on;legend('kp');

//% subplot(2,1,2);

//% plot( w1,Ki,'b');grid on;legend('ki');

//w = logspace(log10(1) ,log10(0.5./Ts*2*pi),1000);

tmcScalar(reg[138],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[139]);
tmclog10(1,1, reg[139], reg[138]);
tmcScalar(reg[140],5.000000000000000e-001);

tmcDivScalar(reg[142],reg[140],Ts);
tmcScalar(reg[143],2.000000000000000e+000);
tmcMul(reg[144],reg[142],reg[143]);
//CALL function
tmcReallocRegister(reg[145]);
tmcpi(1,0, reg[145]);
tmcMul(reg[146],reg[144],reg[145]);
//CALL function
tmcReallocRegister(reg[147]);
tmclog10(1,1, reg[147], reg[146]);
tmcScalar(reg[148],1.000000000000000e+003);
//CALL function
tmcReallocRegister(reg[149]);
tmclogspace(1,3, reg[149], reg[139], reg[147], reg[148]);

tmcAssign(w,reg[149]);
//statement here,line 46

// % Lines 47--47:
//s = 1j*w;

tmcComplexScalar(reg[151],0.000000000000000e+000,1.000000000000000e+000);

tmcMul(reg[153],reg[151],w);

tmcAssign(s,reg[153]);
//statement here,line 47

// % Lines 48--48:
//z = s*Ts;



tmcMul(reg[157],s,Ts);

tmcAssign(z,reg[157]);
//statement here,line 48

// % Lines 49--49:
//Ph2=angle(L2);


//CALL function
tmcReallocRegister(reg[160]);
tmcangle(1,1, reg[160], L2);

tmcAssign(Ph2,reg[160]);
//statement here,line 49

// % Lines 50--51:
//if Ph2>0

//    Ph2=Ph2-2*pi;


tmcScalar(reg[163],0.000000000000000e+000);
tmcGt(reg[164],Ph2,reg[163]);
if(tmcIsFalse(reg[164])) goto label_5; // goto to the end of the clause if the expression is false

tmcScalar(reg[166],2.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[167]);
tmcpi(1,0, reg[167]);
tmcMul(reg[168],reg[166],reg[167]);
tmcSub(reg[169],Ph2,reg[168]);

tmcAssign(Ph2,reg[169]);
//statement here,line 51

// % Lines 52--52:
//end

goto label_4; //branch to end IF
label_5: ; //end IF clause
label_4: ; //end IF
//statement here,line 52

// % Lines 53--54:
//

//Sol_opt=[];Ovs_Opt=[];Lopen_opt=[];

tmcCreateMatrixEmpty(reg[171]);

tmcAssign(Sol_opt,reg[171]);
//statement here,line 54

tmcCreateMatrixEmpty(reg[173]);

tmcAssign(Ovs_Opt,reg[173]);
//statement here,line 54

tmcCreateMatrixEmpty(reg[175]);

tmcAssign(Lopen_opt,reg[175]);
//statement here,line 54

// % Lines 55--56:
//for NomC=[0.8:0.05:1.2]*Ovs

//    figure(300);%clf;

tmcScalar(reg[177],8.000000000000000e-001);
tmcScalar(reg[178],1.200000000000000e+000);
tmcScalar(reg[179],5.000000000000000e-002);
tmcCreateColonBaseIncLimit(reg[180],reg[177],reg[179],reg[178]);
tmcCollectColumns(reg[181],1,reg[180]);
tmcCollectRows(reg[182],1,reg[181]);

tmcMul(reg[184],reg[182],Ovs);
tmcForIterInit(reg[185],reg[184],NomC);
label_8: ; //FOR begin
if(tmcForIterNext(reg[185],reg[184])) goto label_7; // exit for
tmcScalar(reg[186],3.000000000000000e+002);
//CALL function
tmcReallocRegister(reg[187]);
tmcfigure(0,1, reg[187], reg[186]);
//statement here,line 56

// % Lines 57--57:
//    Sol=[];

tmcCreateMatrixEmpty(reg[188]);

tmcAssign(Sol,reg[188]);
//statement here,line 57

// % Lines 58--59:
//    for kk=1:length(Kp)

//        Lopen = (Kp(kk)+Ki(kk)./s)./(R+s*L) .* exp(-(D+Ts).*s);

tmcScalar(reg[190],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[192]);
tmclength(1,1, reg[192], Kp);
tmcCreateColonBaseLimit(reg[193],reg[190],reg[192]);
tmcForIterInit(reg[194],reg[193],kk);
label_11: ; //FOR begin
if(tmcForIterNext(reg[194],reg[193])) goto label_10; // exit for


tmcGetByIndex(reg[197],Kp,1,kk);


tmcGetByIndex(reg[200],Ki,1,kk);

tmcDivScalar(reg[202],reg[200],s);
tmcAdd(reg[203],reg[197],reg[202]);



tmcMul(reg[207],s,L);
tmcAdd(reg[208],R,reg[207]);
tmcDivScalar(reg[209],reg[203],reg[208]);


tmcAdd(reg[212],D,Ts);
tmcNeg(reg[213],reg[212]);

tmcMulScalar(reg[215],reg[213],s);
//CALL function
tmcReallocRegister(reg[216]);
tmcexp(1,1, reg[216], reg[215]);
tmcMulScalar(reg[217],reg[209],reg[216]);

tmcAssign(Lopen,reg[217]);
//statement here,line 59

// % Lines 60--61:
//        %  Lopen = (Kp(kk)+Ts*Ki(kk)./(z-1))./(R+s*L) .* exp(-(D+Ts).*s);

//        II1 = find( abs(Lopen)>1);


//CALL function
tmcReallocRegister(reg[220]);
tmcabs(1,1, reg[220], Lopen);
tmcScalar(reg[221],1.000000000000000e+000);
tmcGt(reg[222],reg[220],reg[221]);
//CALL function
tmcReallocRegister(reg[223]);
tmcReallocRegister(reg[224]);
tmcReallocRegister(reg[225]);
tmcfind(1,1, reg[223], reg[224], reg[225], reg[222],NULL,NULL);

tmcAssign(II1,reg[223]);
//statement here,line 61

// % Lines 62--63:
//        if ~isempty(II1)

//            II1=II1(end);


//CALL function
tmcReallocRegister(reg[228]);
tmcisempty(1,1, reg[228], II1);
tmcNot(reg[229],reg[228]);
if(tmcIsFalse(reg[229])) goto label_13; // goto to the end of the clause if the expression is false

tmcGetEnd(reg[231],II1,1,1);
tmcGetByIndex(reg[232],II1,1,reg[231]);

tmcAssign(II1,reg[232]);
//statement here,line 63

// % Lines 64--64:
//            Ph1 = angle(Lopen(II1));



tmcGetByIndex(reg[236],Lopen,1,II1);
//CALL function
tmcReallocRegister(reg[237]);
tmcangle(1,1, reg[237], reg[236]);

tmcAssign(Ph1,reg[237]);
//statement here,line 64

// % Lines 65--66:
//            if Ph1>0

//                Ph1=Ph1-2*pi;


tmcScalar(reg[240],0.000000000000000e+000);
tmcGt(reg[241],Ph1,reg[240]);
if(tmcIsFalse(reg[241])) goto label_15; // goto to the end of the clause if the expression is false

tmcScalar(reg[243],2.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[244]);
tmcpi(1,0, reg[244]);
tmcMul(reg[245],reg[243],reg[244]);
tmcSub(reg[246],Ph1,reg[245]);

tmcAssign(Ph1,reg[246]);
//statement here,line 66

// % Lines 67--67:
//            end

goto label_14; //branch to end IF
label_15: ; //end IF clause
label_14: ; //end IF
//statement here,line 67

// % Lines 68--69:
//        else

//            Ph1 = -100;

goto label_12; //branch to end IF
label_13: ; //end IF clause
tmcScalar(reg[248],1.000000000000000e+002);
tmcNeg(reg[249],reg[248]);

tmcAssign(Ph1,reg[249]);
//statement here,line 69

// % Lines 70--70:
//        end

label_16: ; //end IF clause
label_12: ; //end IF
//statement here,line 70

// % Lines 71--72:
//        

//        CL = abs(Lopen./(1+Lopen));


tmcScalar(reg[252],1.000000000000000e+000);

tmcAdd(reg[254],reg[252],Lopen);
tmcDivScalar(reg[255],Lopen,reg[254]);
//CALL function
tmcReallocRegister(reg[256]);
tmcabs(1,1, reg[256], reg[255]);

tmcAssign(CL,reg[256]);
//statement here,line 72

// % Lines 73--78:
//        % Ph1=1000;

//        if ~isempty(II1) && Ph1 >= Ph2 && max(abs(CL)) < NomC && max(abs(CL)) > 1.05 

//%             plot(unwrap(angle(Lopen))/pi*180,20*log10(abs(Lopen)),'b',...

//%                 angle(L1)/pi*180-360,20*log10(abs(L1)),'go',...

//%                 angle(L2)/pi*180 ,20*log10(abs(L2)),'ro');grid on;hold on;

//            Sol=[ Sol ; Kp(kk),Ki(kk),w(II1)/2/pi];


//CALL function
tmcReallocRegister(reg[262]);
tmcisempty(1,1, reg[262], II1);
tmcNot(reg[263],reg[262]);
if(tmcIsFalse(reg[263])) {
	tmcAssignFalse(reg[260]); goto label_21; } // return(false) boolean_and expr


tmcGe(reg[266],Ph1,Ph2);
tmcAssignBool(reg[260],reg[266]);
label_21: ; //end boolean expr
if(tmcIsFalse(reg[260])) {
	tmcAssignFalse(reg[259]); goto label_20; } // return(false) boolean_and expr

//CALL function
tmcReallocRegister(reg[268]);
tmcabs(1,1, reg[268], CL);
//CALL function
tmcReallocRegister(reg[269]);
tmcReallocRegister(reg[270]);
tmcmax(1,1, reg[269], reg[270], reg[268],NULL,NULL);

tmcLt(reg[272],reg[269],NomC);
tmcAssignBool(reg[259],reg[272]);
label_20: ; //end boolean expr
if(tmcIsFalse(reg[259])) {
	tmcAssignFalse(reg[258]); goto label_19; } // return(false) boolean_and expr

//CALL function
tmcReallocRegister(reg[274]);
tmcabs(1,1, reg[274], CL);
//CALL function
tmcReallocRegister(reg[275]);
tmcReallocRegister(reg[276]);
tmcmax(1,1, reg[275], reg[276], reg[274],NULL,NULL);
tmcScalar(reg[277],1.050000000000000e+000);
tmcGt(reg[278],reg[275],reg[277]);
tmcAssignBool(reg[258],reg[278]);
label_19: ; //end boolean expr
if(tmcIsFalse(reg[258])) goto label_18; // goto to the end of the clause if the expression is false

tmcCollectColumns(reg[280],1,Sol);


tmcGetByIndex(reg[283],Kp,1,kk);


tmcGetByIndex(reg[286],Ki,1,kk);


tmcGetByIndex(reg[289],w,1,II1);
tmcScalar(reg[290],2.000000000000000e+000);
tmcDiv(reg[291],reg[289],reg[290]);
//CALL function
tmcReallocRegister(reg[292]);
tmcpi(1,0, reg[292]);
tmcDiv(reg[293],reg[291],reg[292]);
tmcCollectColumns(reg[294],3,reg[283],reg[286],reg[293]);
tmcCollectRows(reg[295],2,reg[280],reg[294]);

tmcAssign(Sol,reg[295]);
//statement here,line 78

// % Lines 79--79:
//        end

goto label_17; //branch to end IF
label_18: ; //end IF clause
label_17: ; //end IF
//statement here,line 79

// % Lines 80--80:
//    end

label_9: ; //FOR end
goto label_11; //branch to FOR begin
label_10: ; //FOR exit
//statement here,line 80

// % Lines 81--84:
//    %disp(Sol)

//    if  isempty(Sol)

//        % no solution found

//        disp('no solution found');


//CALL function
tmcReallocRegister(reg[298]);
tmcisempty(1,1, reg[298], Sol);
if(tmcIsFalse(reg[298])) goto label_23; // goto to the end of the clause if the expression is false
tmcCreateString(reg[300],"no solution found");
//CALL function
tmcReallocRegister(reg[301]);
tmcdisp(0,1, reg[301], reg[300]);
//statement here,line 84

// % Lines 85--85:
//        continue;

goto label_6; //continue to WHILE end
//statement here,line 85

// % Lines 86--86:
//    end

goto label_22; //branch to end IF
label_23: ; //end IF clause
label_22: ; //end IF
//statement here,line 86

// % Lines 87--87:
//    [YY,n]=max(Sol(:,2));


tmcCreateMagicColon(reg[303]);
tmcScalar(reg[304],2.000000000000000e+000);
tmcGetByIndex(reg[305],Sol,2,reg[303],reg[304]);
//CALL function
tmcReallocRegister(reg[306]);
tmcReallocRegister(reg[307]);
tmcmax(2,1, reg[306], reg[307], reg[305],NULL,NULL);

tmcAssign(YY,reg[306]);

tmcAssign(n,reg[307]);
//statement here,line 87

// % Lines 88--88:
//    kp0=Sol(n,1);ki0=Sol(n,2);



tmcScalar(reg[312],1.000000000000000e+000);
tmcGetByIndex(reg[313],Sol,2,n,reg[312]);

tmcAssign(kp0,reg[313]);
//statement here,line 88



tmcScalar(reg[317],2.000000000000000e+000);
tmcGetByIndex(reg[318],Sol,2,n,reg[317]);

tmcAssign(ki0,reg[318]);
//statement here,line 88

// % Lines 89--89:
//    Lopen0 = (kp0+ki0./s)./(R+s*L) .* exp(-(D+Ts).*s);




tmcDivScalar(reg[323],ki0,s);
tmcAdd(reg[324],kp0,reg[323]);



tmcMul(reg[328],s,L);
tmcAdd(reg[329],R,reg[328]);
tmcDivScalar(reg[330],reg[324],reg[329]);


tmcAdd(reg[333],D,Ts);
tmcNeg(reg[334],reg[333]);

tmcMulScalar(reg[336],reg[334],s);
//CALL function
tmcReallocRegister(reg[337]);
tmcexp(1,1, reg[337], reg[336]);
tmcMulScalar(reg[338],reg[330],reg[337]);

tmcAssign(Lopen0,reg[338]);
//statement here,line 89

// % Lines 90--94:
//    %  Lopen0 = (kp0+Ts*ki0./(z-1))./(R+s*L) .* exp(-(D+Ts).*s);

//    

//    plot(unwrap(angle(Lopen0))/pi*180,20*log10(abs(Lopen0)),'m.-',...

//        angle(L1)/pi*180-360,20*log10(abs(L1)),'go',...

//        angle(L2)/pi*180 ,20*log10(abs(L2)),'ro');grid on;hold on;


//CALL function
tmcReallocRegister(reg[341]);
tmcangle(1,1, reg[341], Lopen0);
//CALL function
tmcReallocRegister(reg[342]);
tmcunwrap(1,1, reg[342], reg[341],NULL);
//CALL function
tmcReallocRegister(reg[343]);
tmcpi(1,0, reg[343]);
tmcDiv(reg[344],reg[342],reg[343]);
tmcScalar(reg[345],1.800000000000000e+002);
tmcMul(reg[346],reg[344],reg[345]);
tmcScalar(reg[347],2.000000000000000e+001);

//CALL function
tmcReallocRegister(reg[349]);
tmcabs(1,1, reg[349], Lopen0);
//CALL function
tmcReallocRegister(reg[350]);
tmclog10(1,1, reg[350], reg[349]);
tmcMul(reg[351],reg[347],reg[350]);
tmcCreateString(reg[352],"m.-");

//CALL function
tmcReallocRegister(reg[354]);
tmcangle(1,1, reg[354], L1);
//CALL function
tmcReallocRegister(reg[355]);
tmcpi(1,0, reg[355]);
tmcDiv(reg[356],reg[354],reg[355]);
tmcScalar(reg[357],1.800000000000000e+002);
tmcMul(reg[358],reg[356],reg[357]);
tmcScalar(reg[359],3.600000000000000e+002);
tmcSub(reg[360],reg[358],reg[359]);
tmcScalar(reg[361],2.000000000000000e+001);

//CALL function
tmcReallocRegister(reg[363]);
tmcabs(1,1, reg[363], L1);
//CALL function
tmcReallocRegister(reg[364]);
tmclog10(1,1, reg[364], reg[363]);
tmcMul(reg[365],reg[361],reg[364]);
tmcCreateString(reg[366],"go");

//CALL function
tmcReallocRegister(reg[368]);
tmcangle(1,1, reg[368], L2);
//CALL function
tmcReallocRegister(reg[369]);
tmcpi(1,0, reg[369]);
tmcDiv(reg[370],reg[368],reg[369]);
tmcScalar(reg[371],1.800000000000000e+002);
tmcMul(reg[372],reg[370],reg[371]);
tmcScalar(reg[373],2.000000000000000e+001);

//CALL function
tmcReallocRegister(reg[375]);
tmcabs(1,1, reg[375], L2);
//CALL function
tmcReallocRegister(reg[376]);
tmclog10(1,1, reg[376], reg[375]);
tmcMul(reg[377],reg[373],reg[376]);
tmcCreateString(reg[378],"ro");
//CALL function
tmcReallocRegister(reg[379]);
tmcplot(0,9, reg[379], reg[346], reg[351], reg[352], reg[360], reg[365], reg[366], reg[372], reg[377],
 reg[378]);
//statement here,line 94

tmcCreateString(reg[380],"on");
//CALL function
tmcReallocRegister(reg[381]);
tmcgrid(0,1, reg[381], reg[380]);
//statement here,line 94

tmcCreateString(reg[382],"on");
//CALL function
tmcReallocRegister(reg[383]);
tmchold(0,1, reg[383], reg[382]);
//statement here,line 94

// % Lines 95--101:
//    

//%     sysP = tf(1,[L,R]) * tf([kp0,ki0],[1,0] );

//%     sysCL = sysP/(1+sysP);

//    % figure(999);

//    % step(sysCL,3e-3);

//    

//    figure(1000);

tmcScalar(reg[384],1.000000000000000e+003);
//CALL function
tmcReallocRegister(reg[385]);
tmcfigure(0,1, reg[385], reg[384]);
//statement here,line 101

// % Lines 102--103:
//    

//    rden= -R/L;


tmcNeg(reg[387],R);

tmcDiv(reg[389],reg[387],L);

tmcAssign(rden,reg[389]);
//statement here,line 103

// % Lines 104--104:
//    rdend=exp(rden*Ts);



tmcMul(reg[393],rden,Ts);
//CALL function
tmcReallocRegister(reg[394]);
tmcexp(1,1, reg[394], reg[393]);

tmcAssign(rdend,reg[394]);
//statement here,line 104

// % Lines 105--105:
//    sysP1d=[0, 1/R*(1-rdend) ; 1,-rdend];

tmcScalar(reg[396],0.000000000000000e+000);
tmcScalar(reg[397],1.000000000000000e+000);

tmcDiv(reg[399],reg[397],R);
tmcScalar(reg[400],1.000000000000000e+000);

tmcSub(reg[402],reg[400],rdend);
tmcMul(reg[403],reg[399],reg[402]);
tmcCollectColumns(reg[404],2,reg[396],reg[403]);
tmcScalar(reg[405],1.000000000000000e+000);

tmcNeg(reg[407],rdend);
tmcCollectColumns(reg[408],2,reg[405],reg[407]);
tmcCollectRows(reg[409],2,reg[404],reg[408]);

tmcAssign(sysP1d,reg[409]);
//statement here,line 105

// % Lines 106--106:
//    sysP2d=[kp0 ,ki0*Ts-kp0 ; 1,-1];




tmcMul(reg[414],ki0,Ts);

tmcSub(reg[416],reg[414],kp0);
tmcCollectColumns(reg[417],2,kp0,reg[416]);
tmcScalar(reg[418],1.000000000000000e+000);
tmcScalar(reg[419],1.000000000000000e+000);
tmcNeg(reg[420],reg[419]);
tmcCollectColumns(reg[421],2,reg[418],reg[420]);
tmcCollectRows(reg[422],2,reg[417],reg[421]);

tmcAssign(sysP2d,reg[422]);
//statement here,line 106

// % Lines 107--108:
//    sysPd = [conv(sysP1d(1,:),sysP2d(1,:)) ; ...

//            conv(sysP1d(2,:),sysP2d(2,:))];


tmcScalar(reg[425],1.000000000000000e+000);
tmcCreateMagicColon(reg[426]);
tmcGetByIndex(reg[427],sysP1d,2,reg[425],reg[426]);

tmcScalar(reg[429],1.000000000000000e+000);
tmcCreateMagicColon(reg[430]);
tmcGetByIndex(reg[431],sysP2d,2,reg[429],reg[430]);
//CALL function
tmcReallocRegister(reg[432]);
tmcconv(1,2, reg[432], reg[427], reg[431]);
tmcCollectColumns(reg[433],1,reg[432]);

tmcScalar(reg[435],2.000000000000000e+000);
tmcCreateMagicColon(reg[436]);
tmcGetByIndex(reg[437],sysP1d,2,reg[435],reg[436]);

tmcScalar(reg[439],2.000000000000000e+000);
tmcCreateMagicColon(reg[440]);
tmcGetByIndex(reg[441],sysP2d,2,reg[439],reg[440]);
//CALL function
tmcReallocRegister(reg[442]);
tmcconv(1,2, reg[442], reg[437], reg[441]);
tmcCollectColumns(reg[443],1,reg[442]);
tmcCollectRows(reg[444],2,reg[433],reg[443]);

tmcAssign(sysPd,reg[444]);
//statement here,line 108

// % Lines 109--109:
//    sysPCLd = [ sysPd(1,:); sysPd(1,:)+sysPd(2,:) ];


tmcScalar(reg[447],1.000000000000000e+000);
tmcCreateMagicColon(reg[448]);
tmcGetByIndex(reg[449],sysPd,2,reg[447],reg[448]);
tmcCollectColumns(reg[450],1,reg[449]);

tmcScalar(reg[452],1.000000000000000e+000);
tmcCreateMagicColon(reg[453]);
tmcGetByIndex(reg[454],sysPd,2,reg[452],reg[453]);

tmcScalar(reg[456],2.000000000000000e+000);
tmcCreateMagicColon(reg[457]);
tmcGetByIndex(reg[458],sysPd,2,reg[456],reg[457]);
tmcAdd(reg[459],reg[454],reg[458]);
tmcCollectColumns(reg[460],1,reg[459]);
tmcCollectRows(reg[461],2,reg[450],reg[460]);

tmcAssign(sysPCLd,reg[461]);
//statement here,line 109

// % Lines 110--112:
//    

//    

//    num = sysPCLd(1,:);den=sysPCLd(2,:);


tmcScalar(reg[464],1.000000000000000e+000);
tmcCreateMagicColon(reg[465]);
tmcGetByIndex(reg[466],sysPCLd,2,reg[464],reg[465]);

tmcAssign(num,reg[466]);
//statement here,line 112


tmcScalar(reg[469],2.000000000000000e+000);
tmcCreateMagicColon(reg[470]);
tmcGetByIndex(reg[471],sysPCLd,2,reg[469],reg[470]);

tmcAssign(den,reg[471]);
//statement here,line 112

// % Lines 113--113:
//    yy=filter_( num,den,ones(1,floor(3e-3/Ts)));



tmcScalar(reg[475],1.000000000000000e+000);
tmcScalar(reg[476],3.000000000000000e-003);

tmcDiv(reg[478],reg[476],Ts);
//CALL function
tmcReallocRegister(reg[479]);
tmcfloor(1,1, reg[479], reg[478]);
//CALL function
tmcReallocRegister(reg[480]);
tmcones(1,2, reg[480], reg[475], reg[479]);
//CALL function
tmcReallocRegister(reg[481]);
tmcfilter_(1,3, reg[481], num, den, reg[480]);

tmcAssign(yy,reg[481]);
//statement here,line 113

// % Lines 114--114:
//    plot([0:length(yy)-1]*Ts,yy,'b');grid on;hold on;

tmcScalar(reg[483],0.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[485]);
tmclength(1,1, reg[485], yy);
tmcScalar(reg[486],1.000000000000000e+000);
tmcSub(reg[487],reg[485],reg[486]);
tmcCreateColonBaseLimit(reg[488],reg[483],reg[487]);
tmcCollectColumns(reg[489],1,reg[488]);
tmcCollectRows(reg[490],1,reg[489]);

tmcMul(reg[492],reg[490],Ts);

tmcCreateString(reg[494],"b");
//CALL function
tmcReallocRegister(reg[495]);
tmcplot(0,3, reg[495], reg[492], yy, reg[494]);
//statement here,line 114

tmcCreateString(reg[496],"on");
//CALL function
tmcReallocRegister(reg[497]);
tmcgrid(0,1, reg[497], reg[496]);
//statement here,line 114

tmcCreateString(reg[498],"on");
//CALL function
tmcReallocRegister(reg[499]);
tmchold(0,1, reg[499], reg[498]);
//statement here,line 114

// % Lines 115--115:
//    ActOvs = max(yy);


//CALL function
tmcReallocRegister(reg[501]);
tmcReallocRegister(reg[502]);
tmcmax(1,1, reg[501], reg[502], yy,NULL,NULL);

tmcAssign(ActOvs,reg[501]);
//statement here,line 115

// % Lines 116--117:
//    if isempty(Ovs_Opt) || abs(ActOvs-Ovs) < abs(Ovs_Opt-Ovs)

//        Ovs_Opt=ActOvs;Lopen_opt=Lopen0;


//CALL function
tmcReallocRegister(reg[506]);
tmcisempty(1,1, reg[506], Ovs_Opt);
if(tmcIsTrue(reg[506])) {
	tmcAssignTrue(reg[504]); goto label_26;} // return(true) boolean_or expr


tmcSub(reg[509],ActOvs,Ovs);
//CALL function
tmcReallocRegister(reg[510]);
tmcabs(1,1, reg[510], reg[509]);


tmcSub(reg[513],Ovs_Opt,Ovs);
//CALL function
tmcReallocRegister(reg[514]);
tmcabs(1,1, reg[514], reg[513]);
tmcLt(reg[515],reg[510],reg[514]);
tmcAssignBool(reg[504],reg[515]);
label_26: ; //end boolean expr
if(tmcIsFalse(reg[504])) goto label_25; // goto to the end of the clause if the expression is false


tmcAssign(Ovs_Opt,ActOvs);
//statement here,line 117



tmcAssign(Lopen_opt,Lopen0);
//statement here,line 117

// % Lines 118--118:
//        CL_Opt=Lopen_opt./(1+Lopen_opt);


tmcScalar(reg[521],1.000000000000000e+000);

tmcAdd(reg[523],reg[521],Lopen_opt);
tmcDivScalar(reg[524],Lopen_opt,reg[523]);

tmcAssign(CL_Opt,reg[524]);
//statement here,line 118

// % Lines 119--119:
//        Sol_opt = [kp0,ki0];



tmcCollectColumns(reg[528],2,kp0,ki0);
tmcCollectRows(reg[529],1,reg[528]);

tmcAssign(Sol_opt,reg[529]);
//statement here,line 119

// % Lines 120--120:
//        yy_opt=yy;



tmcAssign(yy_opt,yy);
//statement here,line 120

// % Lines 121--121:
//    end

goto label_24; //branch to end IF
label_25: ; //end IF clause
label_24: ; //end IF
//statement here,line 121

// % Lines 122--123:
//    

//end

label_6: ; //FOR end
goto label_8; //branch to FOR begin
label_7: ; //FOR exit
//statement here,line 123

// % Lines 124--124:
//plot([0:length(yy)-1]*Ts,yy_opt,'r-');grid on;hold on;

tmcScalar(reg[533],0.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[535]);
tmclength(1,1, reg[535], yy);
tmcScalar(reg[536],1.000000000000000e+000);
tmcSub(reg[537],reg[535],reg[536]);
tmcCreateColonBaseLimit(reg[538],reg[533],reg[537]);
tmcCollectColumns(reg[539],1,reg[538]);
tmcCollectRows(reg[540],1,reg[539]);

tmcMul(reg[542],reg[540],Ts);

tmcCreateString(reg[544],"r-");
//CALL function
tmcReallocRegister(reg[545]);
tmcplot(0,3, reg[545], reg[542], yy_opt, reg[544]);
//statement here,line 124

tmcCreateString(reg[546],"on");
//CALL function
tmcReallocRegister(reg[547]);
tmcgrid(0,1, reg[547], reg[546]);
//statement here,line 124

tmcCreateString(reg[548],"on");
//CALL function
tmcReallocRegister(reg[549]);
tmchold(0,1, reg[549], reg[548]);
//statement here,line 124

// % Lines 125--126:
//

//PropGain=Sol_opt(1);


tmcScalar(reg[551],1.000000000000000e+000);
tmcGetByIndex(reg[552],Sol_opt,1,reg[551]);

tmcAssign(PropGain,reg[552]);
//statement here,line 126

// % Lines 127--127:
//IntGain=Sol_opt(2);


tmcScalar(reg[555],2.000000000000000e+000);
tmcGetByIndex(reg[556],Sol_opt,1,reg[555]);

tmcAssign(IntGain,reg[556]);
//statement here,line 127

// % Lines 128--128:
//FreqHz = w/2/pi;


tmcScalar(reg[559],2.000000000000000e+000);
tmcDiv(reg[560],w,reg[559]);
//CALL function
tmcReallocRegister(reg[561]);
tmcpi(1,0, reg[561]);
tmcDiv(reg[562],reg[560],reg[561]);

tmcAssign(FreqHz,reg[562]);
//statement here,line 128

// % Lines 129--129:
//FreqLen=length(FreqHz);


//CALL function
tmcReallocRegister(reg[565]);
tmclength(1,1, reg[565], FreqHz);

tmcAssign(FreqLen,reg[565]);
//statement here,line 129

// % Lines 130--130:
//CL_Opt=Lopen_opt./(1+Lopen_opt);


tmcScalar(reg[568],1.000000000000000e+000);

tmcAdd(reg[570],reg[568],Lopen_opt);
tmcDivScalar(reg[571],Lopen_opt,reg[570]);

tmcAssign(CL_Opt,reg[571]);
//statement here,line 130

// % Lines 131--131:
//OL_Mag = 20*log10(abs(Lopen_opt));

tmcScalar(reg[573],2.000000000000000e+001);

//CALL function
tmcReallocRegister(reg[575]);
tmcabs(1,1, reg[575], Lopen_opt);
//CALL function
tmcReallocRegister(reg[576]);
tmclog10(1,1, reg[576], reg[575]);
tmcMul(reg[577],reg[573],reg[576]);

tmcAssign(OL_Mag,reg[577]);
//statement here,line 131

// % Lines 132--132:
//OL_Ph = unwrap(angle(Lopen_opt))/pi*180;


//CALL function
tmcReallocRegister(reg[580]);
tmcangle(1,1, reg[580], Lopen_opt);
//CALL function
tmcReallocRegister(reg[581]);
tmcunwrap(1,1, reg[581], reg[580],NULL);
//CALL function
tmcReallocRegister(reg[582]);
tmcpi(1,0, reg[582]);
tmcDiv(reg[583],reg[581],reg[582]);
tmcScalar(reg[584],1.800000000000000e+002);
tmcMul(reg[585],reg[583],reg[584]);

tmcAssign(OL_Ph,reg[585]);
//statement here,line 132

// % Lines 133--133:
//CL_Mag = 20*log10(abs(CL_Opt));

tmcScalar(reg[587],2.000000000000000e+001);

//CALL function
tmcReallocRegister(reg[589]);
tmcabs(1,1, reg[589], CL_Opt);
//CALL function
tmcReallocRegister(reg[590]);
tmclog10(1,1, reg[590], reg[589]);
tmcMul(reg[591],reg[587],reg[590]);

tmcAssign(CL_Mag,reg[591]);
//statement here,line 133

// % Lines 134--134:
//CL_Ph = unwrap(angle(CL_Opt))/pi*180;


//CALL function
tmcReallocRegister(reg[594]);
tmcangle(1,1, reg[594], CL_Opt);
//CALL function
tmcReallocRegister(reg[595]);
tmcunwrap(1,1, reg[595], reg[594],NULL);
//CALL function
tmcReallocRegister(reg[596]);
tmcpi(1,0, reg[596]);
tmcDiv(reg[597],reg[595],reg[596]);
tmcScalar(reg[598],1.800000000000000e+002);
tmcMul(reg[599],reg[597],reg[598]);

tmcAssign(CL_Ph,reg[599]);
//statement here,line 134

// % Lines 135--135:
//RespTime = [0:length(yy_opt)-1]*Ts;

tmcScalar(reg[601],0.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[603]);
tmclength(1,1, reg[603], yy_opt);
tmcScalar(reg[604],1.000000000000000e+000);
tmcSub(reg[605],reg[603],reg[604]);
tmcCreateColonBaseLimit(reg[606],reg[601],reg[605]);
tmcCollectColumns(reg[607],1,reg[606]);
tmcCollectRows(reg[608],1,reg[607]);

tmcMul(reg[610],reg[608],Ts);

tmcAssign(RespTime,reg[610]);
//statement here,line 135

// % Lines 136--136:
//Resp=yy_opt;



tmcAssign(Resp,yy_opt);
//statement here,line 136

// % Lines 137--137:
//RespLen=length(RespTime);


//CALL function
tmcReallocRegister(reg[615]);
tmclength(1,1, reg[615], RespTime);

tmcAssign(RespLen,reg[615]);
//statement here,line 137

// % Lines 138--144:
//% figure(3000);

//% subplot(2,1,1);

//% semilogx(FreqHz,CL_Mag,'b');ylabel('db');grid on;

//% subplot(2,1,2);

//% semilogx(FreqHz,CL_Ph,'b');ylabel('Deg');grid on;xlabel('Hz');

//

//save('result.mat','PropGain','IntGain','OL_Mag','OL_Ph','CL_Mag','CL_Ph','RespTime','Resp','R','L','Ts','Ovs');

tmcCreateString(reg[617],"result.mat");
//CALL function save
tmcsave(0,13, reg[617], PropGain, "PropGain", IntGain, "IntGain", OL_Mag, "OL_Mag", OL_Ph, "OL_Ph", CL_Mag, "CL_Mag", CL_Ph, "CL_Ph", RespTime, "RespTime", Resp, "Resp",
 R, "R", L, "L", Ts, "Ts", Ovs, "Ovs");
//statement here,line 144

// % Lines 145--157:
//% 

//% figure(2000);

//% subplot(2,1,1);

//%bode(sysCL);

//

//

//

//

//

//

//

//

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(yy_opt);
tmcFreeLocalVar(CL_Opt);
tmcFreeLocalVar(ActOvs);
tmcFreeLocalVar(yy);
tmcFreeLocalVar(den);
tmcFreeLocalVar(num);
tmcFreeLocalVar(sysPCLd);
tmcFreeLocalVar(sysPd);
tmcFreeLocalVar(sysP2d);
tmcFreeLocalVar(sysP1d);
tmcFreeLocalVar(rdend);
tmcFreeLocalVar(rden);
tmcFreeLocalVar(Lopen0);
tmcFreeLocalVar(ki0);
tmcFreeLocalVar(kp0);
tmcFreeLocalVar(n);
tmcFreeLocalVar(YY);
tmcFreeLocalVar(CL);
tmcFreeLocalVar(Ph1);
tmcFreeLocalVar(II1);
tmcFreeLocalVar(Lopen);
tmcFreeLocalVar(kk);
tmcFreeLocalVar(Sol);
tmcFreeLocalVar(NomC);
tmcFreeLocalVar(Lopen_opt);
tmcFreeLocalVar(Ovs_Opt);
tmcFreeLocalVar(Sol_opt);
tmcFreeLocalVar(Ph2);
tmcFreeLocalVar(z);
tmcFreeLocalVar(s);
tmcFreeLocalVar(w);
tmcFreeLocalVar(II);
tmcFreeLocalVar(Kp);
tmcFreeLocalVar(Ki);
tmcFreeLocalVar(LL1);
tmcFreeLocalVar(B1);
tmcFreeLocalVar(s1);
tmcFreeLocalVar(w1);
tmcFreeLocalVar(L2);
tmcFreeLocalVar(L1);
tmcFreeLocalVar(MaxW);
tmcFreeLocalVar(GainM);
tmcFreeLocalVar(PhaseM);
tmcFreeLocalVar(D);
tmcFreeLocalVar(Ovs);
tmcFreeLocalVar(Ts);
tmcFreeLocalVar(L);
tmcFreeLocalVar(R);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(63);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 157

// % Lines 158--158:
