//File: TestO.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--2:
//function [PropGain,IntGain,FreqLen,FreqHz,OL_Mag,OL_Ph,CL_Mag,CL_Ph,RespLen,RespTime,Resp]=TestO(R,L,Ts,Ovs)

//save ('in1.mat','R','L','Ts','Ovs');

void tmcTestO(int nargout, int nargin,tmsMatrix *PropGain,tmsMatrix *IntGain,tmsMatrix *FreqLen,tmsMatrix *FreqHz,tmsMatrix *OL_Mag,tmsMatrix *OL_Ph,tmsMatrix *CL_Mag,tmsMatrix *CL_Ph,tmsMatrix *RespLen,tmsMatrix *RespTime,tmsMatrix *Resp
,tmsMatrix *R,tmsMatrix *L,tmsMatrix *Ts,tmsMatrix *Ovs) {
tmsMatrix **reg=tmcCreateRegFrame(28);

TRY
TMC_DBG_PUSH_STACK_VAR("TestO",15,
R,"R",
L,"L",
Ts,"Ts",
Ovs,"Ovs",
PropGain,"PropGain",
IntGain,"IntGain",
FreqLen,"FreqLen",
FreqHz,"FreqHz",
OL_Mag,"OL_Mag",
OL_Ph,"OL_Ph",
CL_Mag,"CL_Mag",
CL_Ph,"CL_Ph",
RespLen,"RespLen",
RespTime,"RespTime",
Resp,"Resp");

tmcCreateString(reg[1],"in1.mat");
//CALL function save
tmcsave(0,5, reg[1], R, "R", L, "L", Ts, "Ts", Ovs, "Ovs");
//statement here,line 2

// % Lines 3--3:
//[PropGain,IntGain,FreqLen,FreqHz,OL_Mag,OL_Ph,CL_Mag,CL_Ph,RespLen,RespTime,Resp]=getcurloop(R,L,Ts,Ovs);




//CALL function
tmcReallocRegister(reg[6]);
tmcReallocRegister(reg[7]);
tmcReallocRegister(reg[8]);
tmcReallocRegister(reg[9]);
tmcReallocRegister(reg[10]);
tmcReallocRegister(reg[11]);
tmcReallocRegister(reg[12]);
tmcReallocRegister(reg[13]);
tmcReallocRegister(reg[14]);
tmcReallocRegister(reg[15]);
tmcReallocRegister(reg[16]);
tmcgetcurloop(11,4, reg[6], reg[7], reg[8], reg[9], reg[10], reg[11], reg[12], reg[13],
 reg[14], reg[15], reg[16], R, L, Ts, Ovs);

tmcAssign(PropGain,reg[6]);

tmcAssign(IntGain,reg[7]);

tmcAssign(FreqLen,reg[8]);

tmcAssign(FreqHz,reg[9]);

tmcAssign(OL_Mag,reg[10]);

tmcAssign(OL_Ph,reg[11]);

tmcAssign(CL_Mag,reg[12]);

tmcAssign(CL_Ph,reg[13]);

tmcAssign(RespLen,reg[14]);

tmcAssign(RespTime,reg[15]);

tmcAssign(Resp,reg[16]);
//statement here,line 3

label_1: ; //end Function
FINALLY
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(15);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 3

// % Lines 4--4:
