//File: TestO.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--4:
//function y=TestO(x) 

//%addpath('D:\Data_D\HSKOST\TMC\TMC_forLibre\examples\AppSIMO\MexSRC\MexDLLS')

//%addpath('D:\Data_D\HSKOST\TMC\TMC_forLibre\examples\AppSIMO\MatSRC')

// global ite;

void tmcTestO(int nargout, int nargin,tmsMatrix *y
,tmsMatrix *x__input__tmc) {
tmsMatrix **reg=tmcCreateRegFrame(185);
tmsMatrix *x=tmcNewMatrix();
tmsMatrix *MG=tmcNewMatrix();
tmsMatrix *AL=tmcNewMatrix();
tmsMatrix *Ib=tmcNewMatrix();
tmsMatrix *S=tmcNewMatrix();
tmsMatrix *K=tmcNewMatrix();
tmsMatrix *a=tmcNewMatrix();
tmsMatrix *b=tmcNewMatrix();
tmsMatrix *Len=tmcNewMatrix();
tmsMatrix *e=tmcNewMatrix();
tmsMatrix *z=tmcNewMatrix();
tmsMatrix *k=tmcNewMatrix();
tmsMatrix *ep1=tmcNewMatrix();

tmcCopyMat(x,x__input__tmc);
TRY
TMC_DBG_PUSH_STACK_VAR("TestO",15,
x__input__tmc,"x__input__tmc",
y,"y",
x,"x",
MG,"MG",
AL,"AL",
Ib,"Ib",
S,"S",
K,"K",
a,"a",
b,"b",
Len,"Len",
e,"e",
z,"z",
k,"k",
ep1,"ep1");

//statement here,line 4

// % Lines 5--10:
//% A=[1,2;3,4];

//% B=[1;3];

//% C =A*B;

//% disp(C\B);

//% return;

//MG = 100;

tmcScalar(reg[1],1.000000000000000e+002);

tmcAssign(MG,reg[1]);
//statement here,line 10

// % Lines 11--11:
//AL = [10,100,100,200,300,400];

tmcScalar(reg[3],1.000000000000000e+001);
tmcScalar(reg[4],1.000000000000000e+002);
tmcScalar(reg[5],1.000000000000000e+002);
tmcScalar(reg[6],2.000000000000000e+002);
tmcScalar(reg[7],3.000000000000000e+002);
tmcScalar(reg[8],4.000000000000000e+002);
tmcCollectColumns(reg[9],6,reg[3],reg[4],reg[5],reg[6],reg[7],reg[8]);
tmcCollectRows(reg[10],1,reg[9]);

tmcAssign(AL,reg[10]);
//statement here,line 11

// % Lines 12--12:
//Ib    = find(AL(1:end-1)>=MG & AL(2:end)<MG); % HSKOST6p5


tmcScalar(reg[13],1.000000000000000e+000);
tmcGetEnd(reg[14],AL,1,1);
tmcScalar(reg[15],1.000000000000000e+000);
tmcSub(reg[16],reg[14],reg[15]);
tmcCreateColonBaseLimit(reg[17],reg[13],reg[16]);
tmcGetByIndex(reg[18],AL,1,reg[17]);

tmcGe(reg[20],reg[18],MG);

tmcScalar(reg[22],2.000000000000000e+000);
tmcGetEnd(reg[23],AL,1,1);
tmcCreateColonBaseLimit(reg[24],reg[22],reg[23]);
tmcGetByIndex(reg[25],AL,1,reg[24]);

tmcLt(reg[27],reg[25],MG);
tmcAndScalar(reg[28],reg[20],reg[27]);
//CALL function
tmcReallocRegister(reg[29]);
tmcReallocRegister(reg[30]);
tmcReallocRegister(reg[31]);
tmcfind(1,1, reg[29], reg[30], reg[31], reg[28],NULL,NULL);

tmcAssign(Ib,reg[29]);
//statement here,line 12

// % Lines 13--13:
//disp(Ib);


//CALL function
tmcReallocRegister(reg[34]);
tmcdisp(0,1, reg[34], Ib);
//statement here,line 13

// % Lines 14--14:
//return;

goto label_1; //branch to FUNCTION exit
//statement here,line 14

// % Lines 15--16:
//

//x = [1:100];

tmcScalar(reg[35],1.000000000000000e+000);
tmcScalar(reg[36],1.000000000000000e+002);
tmcCreateColonBaseLimit(reg[37],reg[35],reg[36]);
tmcCollectColumns(reg[38],1,reg[37]);
tmcCollectRows(reg[39],1,reg[38]);

tmcAssign(x,reg[39]);
//statement here,line 16

// % Lines 17--17:
//S=cell(2,1);

tmcScalar(reg[41],2.000000000000000e+000);
tmcScalar(reg[42],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[43]);
tmccell(1,2, reg[43], reg[41], reg[42]);

tmcAssign(S,reg[43]);
//statement here,line 17

// % Lines 18--18:
//S{1}.r=x;



tmcScalar(reg[47],1.000000000000000e+000);
tmcGetRefByIndexCell(pRefHelper,S,1,reg[47]);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x00720000);/* r */
tmcAssign(pRefHelper,x);
//statement here,line 18

// % Lines 19--19:
//S{2}.r=x*2;


tmcScalar(reg[50],2.000000000000000e+000);
tmcMul(reg[51],x,reg[50]);

tmcScalar(reg[53],2.000000000000000e+000);
tmcGetRefByIndexCell(pRefHelper,S,1,reg[53]);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x00720000);/* r */
tmcAssign(pRefHelper,reg[51]);
//statement here,line 19

// % Lines 20--20:
//S{end} = 44;

tmcScalar(reg[55],4.400000000000000e+001);

tmcGetEnd(reg[57],S,1,1);
tmcGetRefByIndexCell(pRefHelper,S,1,reg[57]);
tmcAssign(pRefHelper,reg[55]);
//statement here,line 20

// % Lines 21--21:
//disp(['R=',num2str(S{end-1}.r(end-1))]);

tmcCreateString(reg[58],"R=");

tmcGetEnd(reg[60],S,1,1);
tmcScalar(reg[61],1.000000000000000e+000);
tmcSub(reg[62],reg[60],reg[61]);
tmcGetByIndexCell(reg[63],S,1,reg[62]);
tmcGetByFieldHcode(reg[65],reg[63],0x00720000);/* r */
tmcGetEnd(reg[66],reg[65],1,1);
tmcScalar(reg[67],1.000000000000000e+000);
tmcSub(reg[68],reg[66],reg[67]);
tmcGetByIndex(reg[69],reg[65],1,reg[68]);
//CALL function
tmcReallocRegister(reg[70]);
tmcnum2str(1,1, reg[70], reg[69],NULL);
tmcCollectColumns(reg[71],2,reg[58],reg[70]);
tmcCollectRows(reg[72],1,reg[71]);
//CALL function
tmcReallocRegister(reg[73]);
tmcdisp(0,1, reg[73], reg[72]);
//statement here,line 21

// % Lines 22--22:
//disp(S);


//CALL function
tmcReallocRegister(reg[75]);
tmcdisp(0,1, reg[75], S);
//statement here,line 22

// % Lines 23--23:
//K=struct;

//CALL function
tmcReallocRegister(reg[76]);
tmcstruct(1,0, reg[76]);

tmcAssign(K,reg[76]);
//statement here,line 23

// % Lines 24--24:
//K.y=[1:100];

tmcScalar(reg[78],1.000000000000000e+000);
tmcScalar(reg[79],1.000000000000000e+002);
tmcCreateColonBaseLimit(reg[80],reg[78],reg[79]);
tmcCollectColumns(reg[81],1,reg[80]);
tmcCollectRows(reg[82],1,reg[81]);

tmcGetRefByFieldHcode(pRefHelper,K,0x00790000);/* y */
tmcAssign(pRefHelper,reg[82]);
//statement here,line 24

// % Lines 25--25:
//disp(K(end).y(end-3));


tmcGetEnd(reg[86],K,1,1);
tmcGetByIndex(reg[87],K,1,reg[86]);
tmcGetByFieldHcode(reg[89],reg[87],0x00790000);/* y */
tmcGetEnd(reg[90],reg[89],1,1);
tmcScalar(reg[91],3.000000000000000e+000);
tmcSub(reg[92],reg[90],reg[91]);
tmcGetByIndex(reg[93],reg[89],1,reg[92]);
//CALL function
tmcReallocRegister(reg[94]);
tmcdisp(0,1, reg[94], reg[93]);
//statement here,line 25

// % Lines 26--29:
//

//

//

//a = -5;

tmcScalar(reg[95],5.000000000000000e+000);
tmcNeg(reg[96],reg[95]);

tmcAssign(a,reg[96]);
//statement here,line 29

// % Lines 30--30:
//b =  50;

tmcScalar(reg[98],5.000000000000000e+001);

tmcAssign(b,reg[98]);
//statement here,line 30

// % Lines 31--31:
//Len =x;



tmcAssign(Len,x);
//statement here,line 31

// % Lines 32--32:
//e = logspace( -5, -2,Len);

tmcScalar(reg[102],5.000000000000000e+000);
tmcNeg(reg[103],reg[102]);
tmcScalar(reg[104],2.000000000000000e+000);
tmcNeg(reg[105],reg[104]);

//CALL function
tmcReallocRegister(reg[107]);
tmclogspace(1,3, reg[107], reg[103], reg[105], Len);

tmcAssign(e,reg[107]);
//statement here,line 32

// % Lines 33--33:
//e = fliplr(e);


//CALL function
tmcReallocRegister(reg[110]);
tmcfliplr(1,1, reg[110], e);

tmcAssign(e,reg[110]);
//statement here,line 33

// % Lines 34--34:
//y = zeros(1,Len);

tmcScalar(reg[112],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[114]);
tmczeros(1,2, reg[114], reg[112], Len);

tmcAssign(y,reg[114]);
//statement here,line 34

// % Lines 35--35:
//x=y;



tmcAssign(x,y);
//statement here,line 35

// % Lines 36--36:
//z=y;



tmcAssign(z,y);
//statement here,line 36

// % Lines 37--38:
//for k=1:length(e)

//    ep1  = e(k);

tmcScalar(reg[120],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[122]);
tmclength(1,1, reg[122], e);
tmcCreateColonBaseLimit(reg[123],reg[120],reg[122]);
tmcForIterInit(reg[124],reg[123],k);
label_4: ; //FOR begin
if(tmcForIterNext(reg[124],reg[123])) goto label_3; // exit for


tmcGetByIndex(reg[127],e,1,k);

tmcAssign(ep1,reg[127]);
//statement here,line 38

// % Lines 39--39:
//    S=solvemyeq(a,b,ep1);




//CALL function
tmcReallocRegister(reg[132]);
tmcsolvemyeq(1,3, reg[132], a, b, ep1);

tmcAssign(S,reg[132]);
//statement here,line 39

// % Lines 40--41:
//    if ~isempty(S)

//        y(k) = S.y0; x(k) = S.x0;


//CALL function
tmcReallocRegister(reg[135]);
tmcisempty(1,1, reg[135], S);
tmcNot(reg[136],reg[135]);
if(tmcIsFalse(reg[136])) goto label_6; // goto to the end of the clause if the expression is false

tmcGetByFieldHcode(reg[139],S,0x0ed70000);/* y0 */


tmcGetRefByIndex(pRefHelper,y,1,k);
tmcAssign(pRefHelper,reg[139]);
//statement here,line 41


tmcGetByFieldHcode(reg[144],S,0x0eb80000);/* x0 */


tmcGetRefByIndex(pRefHelper,x,1,k);
tmcAssign(pRefHelper,reg[144]);
//statement here,line 41

// % Lines 42--42:
//        z(k) = ite;




tmcGetRefByIndex(pRefHelper,z,1,k);
tmcAssign(pRefHelper,ite);
//statement here,line 42

// % Lines 43--43:
//    end

goto label_5; //branch to end IF
label_6: ; //end IF clause
label_5: ; //end IF
//statement here,line 43

// % Lines 44--44:
//end

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 44

// % Lines 45--45:
//save('res.mat','y','x','z');

tmcCreateString(reg[150],"res.mat");
//CALL function save
tmcsave(0,4, reg[150], y, "y", x, "x", z, "z");
//statement here,line 45

// % Lines 46--49:
//%fp=fopen('res.txt');

//%fprintf(fp,'done Ok');

//%fclose(fp);

//return;

goto label_1; //branch to FUNCTION exit
//statement here,line 49

// % Lines 50--51:
//

//figure(10);

tmcScalar(reg[151],1.000000000000000e+001);
//CALL function
tmcReallocRegister(reg[152]);
tmcfigure(0,1, reg[152], reg[151]);
//statement here,line 51

// % Lines 52--52:
//subplot(3,1,1);

tmcScalar(reg[153],3.000000000000000e+000);
tmcScalar(reg[154],1.000000000000000e+000);
tmcScalar(reg[155],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[156]);
tmcsubplot(0,3, reg[156], reg[153], reg[154], reg[155]);
//statement here,line 52

// % Lines 53--53:
//plot(e,y,'b');grid on;



tmcCreateString(reg[159],"b");
//CALL function
tmcReallocRegister(reg[160]);
tmcplot(0,3, reg[160], e, y, reg[159]);
//statement here,line 53

tmcCreateString(reg[161],"on");
//CALL function
tmcReallocRegister(reg[162]);
tmcgrid(0,1, reg[162], reg[161]);
//statement here,line 53

// % Lines 54--54:
//subplot(3,1,2);

tmcScalar(reg[163],3.000000000000000e+000);
tmcScalar(reg[164],1.000000000000000e+000);
tmcScalar(reg[165],2.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[166]);
tmcsubplot(0,3, reg[166], reg[163], reg[164], reg[165]);
//statement here,line 54

// % Lines 55--55:
//plot(e,x,'r');grid on;



tmcCreateString(reg[169],"r");
//CALL function
tmcReallocRegister(reg[170]);
tmcplot(0,3, reg[170], e, x, reg[169]);
//statement here,line 55

tmcCreateString(reg[171],"on");
//CALL function
tmcReallocRegister(reg[172]);
tmcgrid(0,1, reg[172], reg[171]);
//statement here,line 55

// % Lines 56--56:
//subplot(3,1,3);

tmcScalar(reg[173],3.000000000000000e+000);
tmcScalar(reg[174],1.000000000000000e+000);
tmcScalar(reg[175],3.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[176]);
tmcsubplot(0,3, reg[176], reg[173], reg[174], reg[175]);
//statement here,line 56

// % Lines 57--57:
//plot(e,z,'g');grid on;



tmcCreateString(reg[179],"g");
//CALL function
tmcReallocRegister(reg[180]);
tmcplot(0,3, reg[180], e, z, reg[179]);
//statement here,line 57

tmcCreateString(reg[181],"on");
//CALL function
tmcReallocRegister(reg[182]);
tmcgrid(0,1, reg[182], reg[181]);
//statement here,line 57

// % Lines 58--59:
//

//disp('done');

tmcCreateString(reg[183],"done");
//CALL function
tmcReallocRegister(reg[184]);
tmcdisp(0,1, reg[184], reg[183]);
//statement here,line 59

// % Lines 60--61:
//

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(ep1);
tmcFreeLocalVar(k);
tmcFreeLocalVar(z);
tmcFreeLocalVar(e);
tmcFreeLocalVar(Len);
tmcFreeLocalVar(b);
tmcFreeLocalVar(a);
tmcFreeLocalVar(K);
tmcFreeLocalVar(S);
tmcFreeLocalVar(Ib);
tmcFreeLocalVar(AL);
tmcFreeLocalVar(MG);
tmcFreeLocalVar(x);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(15);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 61

// % Lines 62--62:
