//File: TestO.c 
//Generated by TMC Converter(C)2009-2013
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--6:
//function [F,Mag,Ph]=TestO(f1,d1,f2,d2, NumFreqs,Fmin,Fmax,Nint)

//% [F,Mag,Ph]=TestO(1000,0.07,1500,0.7, 100,0.2,100000,0)

//% Calculate 2nd-order filter frequency responce 

//

//if NumFreqs <2 || f1<= 0 || f2 <=0 

//    F=0; Mag=0; Ph=0;

void  tmcTestO(int nargout, int nargin,tmsMatrix *F,tmsMatrix *Mag,tmsMatrix *Ph
,tmsMatrix *f1,tmsMatrix *d1,tmsMatrix *f2,tmsMatrix *d2,tmsMatrix *NumFreqs,tmsMatrix *Fmin__input__tmc,tmsMatrix *Fmax__input__tmc,tmsMatrix *Nint__input__tmc) {
tmsMatrix **reg=tmcCreateRegFrame(105);
tmsMatrix *Fmin=tmcNewMatrix();
tmsMatrix *Fmax=tmcNewMatrix();
tmsMatrix *Nint=tmcNewMatrix();
tmsMatrix *w1=tmcNewMatrix();
tmsMatrix *w2=tmcNewMatrix();
tmsMatrix *w=tmcNewMatrix();
tmsMatrix *num=tmcNewMatrix();
tmsMatrix *den=tmcNewMatrix();
tmsMatrix *Mag2=tmcNewMatrix();
tmsMatrix *Ph2=tmcNewMatrix();
tmsMatrix *num2=tmcNewMatrix();
tmsMatrix *den2=tmcNewMatrix();

tmcCopyMat(Fmin,Fmin__input__tmc);
tmcCopyMat(Fmax,Fmax__input__tmc);
tmcCopyMat(Nint,Nint__input__tmc);
TRY
TMC_DBG_PUSH_STACK_VAR("TestO",23,
f1,"f1",
d1,"d1",
f2,"f2",
d2,"d2",
NumFreqs,"NumFreqs",
Fmin__input__tmc,"Fmin__input__tmc",
Fmax__input__tmc,"Fmax__input__tmc",
Nint__input__tmc,"Nint__input__tmc",
F,"F",
Mag,"Mag",
Ph,"Ph",
Fmin,"Fmin",
Fmax,"Fmax",
Nint,"Nint",
w1,"w1",
w2,"w2",
w,"w",
num,"num",
den,"den",
Mag2,"Mag2",
Ph2,"Ph2",
num2,"num2",
den2,"den2");


tmcScalar(reg[4],2.000000000000000e+000);
tmcLt(reg[5],NumFreqs,reg[4]);
if(tmcIsTrue(reg[5])) {
	tmcAssignTrue(reg[2]); goto label_5;} // return(true) boolean_or expr

tmcScalar(reg[7],0.000000000000000e+000);
tmcLe(reg[8],f1,reg[7]);
tmcAssignBool(reg[2],reg[8]);
label_5: ; //end boolean expr
if(tmcIsTrue(reg[2])) {
	tmcAssignTrue(reg[1]); goto label_4;} // return(true) boolean_or expr

tmcScalar(reg[10],0.000000000000000e+000);
tmcLe(reg[11],f2,reg[10]);
tmcAssignBool(reg[1],reg[11]);
label_4: ; //end boolean expr
if(tmcIsFalse(reg[1])) goto label_3; // goto to the end of the clause if the expression is false
tmcScalar(reg[12],0.000000000000000e+000);

tmcAssign(F,reg[12]);
//statement here,line 6

tmcScalar(reg[14],0.000000000000000e+000);

tmcAssign(Mag,reg[14]);
//statement here,line 6

tmcScalar(reg[16],0.000000000000000e+000);

tmcAssign(Ph,reg[16]);
//statement here,line 6

// % Lines 7--7:
//    return;

goto label_1; //branch to FUNCTION exit
//statement here,line 7

// % Lines 8--8:
//end

goto label_2; //branch to end IF
label_3: ; //end IF clause
label_2: ; //end IF
//statement here,line 8

// % Lines 9--10:
//if nargin <6

//Fmin = min(f1,f2)*0.2;

//CALL function
tmcReallocRegister(reg[18]);
tmcnargin(1,0, reg[18]);
tmcScalar(reg[19],6.000000000000000e+000);
tmcLt(reg[20],reg[18],reg[19]);
if(tmcIsFalse(reg[20])) goto label_7; // goto to the end of the clause if the expression is false


//CALL function
tmcReallocRegister(reg[23]);
tmcReallocRegister(reg[24]);
tmcmin(1,2, reg[23], reg[24], f1, f2,NULL);
tmcScalar(reg[25],2.000000000000000e-001);
tmcMul(reg[26],reg[23],reg[25]);

tmcAssign(Fmin,reg[26]);
//statement here,line 10

// % Lines 11--11:
//Fmax = max(f1,f2)/0.2;



//CALL function
tmcReallocRegister(reg[30]);
tmcReallocRegister(reg[31]);
tmcmax(1,2, reg[30], reg[31], f1, f2,NULL);
tmcScalar(reg[32],2.000000000000000e-001);
tmcDiv(reg[33],reg[30],reg[32]);

tmcAssign(Fmax,reg[33]);
//statement here,line 11

// % Lines 12--12:
//end

goto label_6; //branch to end IF
label_7: ; //end IF clause
label_6: ; //end IF
//statement here,line 12

// % Lines 13--14:
//if (nargin <8)

//    Nint=0;

//CALL function
tmcReallocRegister(reg[35]);
tmcnargin(1,0, reg[35]);
tmcScalar(reg[36],8.000000000000000e+000);
tmcLt(reg[37],reg[35],reg[36]);
if(tmcIsFalse(reg[37])) goto label_9; // goto to the end of the clause if the expression is false
tmcScalar(reg[38],0.000000000000000e+000);

tmcAssign(Nint,reg[38]);
//statement here,line 14

// % Lines 15--15:
//end

goto label_8; //branch to end IF
label_9: ; //end IF clause
label_8: ; //end IF
//statement here,line 15

// % Lines 16--17:
//

//F = logspace( log10(Fmin),log10(Fmax), NumFreqs ); 


//CALL function
tmcReallocRegister(reg[41]);
tmclog10(1,1, reg[41], Fmin);

//CALL function
tmcReallocRegister(reg[43]);
tmclog10(1,1, reg[43], Fmax);

//CALL function
tmcReallocRegister(reg[45]);
tmclogspace(1,3, reg[45], reg[41], reg[43], NumFreqs);

tmcAssign(F,reg[45]);
//statement here,line 17

// % Lines 18--18:
//w1 = f1*2*pi; w2 = f2*2*pi;


tmcScalar(reg[48],2.000000000000000e+000);
tmcMul(reg[49],f1,reg[48]);
//CALL function
tmcReallocRegister(reg[50]);
tmcpi(1,0, reg[50]);
tmcMul(reg[51],reg[49],reg[50]);

tmcAssign(w1,reg[51]);
//statement here,line 18


tmcScalar(reg[54],2.000000000000000e+000);
tmcMul(reg[55],f2,reg[54]);
//CALL function
tmcReallocRegister(reg[56]);
tmcpi(1,0, reg[56]);
tmcMul(reg[57],reg[55],reg[56]);

tmcAssign(w2,reg[57]);
//statement here,line 18

// % Lines 19--19:
//w = F * 2*pi;


tmcScalar(reg[60],2.000000000000000e+000);
tmcMul(reg[61],F,reg[60]);
//CALL function
tmcReallocRegister(reg[62]);
tmcpi(1,0, reg[62]);
tmcMul(reg[63],reg[61],reg[62]);

tmcAssign(w,reg[63]);
//statement here,line 19

// % Lines 20--20:
//[Mag,Ph,num,den]=resp2nd(w1,d1,w2,d2,w);






//CALL function
tmcReallocRegister(reg[70]);
tmcReallocRegister(reg[71]);
tmcReallocRegister(reg[72]);
tmcReallocRegister(reg[73]);
tmcresp2nd(4,5, reg[70], reg[71], reg[72], reg[73], w1, d1, w2, d2, w);

tmcAssign(Mag,reg[70]);

tmcAssign(Ph,reg[71]);

tmcAssign(num,reg[72]);

tmcAssign(den,reg[73]);
//statement here,line 20

// % Lines 21--21:
//[Mag2,Ph2,num2,den2]=respint(Nint,w);



//CALL function
tmcReallocRegister(reg[80]);
tmcReallocRegister(reg[81]);
tmcReallocRegister(reg[82]);
tmcReallocRegister(reg[83]);
tmcrespint(4,2, reg[80], reg[81], reg[82], reg[83], Nint, w);

tmcAssign(Mag2,reg[80]);

tmcAssign(Ph2,reg[81]);

tmcAssign(num2,reg[82]);

tmcAssign(den2,reg[83]);
//statement here,line 21

// % Lines 22--22:
//Mag = Mag+Mag2;



tmcAdd(reg[90],Mag,Mag2);

tmcAssign(Mag,reg[90]);
//statement here,line 22

// % Lines 23--23:
//Ph  = Ph + Ph2;



tmcAdd(reg[94],Ph,Ph2);

tmcAssign(Ph,reg[94]);
//statement here,line 23

// % Lines 24--24:
//num=conv(num,num2);



//CALL function
tmcReallocRegister(reg[98]);
tmcconv(1,2, reg[98], num, num2);

tmcAssign(num,reg[98]);
//statement here,line 24

// % Lines 25--25:
//den=conv(den,den2);



//CALL function
tmcReallocRegister(reg[102]);
tmcconv(1,2, reg[102], den, den2);

tmcAssign(den,reg[102]);
//statement here,line 25

// % Lines 26--26:
//save('result.mat','Mag','Ph','num','den','w1','w2','d1','d2','w','NumFreqs','Fmin','Fmax','F');

tmcCreateString(reg[104],"result.mat");
//CALL function save
tmcsave(0,14, reg[104], Mag, "Mag", Ph, "Ph", num, "num", den, "den", w1, "w1", w2, "w2", d1, "d1", d2, "d2",
 w, "w", NumFreqs, "NumFreqs", Fmin, "Fmin", Fmax, "Fmax", F, "F");
//statement here,line 26

// % Lines 27--38:
//

//% figure(10);

//% subplot(2,1,1);

//% plot(F, Mag,'b');

//% subplot(2,1,2);

//% plot(F, Ph,'b');

//

//

//

//

//

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(den2);
tmcFreeLocalVar(num2);
tmcFreeLocalVar(Ph2);
tmcFreeLocalVar(Mag2);
tmcFreeLocalVar(den);
tmcFreeLocalVar(num);
tmcFreeLocalVar(w);
tmcFreeLocalVar(w2);
tmcFreeLocalVar(w1);
tmcFreeLocalVar(Nint);
tmcFreeLocalVar(Fmax);
tmcFreeLocalVar(Fmin);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(23);

ENDFINALLY
}

//FUNCTION DEFINITION BEGIN
//statement here,line 38

// % Lines 39--39:
