//File: findcompensator.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--4:
//function [PlantModel,Ctrl] = findcompensator(PlantModel)

//%PlantModel = struct('R',pars(1),'L',pars(2),'Ts',pars(3),'Delay',pars(4));

//

//[PlantModel] = getfrdRL(PlantModel);

void tmcfindcompensator(int nargout, int nargin,tmsMatrix *PlantModel,tmsMatrix *Ctrl
,tmsMatrix *PlantModel__input__tmc) {
tmsMatrix **reg=tmcCreateRegFrame(324);
tmsMatrix *kp=tmcNewMatrix();
tmsMatrix *w0=tmcNewMatrix();
tmsMatrix *cnt=tmcNewMatrix();
tmsMatrix *Ts=tmcNewMatrix();
tmsMatrix *d=tmcNewMatrix();
tmsMatrix *R=tmcNewMatrix();
tmsMatrix *L=tmcNewMatrix();
tmsMatrix *Fmax=tmcNewMatrix();
tmsMatrix *p1=tmcNewMatrix();
tmsMatrix *kd1=tmcNewMatrix();
tmsMatrix *nkd=tmcNewMatrix();
tmsMatrix *nkp=tmcNewMatrix();
tmsMatrix *w2=tmcNewMatrix();
tmsMatrix *kd=tmcNewMatrix();
tmsMatrix *ze=tmcNewMatrix();
tmsMatrix *w=tmcNewMatrix();
tmsMatrix *s=tmcNewMatrix();
tmsMatrix *z=tmcNewMatrix();
tmsMatrix *b=tmcNewMatrix();
tmsMatrix *numz=tmcNewMatrix();
tmsMatrix *denz=tmcNewMatrix();
tmsMatrix *M=tmcNewMatrix();
tmsMatrix *M2=tmcNewMatrix();
tmsMatrix *b2=tmcNewMatrix();
tmsMatrix *numzPw=tmcNewMatrix();
tmsMatrix *denzPw=tmcNewMatrix();
tmsMatrix *gg=tmcNewMatrix();
tmsMatrix *cnt1=tmcNewMatrix();
tmsMatrix *cnt2=tmcNewMatrix();
tmsMatrix *KD=tmcNewMatrix();
tmsMatrix *KP=tmcNewMatrix();
tmsMatrix *C_numz=tmcNewMatrix();
tmsMatrix *C_denz=tmcNewMatrix();
tmsMatrix *O_numz=tmcNewMatrix();
tmsMatrix *O_denz=tmcNewMatrix();
tmsMatrix *CL_numz=tmcNewMatrix();
tmsMatrix *CL_denz=tmcNewMatrix();
tmsMatrix *CL_TFz=tmcNewMatrix();
tmsMatrix *OL_TFz=tmcNewMatrix();
tmsMatrix *I_cross=tmcNewMatrix();
tmsMatrix *Ctrl1=tmcNewMatrix();
tmsMatrix *II=tmcNewMatrix();
tmsMatrix *nC=tmcNewMatrix();
tmsMatrix *nn=tmcNewMatrix();
tmsMatrix *I1=tmcNewMatrix();

tmcCopyMat(PlantModel,PlantModel__input__tmc);
TRY
TMC_DBG_PUSH_STACK_VAR("findcompensator",48,
PlantModel__input__tmc,"PlantModel__input__tmc",
PlantModel,"PlantModel",
Ctrl,"Ctrl",
kp,"kp",
w0,"w0",
cnt,"cnt",
Ts,"Ts",
d,"d",
R,"R",
L,"L",
Fmax,"Fmax",
p1,"p1",
kd1,"kd1",
nkd,"nkd",
nkp,"nkp",
w2,"w2",
kd,"kd",
ze,"ze",
w,"w",
s,"s",
z,"z",
b,"b",
numz,"numz",
denz,"denz",
M,"M",
M2,"M2",
b2,"b2",
numzPw,"numzPw",
denzPw,"denzPw",
gg,"gg",
cnt1,"cnt1",
cnt2,"cnt2",
KD,"KD",
KP,"KP",
C_numz,"C_numz",
C_denz,"C_denz",
O_numz,"O_numz",
O_denz,"O_denz",
CL_numz,"CL_numz",
CL_denz,"CL_denz",
CL_TFz,"CL_TFz",
OL_TFz,"OL_TFz",
I_cross,"I_cross",
Ctrl1,"Ctrl1",
II,"II",
nC,"nC",
nn,"nn",
I1,"I1");


//CALL function
tmcReallocRegister(reg[2]);
tmcgetfrdRL(1,1, reg[2], PlantModel);

tmcAssign(PlantModel,reg[2]);
//statement here,line 4

// % Lines 5--6:
//

//kp  = linspace(100,10000,10);

tmcScalar(reg[4],1.000000000000000e+002);
tmcScalar(reg[5],1.000000000000000e+004);
tmcScalar(reg[6],1.000000000000000e+001);
//CALL function
tmcReallocRegister(reg[7]);
tmclinspace(1,3, reg[7], reg[4], reg[5], reg[6]);

tmcAssign(kp,reg[7]);
//statement here,line 6

// % Lines 7--7:
//w0 = 10000;

tmcScalar(reg[9],1.000000000000000e+004);

tmcAssign(w0,reg[9]);
//statement here,line 7

// % Lines 8--8:
//cnt=0;

tmcScalar(reg[11],0.000000000000000e+000);

tmcAssign(cnt,reg[11]);
//statement here,line 8

// % Lines 9--9:
//Ts = PlantModel.Ts;


tmcGetByFieldHcode(reg[15],PlantModel,0x0a9f0000);/* Ts */

tmcAssign(Ts,reg[15]);
//statement here,line 9

// % Lines 10--10:
//d = PlantModel.Delay;


tmcGetByFieldHcode(reg[19],PlantModel,0xc9630000);/* Delay */

tmcAssign(d,reg[19]);
//statement here,line 10

// % Lines 11--11:
//R=PlantModel.R;


tmcGetByFieldHcode(reg[23],PlantModel,0x00520000);/* R */

tmcAssign(R,reg[23]);
//statement here,line 11

// % Lines 12--12:
//L=PlantModel.L;


tmcGetByFieldHcode(reg[27],PlantModel,0x004c0000);/* L */

tmcAssign(L,reg[27]);
//statement here,line 12

// % Lines 13--13:
//Fmax= 0.499/Ts;

tmcScalar(reg[29],4.990000000000000e-001);

tmcDiv(reg[31],reg[29],Ts);

tmcAssign(Fmax,reg[31]);
//statement here,line 13

// % Lines 14--14:
//p1 = 1./(j*Fmax*2*pi*L+R);

tmcScalar(reg[33],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[34]);
tmcj(1,0, reg[34]);

tmcMul(reg[36],reg[34],Fmax);
tmcScalar(reg[37],2.000000000000000e+000);
tmcMul(reg[38],reg[36],reg[37]);
//CALL function
tmcReallocRegister(reg[39]);
tmcpi(1,0, reg[39]);
tmcMul(reg[40],reg[38],reg[39]);

tmcMul(reg[42],reg[40],L);

tmcAdd(reg[44],reg[42],R);
tmcDivScalar(reg[45],reg[33],reg[44]);

tmcAssign(p1,reg[45]);
//statement here,line 14

// % Lines 15--15:
//kd1 = 1./p1;

tmcScalar(reg[47],1.000000000000000e+000);

tmcDivScalar(reg[49],reg[47],p1);

tmcAssign(kd1,reg[49]);
//statement here,line 15

// % Lines 16--16:
//nkd=100;nkp = 400;

tmcScalar(reg[51],1.000000000000000e+002);

tmcAssign(nkd,reg[51]);
//statement here,line 16

tmcScalar(reg[53],4.000000000000000e+002);

tmcAssign(nkp,reg[53]);
//statement here,line 16

// % Lines 17--17:
//w2 = pi/60/(Ts + d);

//CALL function
tmcReallocRegister(reg[55]);
tmcpi(1,0, reg[55]);
tmcScalar(reg[56],6.000000000000000e+001);
tmcDiv(reg[57],reg[55],reg[56]);


tmcAdd(reg[60],Ts,d);
tmcDiv(reg[61],reg[57],reg[60]);

tmcAssign(w2,reg[61]);
//statement here,line 17

// % Lines 18--19:
//

//kd = linspace(0.1,200 ,nkd ) * kd1;

tmcScalar(reg[63],1.000000000000000e-001);
tmcScalar(reg[64],2.000000000000000e+002);

//CALL function
tmcReallocRegister(reg[66]);
tmclinspace(1,3, reg[66], reg[63], reg[64], nkd);

tmcMul(reg[68],reg[66],kd1);

tmcAssign(kd,reg[68]);
//statement here,line 19

// % Lines 20--20:
//ze  = linspace(0.05*w2,min(20*w2,w0*0.5),nkp)   ;

tmcScalar(reg[70],5.000000000000000e-002);

tmcMul(reg[72],reg[70],w2);
tmcScalar(reg[73],2.000000000000000e+001);

tmcMul(reg[75],reg[73],w2);

tmcScalar(reg[77],5.000000000000000e-001);
tmcMul(reg[78],w0,reg[77]);
//CALL function
tmcReallocRegister(reg[79]);
tmcReallocRegister(reg[80]);
tmcmin(1,2, reg[79], reg[80], reg[75], reg[78],NULL);

//CALL function
tmcReallocRegister(reg[82]);
tmclinspace(1,3, reg[82], reg[72], reg[79], nkp);

tmcAssign(ze,reg[82]);
//statement here,line 20

// % Lines 21--21:
//w = logspace(2, log10(Fmax) ) * 2*pi;

tmcScalar(reg[84],2.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[86]);
tmclog10(1,1, reg[86], Fmax);
//CALL function
tmcReallocRegister(reg[87]);
tmclogspace(1,2, reg[87], reg[84], reg[86],NULL);
tmcScalar(reg[88],2.000000000000000e+000);
tmcMul(reg[89],reg[87],reg[88]);
//CALL function
tmcReallocRegister(reg[90]);
tmcpi(1,0, reg[90]);
tmcMul(reg[91],reg[89],reg[90]);

tmcAssign(w,reg[91]);
//statement here,line 21

// % Lines 22--22:
//s = j*w;

//CALL function
tmcReallocRegister(reg[93]);
tmcj(1,0, reg[93]);

tmcMul(reg[95],reg[93],w);

tmcAssign(s,reg[95]);
//statement here,line 22

// % Lines 23--24:
//

//z = exp(s*Ts);



tmcMul(reg[99],s,Ts);
//CALL function
tmcReallocRegister(reg[100]);
tmcexp(1,1, reg[100], reg[99]);

tmcAssign(z,reg[100]);
//statement here,line 24

// % Lines 25--25:
//b = exp(-R/L*Ts);


tmcNeg(reg[103],R);

tmcDiv(reg[105],reg[103],L);

tmcMul(reg[107],reg[105],Ts);
//CALL function
tmcReallocRegister(reg[108]);
tmcexp(1,1, reg[108], reg[107]);

tmcAssign(b,reg[108]);
//statement here,line 25

// % Lines 26--26:
//numz = [0,1-b   ];

tmcScalar(reg[110],0.000000000000000e+000);
tmcScalar(reg[111],1.000000000000000e+000);

tmcSub(reg[113],reg[111],b);
tmcCollectColumns(reg[114],2,reg[110],reg[113]);
tmcCollectRows(reg[115],1,reg[114]);

tmcAssign(numz,reg[115]);
//statement here,line 26

// % Lines 27--27:
//denz  = [1 ,- b];

tmcScalar(reg[117],1.000000000000000e+000);

tmcNeg(reg[119],b);
tmcCollectColumns(reg[120],2,reg[117],reg[119]);
tmcCollectRows(reg[121],1,reg[120]);

tmcAssign(denz,reg[121]);
//statement here,line 27

// % Lines 28--28:
//M = 1.2;

tmcScalar(reg[123],1.200000000000000e+000);

tmcAssign(M,reg[123]);
//statement here,line 28

// % Lines 29--29:
//M2 = 1.8;

tmcScalar(reg[125],1.800000000000000e+000);

tmcAssign(M2,reg[125]);
//statement here,line 29

// % Lines 30--31:
//

//b2 = exp(-w0*Ts);


tmcNeg(reg[128],w0);

tmcMul(reg[130],reg[128],Ts);
//CALL function
tmcReallocRegister(reg[131]);
tmcexp(1,1, reg[131], reg[130]);

tmcAssign(b2,reg[131]);
//statement here,line 31

// % Lines 32--32:
//numzPw = [0,1-b2   ];

tmcScalar(reg[133],0.000000000000000e+000);
tmcScalar(reg[134],1.000000000000000e+000);

tmcSub(reg[136],reg[134],b2);
tmcCollectColumns(reg[137],2,reg[133],reg[136]);
tmcCollectRows(reg[138],1,reg[137]);

tmcAssign(numzPw,reg[138]);
//statement here,line 32

// % Lines 33--33:
//denzPw  = [1 ,- b2];

tmcScalar(reg[140],1.000000000000000e+000);

tmcNeg(reg[142],b2);
tmcCollectColumns(reg[143],2,reg[140],reg[142]);
tmcCollectRows(reg[144],1,reg[143]);

tmcAssign(denzPw,reg[144]);
//statement here,line 33

// % Lines 34--35:
//

//        numz =conv(numzPw,numz);



//CALL function
tmcReallocRegister(reg[148]);
tmcconv(1,2, reg[148], numzPw, numz);

tmcAssign(numz,reg[148]);
//statement here,line 35

// % Lines 36--36:
//        denz  =conv(denzPw,denz);



//CALL function
tmcReallocRegister(reg[152]);
tmcconv(1,2, reg[152], denzPw, denz);

tmcAssign(denz,reg[152]);
//statement here,line 36

// % Lines 37--37:
//gg=[];

tmcCreateMatrixEmpty(reg[154]);

tmcAssign(gg,reg[154]);
//statement here,line 37

// % Lines 38--39:
//for cnt1=1:nkd

//      waitbar( cnt1/nkd  ,'please wait');

tmcScalar(reg[156],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[158],reg[156],nkd);
tmcForIterInit(reg[159],reg[158],cnt1);
label_4: ; //FOR begin
if(tmcForIterNext(reg[159],reg[158])) goto label_3; // exit for


tmcDiv(reg[162],cnt1,nkd);
tmcCreateString(reg[163],"please wait");
//CALL function
tmcReallocRegister(reg[164]);
tmcwaitbar(0,2, reg[164], reg[162], reg[163],NULL,NULL,NULL,NULL);
//statement here,line 39

// % Lines 40--41:
//    for cnt2=1:nkp

//        KD=kd(cnt1);KP=KD*ze(cnt2);

tmcScalar(reg[165],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[167],reg[165],nkp);
tmcForIterInit(reg[168],reg[167],cnt2);
label_7: ; //FOR begin
if(tmcForIterNext(reg[168],reg[167])) goto label_6; // exit for


tmcGetByIndex(reg[171],kd,1,cnt1);

tmcAssign(KD,reg[171]);
//statement here,line 41




tmcGetByIndex(reg[176],ze,1,cnt2);
tmcMul(reg[177],KD,reg[176]);

tmcAssign(KP,reg[177]);
//statement here,line 41

// % Lines 42--43:
//               

//        C_numz = [ KD, (KP*Ts-KD)  ];




tmcMul(reg[182],KP,Ts);

tmcSub(reg[184],reg[182],KD);
tmcCollectColumns(reg[185],2,KD,reg[184]);
tmcCollectRows(reg[186],1,reg[185]);

tmcAssign(C_numz,reg[186]);
//statement here,line 43

// % Lines 44--44:
//        C_denz  = [1 , -1];

tmcScalar(reg[188],1.000000000000000e+000);
tmcScalar(reg[189],1.000000000000000e+000);
tmcNeg(reg[190],reg[189]);
tmcCollectColumns(reg[191],2,reg[188],reg[190]);
tmcCollectRows(reg[192],1,reg[191]);

tmcAssign(C_denz,reg[192]);
//statement here,line 44

// % Lines 45--47:
//        

//        

//        O_numz = conv(C_numz,numz);



//CALL function
tmcReallocRegister(reg[196]);
tmcconv(1,2, reg[196], C_numz, numz);

tmcAssign(O_numz,reg[196]);
//statement here,line 47

// % Lines 48--48:
//        O_denz  = conv(C_denz,denz);



//CALL function
tmcReallocRegister(reg[200]);
tmcconv(1,2, reg[200], C_denz, denz);

tmcAssign(O_denz,reg[200]);
//statement here,line 48

// % Lines 49--50:
//        

//        CL_numz = O_numz;



tmcAssign(CL_numz,O_numz);
//statement here,line 50

// % Lines 51--51:
//        CL_denz  = O_numz + O_denz;



tmcAdd(reg[206],O_numz,O_denz);

tmcAssign(CL_denz,reg[206]);
//statement here,line 51

// % Lines 52--53:
//        

//        CL_TFz = polyval(CL_numz, z   ) ./ polyval(CL_denz, z   );



//CALL function
tmcReallocRegister(reg[210]);
tmcpolyval(1,2, reg[210], CL_numz, z);


//CALL function
tmcReallocRegister(reg[213]);
tmcpolyval(1,2, reg[213], CL_denz, z);
tmcDivScalar(reg[214],reg[210],reg[213]);

tmcAssign(CL_TFz,reg[214]);
//statement here,line 53

// % Lines 54--54:
//        OL_TFz = polyval(O_numz, z   ) ./ polyval(O_denz, z   );



//CALL function
tmcReallocRegister(reg[218]);
tmcpolyval(1,2, reg[218], O_numz, z);


//CALL function
tmcReallocRegister(reg[221]);
tmcpolyval(1,2, reg[221], O_denz, z);
tmcDivScalar(reg[222],reg[218],reg[221]);

tmcAssign(OL_TFz,reg[222]);
//statement here,line 54

// % Lines 55--55:
//        I_cross = find( abs(OL_TFz) < 1  );


//CALL function
tmcReallocRegister(reg[225]);
tmcabs(1,1, reg[225], OL_TFz);
tmcScalar(reg[226],1.000000000000000e+000);
tmcLt(reg[227],reg[225],reg[226]);
//CALL function
tmcReallocRegister(reg[228]);
tmcReallocRegister(reg[229]);
tmcReallocRegister(reg[230]);
tmcfind(1,1, reg[228], reg[229], reg[230], reg[227],NULL,NULL);

tmcAssign(I_cross,reg[228]);
//statement here,line 55

// % Lines 56--58:
//

//         if  (max(abs(CL_TFz)) < M)  &&  (~isempty(I_cross)) && (max(abs(1./(1+OL_TFz))) < M2)

//          cnt=cnt+1;


//CALL function
tmcReallocRegister(reg[235]);
tmcabs(1,1, reg[235], CL_TFz);
//CALL function
tmcReallocRegister(reg[236]);
tmcReallocRegister(reg[237]);
tmcmax(1,1, reg[236], reg[237], reg[235],NULL,NULL);

tmcLt(reg[239],reg[236],M);
if(tmcIsFalse(reg[239])) {
	tmcAssignFalse(reg[233]); goto label_11; } // return(false) boolean_and expr

//CALL function
tmcReallocRegister(reg[241]);
tmcisempty(1,1, reg[241], I_cross);
tmcNot(reg[242],reg[241]);
tmcAssignBool(reg[233],reg[242]);
label_11: ; //end boolean expr
if(tmcIsFalse(reg[233])) {
	tmcAssignFalse(reg[232]); goto label_10; } // return(false) boolean_and expr
tmcScalar(reg[243],1.000000000000000e+000);
tmcScalar(reg[244],1.000000000000000e+000);

tmcAdd(reg[246],reg[244],OL_TFz);
tmcDivScalar(reg[247],reg[243],reg[246]);
//CALL function
tmcReallocRegister(reg[248]);
tmcabs(1,1, reg[248], reg[247]);
//CALL function
tmcReallocRegister(reg[249]);
tmcReallocRegister(reg[250]);
tmcmax(1,1, reg[249], reg[250], reg[248],NULL,NULL);

tmcLt(reg[252],reg[249],M2);
tmcAssignBool(reg[232],reg[252]);
label_10: ; //end boolean expr
if(tmcIsFalse(reg[232])) goto label_9; // goto to the end of the clause if the expression is false

tmcScalar(reg[254],1.000000000000000e+000);
tmcAdd(reg[255],cnt,reg[254]);

tmcAssign(cnt,reg[255]);
//statement here,line 58

// % Lines 59--59:
//          Ctrl1{cnt}.KI=KP;




tmcGetRefByIndexCell(pRefHelper,Ctrl1,1,cnt);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x095e0000);/* KI */
tmcAssign(pRefHelper,KP);
//statement here,line 59

// % Lines 60--60:
//          Ctrl1{cnt}.KP=KD;




tmcGetRefByIndexCell(pRefHelper,Ctrl1,1,cnt);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x09650000);/* KP */
tmcAssign(pRefHelper,KD);
//statement here,line 60

// % Lines 61--61:
//          Ctrl1{cnt}.w=w0;




tmcGetRefByIndexCell(pRefHelper,Ctrl1,1,cnt);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x00770000);/* w */
tmcAssign(pRefHelper,w0);
//statement here,line 61

// % Lines 62--62:
//          gg=[gg, w(I_cross(1))];




tmcScalar(reg[272],1.000000000000000e+000);
tmcGetByIndex(reg[273],I_cross,1,reg[272]);
tmcGetByIndex(reg[274],w,1,reg[273]);
tmcCollectColumns(reg[275],2,gg,reg[274]);
tmcCollectRows(reg[276],1,reg[275]);

tmcAssign(gg,reg[276]);
//statement here,line 62

// % Lines 63--66:
//          %figure(10);

//          % plot(    angle(OL_TFz)/pi*180, 20*log10(abs(OL_TFz)),'b'  ); grid on;hold on;

//         

//        end

goto label_8; //branch to end IF
label_9: ; //end IF clause
label_8: ; //end IF
//statement here,line 66

// % Lines 67--68:
//        

//    end

label_5: ; //FOR end
goto label_7; //branch to FOR begin
label_6: ; //FOR exit
//statement here,line 68

// % Lines 69--69:
//end

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 69

// % Lines 70--71:
//

//[gg,II] = sort(gg);


//CALL function
tmcReallocRegister(reg[279]);
tmcReallocRegister(reg[280]);
tmcsort(2,1, reg[279], reg[280], gg,NULL);

tmcAssign(gg,reg[279]);

tmcAssign(II,reg[280]);
//statement here,line 71

// % Lines 72--73:
//% gg = fliplr(gg);

//II=fliplr(II);


//CALL function
tmcReallocRegister(reg[284]);
tmcfliplr(1,1, reg[284], II);

tmcAssign(II,reg[284]);
//statement here,line 73

// % Lines 74--74:
//nC = min(length(Ctrl1),50  );


//CALL function
tmcReallocRegister(reg[287]);
tmclength(1,1, reg[287], Ctrl1);
tmcScalar(reg[288],5.000000000000000e+001);
//CALL function
tmcReallocRegister(reg[289]);
tmcReallocRegister(reg[290]);
tmcmin(1,2, reg[289], reg[290], reg[287], reg[288],NULL);

tmcAssign(nC,reg[289]);
//statement here,line 74

// % Lines 75--77:
//

//for nn=1:nC

//    I1 = II(nn);

tmcScalar(reg[292],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[294],reg[292],nC);
tmcForIterInit(reg[295],reg[294],nn);
label_14: ; //FOR begin
if(tmcForIterNext(reg[295],reg[294])) goto label_13; // exit for


tmcGetByIndex(reg[298],II,1,nn);

tmcAssign(I1,reg[298]);
//statement here,line 77

// % Lines 78--78:
//          Ctrl{nn}.KI=Ctrl1{I1}.KI;



tmcGetByIndexCell(reg[302],Ctrl1,1,I1);
tmcGetByFieldHcode(reg[304],reg[302],0x095e0000);/* KI */


tmcGetRefByIndexCell(pRefHelper,Ctrl,1,nn);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x095e0000);/* KI */
tmcAssign(pRefHelper,reg[304]);
//statement here,line 78

// % Lines 79--79:
//          Ctrl{nn}.KP=Ctrl1{I1}.KP;



tmcGetByIndexCell(reg[310],Ctrl1,1,I1);
tmcGetByFieldHcode(reg[312],reg[310],0x09650000);/* KP */


tmcGetRefByIndexCell(pRefHelper,Ctrl,1,nn);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x09650000);/* KP */
tmcAssign(pRefHelper,reg[312]);
//statement here,line 79

// % Lines 80--80:
//          Ctrl{nn}.w=Ctrl1{I1}.w;



tmcGetByIndexCell(reg[318],Ctrl1,1,I1);
tmcGetByFieldHcode(reg[320],reg[318],0x00770000);/* w */


tmcGetRefByIndexCell(pRefHelper,Ctrl,1,nn);
tmcGetRefByFieldHcode(pRefHelper,pRefHelper,0x00770000);/* w */
tmcAssign(pRefHelper,reg[320]);
//statement here,line 80

// % Lines 81--81:
//end
label_12: ; //FOR end
goto label_14; //branch to FOR begin
label_13: ; //FOR exit
//statement here,line 81

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(I1);
tmcFreeLocalVar(nn);
tmcFreeLocalVar(nC);
tmcFreeLocalVar(II);
tmcFreeLocalVar(Ctrl1);
tmcFreeLocalVar(I_cross);
tmcFreeLocalVar(OL_TFz);
tmcFreeLocalVar(CL_TFz);
tmcFreeLocalVar(CL_denz);
tmcFreeLocalVar(CL_numz);
tmcFreeLocalVar(O_denz);
tmcFreeLocalVar(O_numz);
tmcFreeLocalVar(C_denz);
tmcFreeLocalVar(C_numz);
tmcFreeLocalVar(KP);
tmcFreeLocalVar(KD);
tmcFreeLocalVar(cnt2);
tmcFreeLocalVar(cnt1);
tmcFreeLocalVar(gg);
tmcFreeLocalVar(denzPw);
tmcFreeLocalVar(numzPw);
tmcFreeLocalVar(b2);
tmcFreeLocalVar(M2);
tmcFreeLocalVar(M);
tmcFreeLocalVar(denz);
tmcFreeLocalVar(numz);
tmcFreeLocalVar(b);
tmcFreeLocalVar(z);
tmcFreeLocalVar(s);
tmcFreeLocalVar(w);
tmcFreeLocalVar(ze);
tmcFreeLocalVar(kd);
tmcFreeLocalVar(w2);
tmcFreeLocalVar(nkp);
tmcFreeLocalVar(nkd);
tmcFreeLocalVar(kd1);
tmcFreeLocalVar(p1);
tmcFreeLocalVar(Fmax);
tmcFreeLocalVar(L);
tmcFreeLocalVar(R);
tmcFreeLocalVar(d);
tmcFreeLocalVar(Ts);
tmcFreeLocalVar(cnt);
tmcFreeLocalVar(w0);
tmcFreeLocalVar(kp);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(48);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 81

// % Lines 82--82:
