//File: backsub.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--6:
//function x = backsub(A,b)

//%

//% assume A is an upper triangular matrix

//% backsub performs backward substitution to solve Ax=b

//%

//   n = size(A,1);

void tmcbacksub(int nargout, int nargin,tmsMatrix *x
,tmsMatrix *A__input__tmc,tmsMatrix *b) {
tmsMatrix **reg=tmcCreateRegFrame(82);
tmsMatrix *A=tmcNewMatrix();
tmsMatrix *n=tmcNewMatrix();
tmsMatrix *s=tmcNewMatrix();
tmsMatrix *k=tmcNewMatrix();

tmcCopyMat(A,A__input__tmc);
TRY
TMC_DBG_PUSH_STACK_VAR("backsub",7,
A__input__tmc,"A__input__tmc",
b,"b",
x,"x",
A,"A",
n,"n",
s,"s",
k,"k");


tmcScalar(reg[2],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[3]);
tmcsize(1,2, reg[3], A, reg[2]);

tmcAssign(n,reg[3]);
//statement here,line 6

// % Lines 7--7:
//   s = max(abs(diag(A)))*1.0d-16;


//CALL function
tmcReallocRegister(reg[6]);
tmcdiag(1,1, reg[6], A);
//CALL function
tmcReallocRegister(reg[7]);
tmcabs(1,1, reg[7], reg[6]);
//CALL function
tmcReallocRegister(reg[8]);
tmcReallocRegister(reg[9]);
tmcmax(1,1, reg[8], reg[9], reg[7],NULL,NULL);
tmcScalar(reg[10],1.000000000000000e-016);
tmcMul(reg[11],reg[8],reg[10]);

tmcAssign(s,reg[11]);
//statement here,line 7

// % Lines 8--8:
//   x = zeros(n,1);


tmcScalar(reg[14],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[15]);
tmczeros(1,2, reg[15], n, reg[14]);

tmcAssign(x,reg[15]);
//statement here,line 8

// % Lines 9--9:
//   if A(n,n) == 0, A(n,n) = s; end;




tmcGetByIndex(reg[20],A,2,n,n);
tmcScalar(reg[21],0.000000000000000e+000);
tmcEq(reg[22],reg[20],reg[21]);
if(tmcIsFalse(reg[22])) goto label_3; // goto to the end of the clause if the expression is false




tmcGetRefByIndex(pRefHelper,A,2,n,n);
tmcAssign(pRefHelper,s);
//statement here,line 9

goto label_2; //branch to end IF
label_3: ; //end IF clause
label_2: ; //end IF
//statement here,line 9

// % Lines 10--10:
//   x(n) = b(n)/A(n,n);



tmcGetByIndex(reg[29],b,1,n);



tmcGetByIndex(reg[33],A,2,n,n);
tmcDiv(reg[34],reg[29],reg[33]);


tmcGetRefByIndex(pRefHelper,x,1,n);
tmcAssign(pRefHelper,reg[34]);
//statement here,line 10

// % Lines 11--12:
//   for k = (n-1):-1:1

//       if A(k,k) == 0, A(k,k) = s; end;


tmcScalar(reg[38],1.000000000000000e+000);
tmcSub(reg[39],n,reg[38]);
tmcScalar(reg[40],1.000000000000000e+000);
tmcScalar(reg[41],1.000000000000000e+000);
tmcNeg(reg[42],reg[41]);
tmcCreateColonBaseIncLimit(reg[43],reg[39],reg[42],reg[40]);
tmcForIterInit(reg[44],reg[43],k);
label_6: ; //FOR begin
if(tmcForIterNext(reg[44],reg[43])) goto label_5; // exit for



tmcGetByIndex(reg[48],A,2,k,k);
tmcScalar(reg[49],0.000000000000000e+000);
tmcEq(reg[50],reg[48],reg[49]);
if(tmcIsFalse(reg[50])) goto label_8; // goto to the end of the clause if the expression is false




tmcGetRefByIndex(pRefHelper,A,2,k,k);
tmcAssign(pRefHelper,s);
//statement here,line 12

goto label_7; //branch to end IF
label_8: ; //end IF clause
label_7: ; //end IF
//statement here,line 12

// % Lines 13--13:
//       x(k) = (b(k) - A(k,k+1:n)*x(k+1:n))/A(k,k);



tmcGetByIndex(reg[57],b,1,k);



tmcScalar(reg[61],1.000000000000000e+000);
tmcAdd(reg[62],k,reg[61]);

tmcCreateColonBaseLimit(reg[64],reg[62],n);
tmcGetByIndex(reg[65],A,2,k,reg[64]);


tmcScalar(reg[68],1.000000000000000e+000);
tmcAdd(reg[69],k,reg[68]);

tmcCreateColonBaseLimit(reg[71],reg[69],n);
tmcGetByIndex(reg[72],x,1,reg[71]);
tmcMul(reg[73],reg[65],reg[72]);
tmcSub(reg[74],reg[57],reg[73]);



tmcGetByIndex(reg[78],A,2,k,k);
tmcDiv(reg[79],reg[74],reg[78]);


tmcGetRefByIndex(pRefHelper,x,1,k);
tmcAssign(pRefHelper,reg[79]);
//statement here,line 13

// % Lines 14--14:
//   end;

label_4: ; //FOR end
goto label_6; //branch to FOR begin
label_5: ; //FOR exit
//statement here,line 14

// % Lines 15--15:
label_1: ; //end Function
FINALLY
tmcFreeLocalVar(k);
tmcFreeLocalVar(s);
tmcFreeLocalVar(n);
tmcFreeLocalVar(A);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(7);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 15

// % Lines 16--16:
