//File: scalsq.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--13:
//

//function x = scalsq(A,b,w)

//%

//%  Solving the scaled least squares problem 

//%          W(Ax - b) = 0

//%      with iterative refinement. 

//%

//%  input  A --- the matrix

//%         b --- the right-hand side vector

//%         w --- the scaling vector (diagonal entries of W)

//%

//%      

//   [m,n] = size(A);

void tmcscalsq(int nargout, int nargin,tmsMatrix *x
,tmsMatrix *A__input__tmc,tmsMatrix *b__input__tmc,tmsMatrix *w__input__tmc) {
tmsMatrix **reg=tmcCreateRegFrame(164);
tmsMatrix *A=tmcNewMatrix();
tmsMatrix *b=tmcNewMatrix();
tmsMatrix *w=tmcNewMatrix();
tmsMatrix *m=tmcNewMatrix();
tmsMatrix *n=tmcNewMatrix();
tmsMatrix *j_=tmcNewMatrix();
tmsMatrix *Q=tmcNewMatrix();
tmsMatrix *R=tmcNewMatrix();
tmsMatrix *d=tmcNewMatrix();
tmsMatrix *S=tmcNewMatrix();
tmsMatrix *bb=tmcNewMatrix();
tmsMatrix *B=tmcNewMatrix();
tmsMatrix *r=tmcNewMatrix();
tmsMatrix *rr=tmcNewMatrix();
tmsMatrix *s=tmcNewMatrix();
tmsMatrix *c=tmcNewMatrix();
tmsMatrix *c2=tmcNewMatrix();
tmsMatrix *c1=tmcNewMatrix();

tmcCopyMat(A,A__input__tmc);
tmcCopyMat(b,b__input__tmc);
tmcCopyMat(w,w__input__tmc);
TRY
TMC_DBG_PUSH_STACK_VAR("scalsq",22,
A__input__tmc,"A__input__tmc",
b__input__tmc,"b__input__tmc",
w__input__tmc,"w__input__tmc",
x,"x",
A,"A",
b,"b",
w,"w",
m,"m",
n,"n",
j_,"j_",
Q,"Q",
R,"R",
d,"d",
S,"S",
bb,"bb",
B,"B",
r,"r",
rr,"rr",
s,"s",
c,"c",
c2,"c2",
c1,"c1");


//CALL function
tmcReallocRegister(reg[2]);
tmcReallocRegister(reg[3]);
tmcsize(2,1, reg[2], reg[3], A,NULL);

tmcAssign(m,reg[2]);

tmcAssign(n,reg[3]);
//statement here,line 13

// % Lines 14--16:
//   

//   if nargin == 2

//       w = ones(m,1);

//CALL function
tmcReallocRegister(reg[6]);
tmcnargin(1,0, reg[6]);
tmcScalar(reg[7],2.000000000000000e+000);
tmcEq(reg[8],reg[6],reg[7]);
if(tmcIsFalse(reg[8])) goto label_3; // goto to the end of the clause if the expression is false

tmcScalar(reg[10],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[11]);
tmcones(1,2, reg[11], m, reg[10]);

tmcAssign(w,reg[11]);
//statement here,line 16

// % Lines 17--18:
//       for j_ = 1:m

//           if abs(b(j_)) > 1, w(j_) = 1/abs(b(j_)); end;

tmcScalar(reg[13],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[15],reg[13],m);
tmcForIterInit(reg[16],reg[15],j_);
label_6: ; //FOR begin
if(tmcForIterNext(reg[16],reg[15])) goto label_5; // exit for


tmcGetByIndex(reg[19],b,1,j_);
//CALL function
tmcReallocRegister(reg[20]);
tmcabs(1,1, reg[20], reg[19]);
tmcScalar(reg[21],1.000000000000000e+000);
tmcGt(reg[22],reg[20],reg[21]);
if(tmcIsFalse(reg[22])) goto label_8; // goto to the end of the clause if the expression is false
tmcScalar(reg[23],1.000000000000000e+000);


tmcGetByIndex(reg[26],b,1,j_);
//CALL function
tmcReallocRegister(reg[27]);
tmcabs(1,1, reg[27], reg[26]);
tmcDiv(reg[28],reg[23],reg[27]);


tmcGetRefByIndex(pRefHelper,w,1,j_);
tmcAssign(pRefHelper,reg[28]);
//statement here,line 18

goto label_7; //branch to end IF
label_8: ; //end IF clause
label_7: ; //end IF
//statement here,line 18

// % Lines 19--19:
//       end

label_4: ; //FOR end
goto label_6; //branch to FOR begin
label_5: ; //FOR exit
//statement here,line 19

// % Lines 20--20:
//   end;

goto label_2; //branch to end IF
label_3: ; //end IF clause
label_2: ; //end IF
//statement here,line 20

// % Lines 21--23:
//   

//   for j_ = 1:m

//       A(j_,:) = A(j_,:)*w(j_);

tmcScalar(reg[31],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[33],reg[31],m);
tmcForIterInit(reg[34],reg[33],j_);
label_11: ; //FOR begin
if(tmcForIterNext(reg[34],reg[33])) goto label_10; // exit for


tmcCreateMagicColon(reg[37]);
tmcGetByIndex(reg[38],A,2,j_,reg[37]);


tmcGetByIndex(reg[41],w,1,j_);
tmcMul(reg[42],reg[38],reg[41]);


tmcCreateMagicColon(reg[45]);
tmcGetRefByIndex(pRefHelper,A,2,j_,reg[45]);
tmcAssign(pRefHelper,reg[42]);
//statement here,line 23

// % Lines 24--24:
//   end;

label_9: ; //FOR end
goto label_11; //branch to FOR begin
label_10: ; //FOR exit
//statement here,line 24

// % Lines 25--25:
//   b = b.*w;



tmcMulScalar(reg[48],b,w);

tmcAssign(b,reg[48]);
//statement here,line 25

// % Lines 26--27:
//   

//   [Q,R] = qr(A);


//CALL function
tmcReallocRegister(reg[51]);
tmcReallocRegister(reg[52]);
tmcReallocRegister(reg[53]);
tmcqr(2,1, reg[51], reg[52], reg[53], A,NULL);

tmcAssign(Q,reg[51]);

tmcAssign(R,reg[52]);
//statement here,line 27

// % Lines 28--29:
//

//   d = Q'*b;  S = R(1:n,1:n);


tmcTranspose(reg[57],Q);

tmcMul(reg[59],reg[57],b);

tmcAssign(d,reg[59]);
//statement here,line 29


tmcScalar(reg[62],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[64],reg[62],n);
tmcScalar(reg[65],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[67],reg[65],n);
tmcGetByIndex(reg[68],R,2,reg[64],reg[67]);

tmcAssign(S,reg[68]);
//statement here,line 29

// % Lines 30--30:
//   x = backsub(S,d(1:n));



tmcScalar(reg[72],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[74],reg[72],n);
tmcGetByIndex(reg[75],d,1,reg[74]);
//CALL function
tmcReallocRegister(reg[76]);
tmcbacksub(1,2, reg[76], S, reg[75]);

tmcAssign(x,reg[76]);
//statement here,line 30

// % Lines 31--33:
//   

//   % one step refinement

//   bb = [b;zeros(n,1)]; B = [eye(m),A;A',zeros(n,n)];


tmcCollectColumns(reg[79],1,b);

tmcScalar(reg[81],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[82]);
tmczeros(1,2, reg[82], n, reg[81]);
tmcCollectColumns(reg[83],1,reg[82]);
tmcCollectRows(reg[84],2,reg[79],reg[83]);

tmcAssign(bb,reg[84]);
//statement here,line 33


//CALL function
tmcReallocRegister(reg[87]);
tmceye(1,1, reg[87], m,NULL);

tmcCollectColumns(reg[89],2,reg[87],A);

tmcTranspose(reg[91],A);


//CALL function
tmcReallocRegister(reg[94]);
tmczeros(1,2, reg[94], n, n);
tmcCollectColumns(reg[95],2,reg[91],reg[94]);
tmcCollectRows(reg[96],2,reg[89],reg[95]);

tmcAssign(B,reg[96]);
//statement here,line 33

// % Lines 34--34:
//   r = b - A*x;




tmcMul(reg[101],A,x);
tmcSub(reg[102],b,reg[101]);

tmcAssign(r,reg[102]);
//statement here,line 34

// % Lines 35--37:
//   

//   %for j_ = 1:3

//   rr = bb - B*[r;x]; %disp(norm(rr));




tmcCollectColumns(reg[107],1,r);

tmcCollectColumns(reg[109],1,x);
tmcCollectRows(reg[110],2,reg[107],reg[109]);
tmcMul(reg[111],B,reg[110]);
tmcSub(reg[112],bb,reg[111]);

tmcAssign(rr,reg[112]);
//statement here,line 37

// % Lines 38--39:
//   

//   s = Q'*rr(1:m);


tmcTranspose(reg[115],Q);

tmcScalar(reg[117],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[119],reg[117],m);
tmcGetByIndex(reg[120],rr,1,reg[119]);
tmcMul(reg[121],reg[115],reg[120]);

tmcAssign(s,reg[121]);
//statement here,line 39

// % Lines 40--40:
//   c = forsub(S',rr(m+1:m+n));


tmcTranspose(reg[124],S);


tmcScalar(reg[127],1.000000000000000e+000);
tmcAdd(reg[128],m,reg[127]);


tmcAdd(reg[131],m,n);
tmcCreateColonBaseLimit(reg[132],reg[128],reg[131]);
tmcGetByIndex(reg[133],rr,1,reg[132]);
//CALL function
tmcReallocRegister(reg[134]);
tmcforsub(1,2, reg[134], reg[124], reg[133]);

tmcAssign(c,reg[134]);
//statement here,line 40

// % Lines 41--41:
//   c2 = backsub(S,s(1:n)-c);



tmcScalar(reg[138],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[140],reg[138],n);
tmcGetByIndex(reg[141],s,1,reg[140]);

tmcSub(reg[143],reg[141],c);
//CALL function
tmcReallocRegister(reg[144]);
tmcbacksub(1,2, reg[144], S, reg[143]);

tmcAssign(c2,reg[144]);
//statement here,line 41

// % Lines 42--42:
//   c1 = Q*[c;s(n+1:m)];



tmcCollectColumns(reg[148],1,c);


tmcScalar(reg[151],1.000000000000000e+000);
tmcAdd(reg[152],n,reg[151]);

tmcCreateColonBaseLimit(reg[154],reg[152],m);
tmcGetByIndex(reg[155],s,1,reg[154]);
tmcCollectColumns(reg[156],1,reg[155]);
tmcCollectRows(reg[157],2,reg[148],reg[156]);
tmcMul(reg[158],Q,reg[157]);

tmcAssign(c1,reg[158]);
//statement here,line 42

// % Lines 43--44:
//   %r = r + c1;

//   x = x + c2;



tmcAdd(reg[162],x,c2);

tmcAssign(x,reg[162]);
//statement here,line 44

// % Lines 45--46:
//   %end;

//   
label_1: ; //end Function
FINALLY
tmcFreeLocalVar(c1);
tmcFreeLocalVar(c2);
tmcFreeLocalVar(c);
tmcFreeLocalVar(s);
tmcFreeLocalVar(rr);
tmcFreeLocalVar(r);
tmcFreeLocalVar(B);
tmcFreeLocalVar(bb);
tmcFreeLocalVar(S);
tmcFreeLocalVar(d);
tmcFreeLocalVar(R);
tmcFreeLocalVar(Q);
tmcFreeLocalVar(j_);
tmcFreeLocalVar(n);
tmcFreeLocalVar(m);
tmcFreeLocalVar(w);
tmcFreeLocalVar(b);
tmcFreeLocalVar(A);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(22);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 46

// % Lines 47--47:
