//File: sylmat.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--7:
//

//function A = sylmat(g,u,v)

//%

//%  sylmat generates the Sylvester resultant matrix

//%    of polynomial g, u, v

//%

//   mg = length(g)-1; 

void tmcsylmat(int nargout, int nargin,tmsMatrix *A
,tmsMatrix *g,tmsMatrix *u,tmsMatrix *v) {
tmsMatrix **reg=tmcCreateRegFrame(100);
tmsMatrix *mg=tmcNewMatrix();
tmsMatrix *mu=tmcNewMatrix();
tmsMatrix *mv=tmcNewMatrix();
tmsMatrix *np=tmcNewMatrix();
tmsMatrix *nq=tmcNewMatrix();
tmsMatrix *m=tmcNewMatrix();
tmsMatrix *n=tmcNewMatrix();
tmsMatrix *j_=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("sylmat",12,
g,"g",
u,"u",
v,"v",
A,"A",
mg,"mg",
mu,"mu",
mv,"mv",
np,"np",
nq,"nq",
m,"m",
n,"n",
j_,"j_");


//CALL function
tmcReallocRegister(reg[2]);
tmclength(1,1, reg[2], g);
tmcScalar(reg[3],1.000000000000000e+000);
tmcSub(reg[4],reg[2],reg[3]);

tmcAssign(mg,reg[4]);
//statement here,line 7

// % Lines 8--8:
//   mu = length(u)-1; 


//CALL function
tmcReallocRegister(reg[7]);
tmclength(1,1, reg[7], u);
tmcScalar(reg[8],1.000000000000000e+000);
tmcSub(reg[9],reg[7],reg[8]);

tmcAssign(mu,reg[9]);
//statement here,line 8

// % Lines 9--9:
//   mv = length(v)-1; 


//CALL function
tmcReallocRegister(reg[12]);
tmclength(1,1, reg[12], v);
tmcScalar(reg[13],1.000000000000000e+000);
tmcSub(reg[14],reg[12],reg[13]);

tmcAssign(mv,reg[14]);
//statement here,line 9

// % Lines 10--10:
//   np = mg + mu;



tmcAdd(reg[18],mg,mu);

tmcAssign(np,reg[18]);
//statement here,line 10

// % Lines 11--11:
//   nq = mg + mv;



tmcAdd(reg[22],mg,mv);

tmcAssign(nq,reg[22]);
//statement here,line 11

// % Lines 12--13:
//   

//   m = mg + mu + mv;



tmcAdd(reg[26],mg,mu);

tmcAdd(reg[28],reg[26],mv);

tmcAssign(m,reg[28]);
//statement here,line 13

// % Lines 14--14:
//   n = np + nq;



tmcAdd(reg[32],np,nq);

tmcAssign(n,reg[32]);
//statement here,line 14

// % Lines 15--16:
//      

//   A = zeros(n, m);  



//CALL function
tmcReallocRegister(reg[36]);
tmczeros(1,2, reg[36], n, m);

tmcAssign(A,reg[36]);
//statement here,line 16

// % Lines 17--19:
//   

//   for j_ = 1:mg

//       A(j_:j_+mu,j_) = u';

tmcScalar(reg[38],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[40],reg[38],mg);
tmcForIterInit(reg[41],reg[40],j_);
label_4: ; //FOR begin
if(tmcForIterNext(reg[41],reg[40])) goto label_3; // exit for

tmcTranspose(reg[43],u);




tmcAdd(reg[48],j_,mu);
tmcCreateColonBaseLimit(reg[49],j_,reg[48]);

tmcGetRefByIndex(pRefHelper,A,2,reg[49],j_);
tmcAssign(pRefHelper,reg[43]);
//statement here,line 19

// % Lines 20--20:
//       A(np+j_:np+j_+mv,j_) = v';


tmcTranspose(reg[52],v);



tmcAdd(reg[56],np,j_);


tmcAdd(reg[59],np,j_);

tmcAdd(reg[61],reg[59],mv);
tmcCreateColonBaseLimit(reg[62],reg[56],reg[61]);

tmcGetRefByIndex(pRefHelper,A,2,reg[62],j_);
tmcAssign(pRefHelper,reg[52]);
//statement here,line 20

// % Lines 21--21:
//   end;

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 21

// % Lines 22--24:
//   

//   for j_ = 1:mu

//       A(j_:j_+mg,j_+mg) = g';

tmcScalar(reg[64],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[66],reg[64],mu);
tmcForIterInit(reg[67],reg[66],j_);
label_7: ; //FOR begin
if(tmcForIterNext(reg[67],reg[66])) goto label_6; // exit for

tmcTranspose(reg[69],g);




tmcAdd(reg[74],j_,mg);
tmcCreateColonBaseLimit(reg[75],j_,reg[74]);


tmcAdd(reg[78],j_,mg);
tmcGetRefByIndex(pRefHelper,A,2,reg[75],reg[78]);
tmcAssign(pRefHelper,reg[69]);
//statement here,line 24

// % Lines 25--25:
//   end;

label_5: ; //FOR end
goto label_7; //branch to FOR begin
label_6: ; //FOR exit
//statement here,line 25

// % Lines 26--28:
//   

//   for j_ = 1:mv

//       A(np+j_:np+j_+mg, j_+mg+mu) = g';

tmcScalar(reg[79],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[81],reg[79],mv);
tmcForIterInit(reg[82],reg[81],j_);
label_10: ; //FOR begin
if(tmcForIterNext(reg[82],reg[81])) goto label_9; // exit for

tmcTranspose(reg[84],g);



tmcAdd(reg[88],np,j_);


tmcAdd(reg[91],np,j_);

tmcAdd(reg[93],reg[91],mg);
tmcCreateColonBaseLimit(reg[94],reg[88],reg[93]);


tmcAdd(reg[97],j_,mg);

tmcAdd(reg[99],reg[97],mu);
tmcGetRefByIndex(pRefHelper,A,2,reg[94],reg[99]);
tmcAssign(pRefHelper,reg[84]);
//statement here,line 28

// % Lines 29--29:
//   end
label_8: ; //FOR end
goto label_10; //branch to FOR begin
label_9: ; //FOR exit
//statement here,line 29

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(j_);
tmcFreeLocalVar(n);
tmcFreeLocalVar(m);
tmcFreeLocalVar(nq);
tmcFreeLocalVar(np);
tmcFreeLocalVar(mv);
tmcFreeLocalVar(mu);
tmcFreeLocalVar(mg);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(12);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 29

// % Lines 30--30:
