//File: sylves.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--5:
//function A = sylves(f,g,k)

//%

//%  The k-th sylvester matrix of f(x), f'(x) = g(x)

//%

//   l = length(f);

void tmcsylves(int nargout, int nargin,tmsMatrix *A
,tmsMatrix *f,tmsMatrix *g,tmsMatrix *k) {
tmsMatrix **reg=tmcCreateRegFrame(56);
tmsMatrix *l=tmcNewMatrix();
tmsMatrix *m=tmcNewMatrix();
tmsMatrix *n=tmcNewMatrix();
tmsMatrix *j_=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("sylves",8,
f,"f",
g,"g",
k,"k",
A,"A",
l,"l",
m,"m",
n,"n",
j_,"j_");


//CALL function
tmcReallocRegister(reg[2]);
tmclength(1,1, reg[2], f);

tmcAssign(l,reg[2]);
//statement here,line 5

// % Lines 6--6:
//   m = l+k-1;



tmcAdd(reg[6],l,k);
tmcScalar(reg[7],1.000000000000000e+000);
tmcSub(reg[8],reg[6],reg[7]);

tmcAssign(m,reg[8]);
//statement here,line 6

// % Lines 7--7:
//   n = 2*k+1;

tmcScalar(reg[10],2.000000000000000e+000);

tmcMul(reg[12],reg[10],k);
tmcScalar(reg[13],1.000000000000000e+000);
tmcAdd(reg[14],reg[12],reg[13]);

tmcAssign(n,reg[14]);
//statement here,line 7

// % Lines 8--8:
//   A = zeros(m,n);



//CALL function
tmcReallocRegister(reg[18]);
tmczeros(1,2, reg[18], m, n);

tmcAssign(A,reg[18]);
//statement here,line 8

// % Lines 9--10:
//   for j_ = 1:k+1;

//       A(j_:j_+l-2,j_) = g';

tmcScalar(reg[20],1.000000000000000e+000);

tmcScalar(reg[22],1.000000000000000e+000);
tmcAdd(reg[23],k,reg[22]);
tmcCreateColonBaseLimit(reg[24],reg[20],reg[23]);
tmcForIterInit(reg[25],reg[24],j_);
label_4: ; //FOR begin
if(tmcForIterNext(reg[25],reg[24])) goto label_3; // exit for

tmcTranspose(reg[27],g);




tmcAdd(reg[32],j_,l);
tmcScalar(reg[33],2.000000000000000e+000);
tmcSub(reg[34],reg[32],reg[33]);
tmcCreateColonBaseLimit(reg[35],j_,reg[34]);

tmcGetRefByIndex(pRefHelper,A,2,reg[35],j_);
tmcAssign(pRefHelper,reg[27]);
//statement here,line 10

// % Lines 11--11:
//   end;

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 11

// % Lines 12--13:
//   for j_ = 1:k

//       A(j_:j_+l-1,j_+k+1) = f';

tmcScalar(reg[37],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[39],reg[37],k);
tmcForIterInit(reg[40],reg[39],j_);
label_7: ; //FOR begin
if(tmcForIterNext(reg[40],reg[39])) goto label_6; // exit for

tmcTranspose(reg[42],f);




tmcAdd(reg[47],j_,l);
tmcScalar(reg[48],1.000000000000000e+000);
tmcSub(reg[49],reg[47],reg[48]);
tmcCreateColonBaseLimit(reg[50],j_,reg[49]);


tmcAdd(reg[53],j_,k);
tmcScalar(reg[54],1.000000000000000e+000);
tmcAdd(reg[55],reg[53],reg[54]);
tmcGetRefByIndex(pRefHelper,A,2,reg[50],reg[55]);
tmcAssign(pRefHelper,reg[42]);
//statement here,line 13

// % Lines 14--14:
//   end;

label_5: ; //FOR end
goto label_7; //branch to FOR begin
label_6: ; //FOR exit
//statement here,line 14

// % Lines 15--16:
//

//   
label_1: ; //end Function
FINALLY
tmcFreeLocalVar(j_);
tmcFreeLocalVar(n);
tmcFreeLocalVar(m);
tmcFreeLocalVar(l);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(8);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 16

// % Lines 17--17:
