//File: TestO.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--32:
//function y=TestO(x) 

//% This example uses MultRoot by ZHONGGANG ZENG

//% References:

//% [1] ZHONGGANG ZENG, "COMPUTING MULTIPLE ROOTS OF INEXACT POLYNOMIALS",

//% MATHEMATICS OF COMPUTATION,

//% Volume 74, Number 250, Pages 869-903

//% S 0025-5718(04)01692-8

//% Article electronically published on July 22, 2004

//% [2] ZHONGGANG ZENG, "MultRoot - A Matlab package computing polynomial roots and multiplicities"

//% Journal ACM Transactions on Mathematical Software (TOMS), Volume 30 Issue 2, June 2004 , Pages 218-236

//

//%e = [1,2,3];

//%y = e(imag(e)>0);

//%disp(y);

//%return;

//

//% www=load('D:\Data_D\HSKOST\TMC\qd_tmc\tmc_src-1.02\examples\AppEx_qd\testroot1.mat')

//%figure(222);plot( real(www.xx),imag(www.xx),'r.',real(www.qxx),imag(www.qxx),'bo',real(roots(www.aa)),imag(roots(www.aa)),'gx');grid on;

//% www=load('HH.mat');

//% A=www.HH;

//% B=www.B;

//% disp(det(A));

//% disp(det_qd(A));

//% disp(eig(A));

//% disp(eig_qd(A));

//%disp(A\B);

//%  disp(leftdivide_qd(A,B));

//% return

//

//

//

//ar = 0.00001;

void tmcTestO(int nargout, int nargin,tmsMatrix *y
,tmsMatrix *x) {
tmsMatrix **reg=tmcCreateRegFrame(256);
tmsMatrix *ar=tmcNewMatrix();
tmsMatrix *ai=tmcNewMatrix();
tmsMatrix *x0=tmcNewMatrix();
tmsMatrix *x1=tmcNewMatrix();
tmsMatrix *va=tmcNewMatrix();
tmsMatrix *vb=tmcNewMatrix();
tmsMatrix *vb2=tmcNewMatrix();
tmsMatrix *vb4=tmcNewMatrix();
tmsMatrix *vb8=tmcNewMatrix();
tmsMatrix *vb9=tmcNewMatrix();
tmsMatrix *vb9r=tmcNewMatrix();
tmsMatrix *aa=tmcNewMatrix();
tmsMatrix *xx=tmcNewMatrix();
tmsMatrix *qxx=tmcNewMatrix();
tmsMatrix *cnt=tmcNewMatrix();
tmsMatrix *yy=tmcNewMatrix();
tmsMatrix *err_xx=tmcNewMatrix();
tmsMatrix *qyy=tmcNewMatrix();
tmsMatrix *y1=tmcNewMatrix();
tmsMatrix *y2=tmcNewMatrix();
tmsMatrix *err_qxx=tmcNewMatrix();
tmsMatrix *mqq=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("TestO",24,
x,"x",
y,"y",
ar,"ar",
ai,"ai",
x0,"x0",
x1,"x1",
va,"va",
vb,"vb",
vb2,"vb2",
vb4,"vb4",
vb8,"vb8",
vb9,"vb9",
vb9r,"vb9r",
aa,"aa",
xx,"xx",
qxx,"qxx",
cnt,"cnt",
yy,"yy",
err_xx,"err_xx",
qyy,"qyy",
y1,"y1",
y2,"y2",
err_qxx,"err_qxx",
mqq,"mqq");

tmcScalar(reg[1],1.000000000000000e-005);

tmcAssign(ar,reg[1]);
//statement here,line 32

// % Lines 33--33:
//ai  = 10;

tmcScalar(reg[3],1.000000000000000e+001);

tmcAssign(ai,reg[3]);
//statement here,line 33

// % Lines 34--35:
//

//x0 = ar + ai*j;



//CALL function
tmcReallocRegister(reg[7]);
tmcj(1,0, reg[7]);
tmcMul(reg[8],ai,reg[7]);
tmcAdd(reg[9],ar,reg[8]);

tmcAssign(x0,reg[9]);
//statement here,line 35

// % Lines 36--36:
//x1 = ar - ai*j;



//CALL function
tmcReallocRegister(reg[13]);
tmcj(1,0, reg[13]);
tmcMul(reg[14],ai,reg[13]);
tmcSub(reg[15],ar,reg[14]);

tmcAssign(x1,reg[15]);
//statement here,line 36

// % Lines 37--38:
//

//va = [1, -2*ar,ar^2+ai^2];

tmcScalar(reg[17],1.000000000000000e+000);
tmcScalar(reg[18],2.000000000000000e+000);
tmcNeg(reg[19],reg[18]);

tmcMul(reg[21],reg[19],ar);

tmcScalar(reg[23],2.000000000000000e+000);
tmcPower(reg[24],ar,reg[23]);

tmcScalar(reg[26],2.000000000000000e+000);
tmcPower(reg[27],ai,reg[26]);
tmcAdd(reg[28],reg[24],reg[27]);
tmcCollectColumns(reg[29],3,reg[17],reg[21],reg[28]);
tmcCollectRows(reg[30],1,reg[29]);

tmcAssign(va,reg[30]);
//statement here,line 38

// % Lines 39--39:
//vb = va;



tmcAssign(vb,va);
//statement here,line 39

// % Lines 40--40:
//vb2 = conv_qd(va,va);



//CALL function
tmcReallocRegister(reg[36]);
tmcconv_qd(1,2, reg[36], va, va);

tmcAssign(vb2,reg[36]);
//statement here,line 40

// % Lines 41--41:
//vb4 = conv_qd(vb2,vb2);



//CALL function
tmcReallocRegister(reg[40]);
tmcconv_qd(1,2, reg[40], vb2, vb2);

tmcAssign(vb4,reg[40]);
//statement here,line 41

// % Lines 42--42:
//vb8 = conv_qd(vb4,vb4);



//CALL function
tmcReallocRegister(reg[44]);
tmcconv_qd(1,2, reg[44], vb4, vb4);

tmcAssign(vb8,reg[44]);
//statement here,line 42

// % Lines 43--43:
//vb9 = conv_qd(vb8,va);



//CALL function
tmcReallocRegister(reg[48]);
tmcconv_qd(1,2, reg[48], vb8, va);

tmcAssign(vb9,reg[48]);
//statement here,line 43

// % Lines 44--44:
//vb9r = real(vb9);


//CALL function
tmcReallocRegister(reg[51]);
tmcreal(1,1, reg[51], vb9);

tmcAssign(vb9r,reg[51]);
//statement here,line 44

// % Lines 45--46:
//

//vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[55]);
tmcconv_qd(1,2, reg[55], vb, va);

tmcAssign(vb,reg[55]);
//statement here,line 46

// % Lines 47--47:
//vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[59]);
tmcconv_qd(1,2, reg[59], vb, va);

tmcAssign(vb,reg[59]);
//statement here,line 47

// % Lines 48--48:
//vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[63]);
tmcconv_qd(1,2, reg[63], vb, va);

tmcAssign(vb,reg[63]);
//statement here,line 48

// % Lines 49--49:
// vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[67]);
tmcconv_qd(1,2, reg[67], vb, va);

tmcAssign(vb,reg[67]);
//statement here,line 49

// % Lines 50--50:
// vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[71]);
tmcconv_qd(1,2, reg[71], vb, va);

tmcAssign(vb,reg[71]);
//statement here,line 50

// % Lines 51--51:
// vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[75]);
tmcconv_qd(1,2, reg[75], vb, va);

tmcAssign(vb,reg[75]);
//statement here,line 51

// % Lines 52--52:
// vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[79]);
tmcconv_qd(1,2, reg[79], vb, va);

tmcAssign(vb,reg[79]);
//statement here,line 52

// % Lines 53--53:
// vb = conv_qd(vb,va);



//CALL function
tmcReallocRegister(reg[83]);
tmcconv_qd(1,2, reg[83], vb, va);

tmcAssign(vb,reg[83]);
//statement here,line 53

// % Lines 54--86:
// 

//%   vb = conv(vb,va);

//%  vb = conv(vb,va);

//%  vb = conv(vb,va);

//

//% aa=[1,909,367236,86545284,13111610526,1324272663126,...

//%         89167692650484,3859687267585236,97457103506527209,1093685272684360901];

//

//% aa = [ ...

//% 1,...

//% -0.18e-3, ...

//% 900.000000,...

//% -.1440000000,...

//% 3.60000000e5,...

//% -50.40000000,...

//% 8.400000001e7,...

//% -10080.00000,...

//% 1.260000000e10,...

//% -1.260000000e6,...

//% 1.259999997e12,...

//% -1.00800000e8,...

//% 8.4000000e13,...

//% -5.04000000e9,...

//% 3.600000007e15,...

//% (-1.440000000e11-2e7*i),...

//% 9.00000001e16,...

//% -1.800000000e12,...

//% 1.000000000e18 ...

//% ];

//% 

//% 

//% aa = vb;

//aa = vb9r;



tmcAssign(aa,vb9r);
//statement here,line 86

// % Lines 87--87:
//aa = zeros(1,19);

tmcScalar(reg[87],1.000000000000000e+000);
tmcScalar(reg[88],1.900000000000000e+001);
//CALL function
tmcReallocRegister(reg[89]);
tmczeros(1,2, reg[89], reg[87], reg[88]);

tmcAssign(aa,reg[89]);
//statement here,line 87

// % Lines 88--88:
// aa(1)= 1.00000000000000000000000000000000;      

tmcScalar(reg[91],1.000000000000000e+000);

tmcScalar(reg[93],1.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[93]);
tmcAssign(pRefHelper,reg[91]);
//statement here,line 88

// % Lines 89--89:
// aa(2)=-1.799999954528175294399261474609375E-0004;

tmcScalar(reg[94],1.799999954528175e-004);
tmcNeg(reg[95],reg[94]);

tmcScalar(reg[97],2.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[97]);
tmcAssign(pRefHelper,reg[95]);
//statement here,line 89

// % Lines 90--90:
// aa(3)=  900.000000014399999272450813900107 ;     

tmcScalar(reg[98],9.000000000144000e+002);

tmcScalar(reg[100],3.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[100]);
tmcAssign(pRefHelper,reg[98]);
//statement here,line 90

// % Lines 91--91:
// aa(4)=-0.143999996362926023501012475585038 ;     

tmcScalar(reg[101],1.439999963629260e-001);
tmcNeg(reg[102],reg[101]);

tmcScalar(reg[104],4.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[104]);
tmcAssign(pRefHelper,reg[102]);
//statement here,line 91

// % Lines 92--92:
// aa(5)=  360000.000010079999490735729728038 ;     

tmcScalar(reg[105],3.600000000100800e+005);

tmcScalar(reg[107],5.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[107]);
tmcAssign(pRefHelper,reg[105]);
//statement here,line 92

// % Lines 93--93:
// aa(6)= -50.3999987271921082126226590587843 ;     

tmcScalar(reg[108],5.039999872719211e+001);
tmcNeg(reg[109],reg[108]);

tmcScalar(reg[111],6.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[111]);
tmcAssign(pRefHelper,reg[109]);
//statement here,line 93

// % Lines 94--94:
// aa(7)=  84000000.0030239998472247509180040 ;     

tmcScalar(reg[112],8.400000000302400e+007);

tmcScalar(reg[114],7.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[114]);
tmcAssign(pRefHelper,reg[112]);
//statement here,line 94

// % Lines 95--95:
// aa(8)= -10079.9997454585816409967591802353 ;     

tmcScalar(reg[115],1.007999974545858e+004);
tmcNeg(reg[116],reg[115]);

tmcScalar(reg[118],8.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[118]);
tmcAssign(pRefHelper,reg[116]);
//statement here,line 95

// % Lines 96--96:
// aa(9)=  12600000000.5039999745377944863000 ;     

tmcScalar(reg[119],1.260000000050400e+010);

tmcScalar(reg[121],9.000000000000000e+000);
tmcGetRefByIndex(pRefHelper,aa,1,reg[121]);
tmcAssign(pRefHelper,reg[119]);
//statement here,line 96

// % Lines 97--97:
// aa(10)= -1259999.96818316270506093837654926  ;    

tmcScalar(reg[122],1.259999968183163e+006);
tmcNeg(reg[123],reg[122]);

tmcScalar(reg[125],1.000000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[125]);
tmcAssign(pRefHelper,reg[123]);
//statement here,line 97

// % Lines 98--98:
// aa(11)=  1260000000050.39999745377944863000  ;    

tmcScalar(reg[126],1.260000000050400e+012);

tmcScalar(reg[128],1.100000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[128]);
tmcAssign(pRefHelper,reg[126]);
//statement here,line 98

// % Lines 99--99:
// aa(12)= -100799997.454585816409967591802353 ;     

tmcScalar(reg[129],1.007999974545858e+008);
tmcNeg(reg[130],reg[129]);

tmcScalar(reg[132],1.200000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[132]);
tmcAssign(pRefHelper,reg[130]);
//statement here,line 99

// % Lines 100--100:
// aa(13)=  84000000003023.9998472247509180040  ;    

tmcScalar(reg[133],8.400000000302400e+013);

tmcScalar(reg[135],1.300000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[135]);
tmcAssign(pRefHelper,reg[133]);
//statement here,line 100

// % Lines 101--101:
// aa(14)= -5039999872.71921082126226590587843  ;    

tmcScalar(reg[136],5.039999872719211e+009);
tmcNeg(reg[137],reg[136]);

tmcScalar(reg[139],1.400000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[139]);
tmcAssign(pRefHelper,reg[137]);
//statement here,line 101

// % Lines 102--102:
// aa(15)=  3600000000100799.99490735729728038 ;     

tmcScalar(reg[140],3.600000000100800e+015);

tmcScalar(reg[142],1.500000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[142]);
tmcAssign(pRefHelper,reg[140]);
//statement here,line 102

// % Lines 103--103:
// aa(16)= -143999996362.926023501012475585038  ;    

tmcScalar(reg[143],1.439999963629260e+011);
tmcNeg(reg[144],reg[143]);

tmcScalar(reg[146],1.600000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[146]);
tmcAssign(pRefHelper,reg[144]);
//statement here,line 103

// % Lines 104--104:
// aa(17)=  90000000001439999.9272450813900107  ;    

tmcScalar(reg[147],9.000000000144000e+016);

tmcScalar(reg[149],1.700000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[149]);
tmcAssign(pRefHelper,reg[147]);
//statement here,line 104

// % Lines 105--105:
//aa(18)=  -1799999954528.17529439926147460938 ;     

tmcScalar(reg[150],1.799999954528175e+012);
tmcNeg(reg[151],reg[150]);

tmcScalar(reg[153],1.800000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[153]);
tmcAssign(pRefHelper,reg[151]);
//statement here,line 105

// % Lines 106--106:
// aa(19)= 1000000000000000000.000000000000000 ;

tmcScalar(reg[154],1.000000000000000e+018);

tmcScalar(reg[156],1.900000000000000e+001);
tmcGetRefByIndex(pRefHelper,aa,1,reg[156]);
tmcAssign(pRefHelper,reg[154]);
//statement here,line 106

// % Lines 107--109:
//  

//

//xx =  roots( aa);


//CALL function
tmcReallocRegister(reg[158]);
tmcroots(1,1, reg[158], aa);

tmcAssign(xx,reg[158]);
//statement here,line 109

// % Lines 110--110:
//qxx =  roots_qd( aa);


//CALL function
tmcReallocRegister(reg[161]);
tmcroots_qd(1,1, reg[161], aa);

tmcAssign(qxx,reg[161]);
//statement here,line 110

// % Lines 111--112:
//

//disp('Roots=');

tmcCreateString(reg[163],"Roots=");
//CALL function
tmcReallocRegister(reg[164]);
tmcdisp(0,1, reg[164], reg[163]);
//statement here,line 112

// % Lines 113--113:
//disp(xx);


//CALL function
tmcReallocRegister(reg[166]);
tmcdisp(0,1, reg[166], xx);
//statement here,line 113

// % Lines 114--115:
//for cnt=1:length(xx)

//    yy(cnt) = polyval_qd(aa,xx(cnt));    

tmcScalar(reg[167],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[169]);
tmclength(1,1, reg[169], xx);
tmcCreateColonBaseLimit(reg[170],reg[167],reg[169]);
tmcForIterInit(reg[171],reg[170],cnt);
label_4: ; //FOR begin
if(tmcForIterNext(reg[171],reg[170])) goto label_3; // exit for



tmcGetByIndex(reg[175],xx,1,cnt);
//CALL function
tmcReallocRegister(reg[176]);
tmcpolyval_qd(1,2, reg[176], aa, reg[175]);


tmcGetRefByIndex(pRefHelper,yy,1,cnt);
tmcAssign(pRefHelper,reg[176]);
//statement here,line 115

// % Lines 116--116:
//end

label_2: ; //FOR end
goto label_4; //branch to FOR begin
label_3: ; //FOR exit
//statement here,line 116

// % Lines 117--117:
//disp('P(roots)=');

tmcCreateString(reg[179],"P(roots)=");
//CALL function
tmcReallocRegister(reg[180]);
tmcdisp(0,1, reg[180], reg[179]);
//statement here,line 117

// % Lines 118--118:
//disp(yy);


//CALL function
tmcReallocRegister(reg[182]);
tmcdisp(0,1, reg[182], yy);
//statement here,line 118

// % Lines 119--119:
//err_xx = abs(xx-(ar+j*ai));



//CALL function
tmcReallocRegister(reg[185]);
tmcj(1,0, reg[185]);

tmcMul(reg[187],reg[185],ai);
tmcAdd(reg[188],ar,reg[187]);
tmcSub(reg[189],xx,reg[188]);
//CALL function
tmcReallocRegister(reg[190]);
tmcabs(1,1, reg[190], reg[189]);

tmcAssign(err_xx,reg[190]);
//statement here,line 119

// % Lines 120--120:
//disp('error(roots)=');

tmcCreateString(reg[192],"error(roots)=");
//CALL function
tmcReallocRegister(reg[193]);
tmcdisp(0,1, reg[193], reg[192]);
//statement here,line 120

// % Lines 121--121:
//disp(err_xx);


//CALL function
tmcReallocRegister(reg[195]);
tmcdisp(0,1, reg[195], err_xx);
//statement here,line 121

// % Lines 122--124:
//

//

//disp('Quad Roots=');

tmcCreateString(reg[196],"Quad Roots=");
//CALL function
tmcReallocRegister(reg[197]);
tmcdisp(0,1, reg[197], reg[196]);
//statement here,line 124

// % Lines 125--125:
//disp(qxx);


//CALL function
tmcReallocRegister(reg[199]);
tmcdisp(0,1, reg[199], qxx);
//statement here,line 125

// % Lines 126--127:
//for cnt=1:length(qxx)

//    qyy(cnt) = polyval_qd(aa,qxx(cnt));    

tmcScalar(reg[200],1.000000000000000e+000);

//CALL function
tmcReallocRegister(reg[202]);
tmclength(1,1, reg[202], qxx);
tmcCreateColonBaseLimit(reg[203],reg[200],reg[202]);
tmcForIterInit(reg[204],reg[203],cnt);
label_7: ; //FOR begin
if(tmcForIterNext(reg[204],reg[203])) goto label_6; // exit for



tmcGetByIndex(reg[208],qxx,1,cnt);
//CALL function
tmcReallocRegister(reg[209]);
tmcpolyval_qd(1,2, reg[209], aa, reg[208]);


tmcGetRefByIndex(pRefHelper,qyy,1,cnt);
tmcAssign(pRefHelper,reg[209]);
//statement here,line 127

// % Lines 128--128:
//end

label_5: ; //FOR end
goto label_7; //branch to FOR begin
label_6: ; //FOR exit
//statement here,line 128

// % Lines 129--129:
//disp('P(quad roots)=');

tmcCreateString(reg[212],"P(quad roots)=");
//CALL function
tmcReallocRegister(reg[213]);
tmcdisp(0,1, reg[213], reg[212]);
//statement here,line 129

// % Lines 130--130:
//disp(qyy);


//CALL function
tmcReallocRegister(reg[215]);
tmcdisp(0,1, reg[215], qyy);
//statement here,line 130

// % Lines 131--132:
//

//y1 = polyval_qd(aa,x0);



//CALL function
tmcReallocRegister(reg[218]);
tmcpolyval_qd(1,2, reg[218], aa, x0);

tmcAssign(y1,reg[218]);
//statement here,line 132

// % Lines 133--133:
//y2 = polyval_qd(aa,x1);



//CALL function
tmcReallocRegister(reg[222]);
tmcpolyval_qd(1,2, reg[222], aa, x1);

tmcAssign(y2,reg[222]);
//statement here,line 133

// % Lines 134--134:
//disp('P(x0,conj(x0))=');

tmcCreateString(reg[224],"P(x0,conj(x0))=");
//CALL function
tmcReallocRegister(reg[225]);
tmcdisp(0,1, reg[225], reg[224]);
//statement here,line 134

// % Lines 135--135:
//disp([y1,y2]);



tmcCollectColumns(reg[228],2,y1,y2);
tmcCollectRows(reg[229],1,reg[228]);
//CALL function
tmcReallocRegister(reg[230]);
tmcdisp(0,1, reg[230], reg[229]);
//statement here,line 135

// % Lines 136--138:
//

//

//err_qxx = abs(qxx-(ar+j*ai));



//CALL function
tmcReallocRegister(reg[233]);
tmcj(1,0, reg[233]);

tmcMul(reg[235],reg[233],ai);
tmcAdd(reg[236],ar,reg[235]);
tmcSub(reg[237],qxx,reg[236]);
//CALL function
tmcReallocRegister(reg[238]);
tmcabs(1,1, reg[238], reg[237]);

tmcAssign(err_qxx,reg[238]);
//statement here,line 138

// % Lines 139--139:
//disp('error(quad roots)=');

tmcCreateString(reg[240],"error(quad roots)=");
//CALL function
tmcReallocRegister(reg[241]);
tmcdisp(0,1, reg[241], reg[240]);
//statement here,line 139

// % Lines 140--140:
//disp(err_qxx);


//CALL function
tmcReallocRegister(reg[243]);
tmcdisp(0,1, reg[243], err_qxx);
//statement here,line 140

// % Lines 141--148:
//

//%disp('***********************************************');

//%disp('Quad P(roots)=');

//%disp(qyy);

//%qerr = qxx - xx;

//%disp(qerr);

//

//disp('Polynom Coeficcients: aa=');

tmcCreateString(reg[244],"Polynom Coeficcients: aa=");
//CALL function
tmcReallocRegister(reg[245]);
tmcdisp(0,1, reg[245], reg[244]);
//statement here,line 148

// % Lines 149--149:
//disp(aa);


//CALL function
tmcReallocRegister(reg[247]);
tmcdisp(0,1, reg[247], aa);
//statement here,line 149

// % Lines 150--151:
//

//mqq = multroot(aa);


//CALL function
tmcReallocRegister(reg[249]);
tmcmultroot(1,1, reg[249], aa,NULL);

tmcAssign(mqq,reg[249]);
//statement here,line 151

// % Lines 152--152:
//disp('multroots=');

tmcCreateString(reg[251],"multroots=");
//CALL function
tmcReallocRegister(reg[252]);
tmcdisp(0,1, reg[252], reg[251]);
//statement here,line 152

// % Lines 153--153:
//disp(mqq);


//CALL function
tmcReallocRegister(reg[254]);
tmcdisp(0,1, reg[254], mqq);
//statement here,line 153

// % Lines 154--155:
//

//save('testroot1.mat','aa','xx','qxx','yy','qyy','x0','err_xx','err_qxx');

tmcCreateString(reg[255],"testroot1.mat");
//CALL function save
tmcsave(0,9, reg[255], aa, "aa", xx, "xx", qxx, "qxx", yy, "yy", qyy, "qyy", x0, "x0", err_xx, "err_xx", err_qxx, "err_qxx"
);
//statement here,line 155

// % Lines 156--159:
//

//

//

// 
label_1: ; //end Function
FINALLY
tmcFreeLocalVar(mqq);
tmcFreeLocalVar(err_qxx);
tmcFreeLocalVar(y2);
tmcFreeLocalVar(y1);
tmcFreeLocalVar(qyy);
tmcFreeLocalVar(err_xx);
tmcFreeLocalVar(yy);
tmcFreeLocalVar(cnt);
tmcFreeLocalVar(qxx);
tmcFreeLocalVar(xx);
tmcFreeLocalVar(aa);
tmcFreeLocalVar(vb9r);
tmcFreeLocalVar(vb9);
tmcFreeLocalVar(vb8);
tmcFreeLocalVar(vb4);
tmcFreeLocalVar(vb2);
tmcFreeLocalVar(vb);
tmcFreeLocalVar(va);
tmcFreeLocalVar(x1);
tmcFreeLocalVar(x0);
tmcFreeLocalVar(ai);
tmcFreeLocalVar(ar);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(24);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 159

// % Lines 160--160:
