#line 2 "lex.tmcpar_.cpp"

#line 4 "lex.tmcpar_.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer tmcpar__create_buffer
#define yy_delete_buffer tmcpar__delete_buffer
#define yy_flex_debug tmcpar__flex_debug
#define yy_init_buffer tmcpar__init_buffer
#define yy_flush_buffer tmcpar__flush_buffer
#define yy_load_buffer_state tmcpar__load_buffer_state
#define yy_switch_to_buffer tmcpar__switch_to_buffer
#define yyin tmcpar_in
#define yyleng tmcpar_leng
#define yylex tmcpar_lex
#define yylineno tmcpar_lineno
#define yyout tmcpar_out
#define yyrestart tmcpar_restart
#define yytext tmcpar_text
#define yywrap tmcpar_wrap
#define yyalloc tmcpar_alloc
#define yyrealloc tmcpar_realloc
#define yyfree tmcpar_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE tmcpar_restart(tmcpar_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t tmcpar_leng;

extern FILE *tmcpar_in, *tmcpar_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE tmcpar_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-tmcpar_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < tmcpar_leng; ++yyl )\
                    if ( tmcpar_text[yyl] == '\n' )\
                        --tmcpar_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up tmcpar_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up tmcpar_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via tmcpar_restart()), so that the user can continue scanning by
	 * just pointing tmcpar_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when tmcpar_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t tmcpar_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow tmcpar_wrap()'s to do buffer switches
 * instead of setting up a fresh tmcpar_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void tmcpar_restart (FILE *input_file  );
void tmcpar__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE tmcpar__create_buffer (FILE *file,int size  );
void tmcpar__delete_buffer (YY_BUFFER_STATE b  );
void tmcpar__flush_buffer (YY_BUFFER_STATE b  );
void tmcpar_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void tmcpar_pop_buffer_state (void );

static void tmcpar_ensure_buffer_stack (void );
static void tmcpar__load_buffer_state (void );
static void tmcpar__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER tmcpar__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE tmcpar__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE tmcpar__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE tmcpar__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *tmcpar_alloc (yy_size_t  );
void *tmcpar_realloc (void *,yy_size_t  );
void tmcpar_free (void *  );

#define yy_new_buffer tmcpar__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        tmcpar_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            tmcpar__create_buffer(tmcpar_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        tmcpar_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            tmcpar__create_buffer(tmcpar_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *tmcpar_in = (FILE *) 0, *tmcpar_out = (FILE *) 0;

typedef int yy_state_type;

extern int tmcpar_lineno;

int tmcpar_lineno = 1;

extern char *tmcpar_text;
#define yytext_ptr tmcpar_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up tmcpar_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	tmcpar_leng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[162] =
    {   0,
        0,    0,    0,    0,   67,   65,    1,   62,   62,   62,
       63,   34,   27,   50,   51,   31,   28,   56,   29,   60,
       37,    4,    4,   59,   57,   46,   49,   47,   58,   24,
       54,   41,   55,   39,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   52,   35,   53,   48,   26,
        1,    0,   62,   62,   63,   63,   32,    0,   23,   25,
       30,    0,   36,    4,   40,   38,    4,    4,    0,    0,
        3,   43,   44,   42,   24,   24,   24,   24,   24,   24,
       24,   24,   24,    6,   24,   24,   24,   24,   24,   33,
       45,   61,   22,    2,    0,    4,    0,    4,    4,   24,

       24,   24,   24,   24,   21,   15,   24,   24,   24,   24,
       24,   16,   24,    2,    2,    0,    4,   24,   13,   24,
       24,    8,   24,   24,   24,   24,   24,   24,   24,    9,
       17,   24,   24,   24,   24,   24,   24,   24,   24,   11,
       24,    7,   24,   24,   19,   24,    5,   12,   24,   24,
       24,   24,   10,   24,   18,   24,   24,   14,   24,   20,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   26,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   27,   46,
       47,   27,   27,   48,   49,   50,   51,   27,   52,   28,
       53,   27,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    2,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,    1,    1,
        1,    1,    4,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[167] =
    {   0,
        0,    0,  255,  254,  261,  264,   56,   56,   59,   62,
       65,  253,  251,  264,  264,  264,  264,  264,  264,   64,
      264,   82,   69,  264,  264,  236,  235,  234,  264,    0,
      264,  264,  264,  264,  207,   42,   28,   41,  209,  214,
      202,  213,  198,  201,  207,  264,  192,  264,  224,  264,
       75,  237,   98,  110,  113,  264,  264,  236,  235,  264,
      264,  227,  264,  104,  264,  264,  111,  118,  145,    0,
      264,  264,  264,  264,    0,  203,   55,  194,  190,  201,
      189,  190,  188,    0,  193,  183,  190,  178,  188,  264,
      264,  264,  264,  135,  152,  150,  109,  154,   89,  195,

      190,  191,  176,  187,  185,    0,  187,  187,  183,  169,
      169,    0,  173,  147,  264,  156,  160,  165,    0,  160,
      158,  157,  147,  145,  160,  143,  142,  153,  148,    0,
        0,  139,  145,  137,  140,  136,  128,  133,  134,    0,
      114,    0,  122,   98,    0,  101,    0,    0,   96,   73,
       63,   49,    0,   51,    0,   53,   38,    0,   37,    0,
      264,  203,  207,  209,   75,  213
    } ;

static yyconst flex_int16_t yy_def[167] =
    {   0,
      161,    1,    1,    1,  161,  161,  161,  161,  161,  161,
      162,  161,  163,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  164,
      161,  161,  161,  161,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  162,  161,  161,  163,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  165,
      161,  161,  161,  161,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  161,
      161,  161,  161,  166,  161,  161,  161,  161,  165,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  166,  161,  161,  161,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
        0,  161,  161,  161,  161,  161
    } ;

static yyconst flex_int16_t yy_nxt[322] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   30,   30,   30,   31,   32,
       33,   34,    6,   30,   35,   36,   30,   37,   38,   39,
       30,   40,   30,   30,   30,   30,   41,   42,   43,   44,
       30,   45,   30,   46,   47,   48,   49,   51,   53,   53,
       53,   53,   53,   53,   54,   53,   53,   56,   56,   56,
       52,   60,   79,   80,   61,   77,   51,   99,   62,   63,
       64,   64,  160,   67,  159,   68,   68,   81,   78,   52,
      158,   82,  157,   65,   69,   66,   67,  156,   68,   68,

       53,   53,   53,  101,  102,   69,   69,   69,  155,   70,
       71,   71,   53,   53,   53,   56,   56,   56,   69,   69,
       64,   64,  154,   71,   71,   98,   98,   96,   96,   95,
       71,   71,   67,  153,   68,   68,   69,  115,  115,  115,
       95,   95,  152,   69,  151,   71,   71,   69,   69,  115,
      115,  115,   71,   71,   69,   69,   97,  150,   97,   71,
       71,   98,   98,  116,  149,  116,   96,   96,  117,  117,
       98,   98,  117,  117,  148,   69,  117,  117,  147,  146,
      145,  144,  143,  142,  141,  140,   69,   69,  139,  138,
      137,   71,   71,  136,  135,   71,   71,  134,  133,  132,

      131,   71,   71,   55,   55,   55,   55,   58,  130,   58,
       58,   75,   75,  114,  114,  114,  114,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      100,   94,   93,   59,   92,   91,   90,   89,   88,   87,
       86,   85,   84,   83,   76,   74,   73,   72,   59,   57,
      161,   50,   50,    5,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,

      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161
    } ;

static yyconst flex_int16_t yy_chk[322] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,    8,
        8,    9,    9,    9,   10,   10,   10,   11,   11,   11,
        7,   20,   37,   37,   20,   36,   51,  165,   20,   20,
       20,   20,  159,   23,  157,   23,   23,   38,   36,   51,
      156,   38,  154,   20,   23,   20,   22,  152,   22,   22,

       53,   53,   53,   77,   77,   23,   23,   22,  151,   22,
       23,   23,   54,   54,   54,   55,   55,   55,   22,   22,
       64,   64,  150,   22,   22,   97,   97,   67,   67,   64,
       99,   99,   68,  149,   68,   68,   67,   94,   94,   94,
       64,   64,  146,   68,  144,   64,   64,   67,   67,  114,
      114,  114,   67,   67,   68,   68,   69,  143,   69,   68,
       68,   69,   69,   95,  141,   95,   96,   96,   95,   95,
       98,   98,  116,  116,  139,   96,  117,  117,  138,  137,
      136,  135,  134,  133,  132,  129,   96,   96,  128,  127,
      126,   96,   96,  125,  124,   98,   98,  123,  122,  121,

      120,  117,  117,  162,  162,  162,  162,  163,  118,  163,
      163,  164,  164,  166,  166,  166,  166,  113,  111,  110,
      109,  108,  107,  105,  104,  103,  102,  101,  100,   89,
       88,   87,   86,   85,   83,   82,   81,   80,   79,   78,
       76,   62,   59,   58,   52,   49,   47,   45,   44,   43,
       42,   41,   40,   39,   35,   28,   27,   26,   13,   12,
        5,    4,    3,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,

      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[67] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int tmcpar__flex_debug;
int tmcpar__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *tmcpar_text;
#line 1 "TmcParLexer.l"
#line 7 "TmcParLexer.l"
//! Scanner for m-file parser
/******************************************************************************
 * Copyright (c) 2009-2015 by Shmuel Safonov.
 * All rights are reserved.
 * The TMC software is covered under GPL license. Other usage possibilities
 * are also available under commercial license terms. 
  *****************************************************************************/

#include <stdio.h>
#ifndef LINUX_GPL
#include <io.h>
#else
//#define __cdecl 
#endif

#include <string.h>
#include <stdlib.h>

#include <string>
#include <list>

#define YY_NEVER_INTERACTIVE	1

#include "tmcpar_tree.h"
#include "tmcpar_utils.h"

#define MAX_SRC_STRING 10000 // maximal constant string supported
static char* get_string(short bGershaim);
static long ReturnLspToken(long TokVal);
static void dbgPrintLspToken(long TokVal);
void reset_tmcpar_lexer();



void yyunput_elipse_of_element_op(void);

#include "TmcParParser.tab.hpp"

char* alloc_string(long sz)
{
	char *c = (char*)malloc(sizeof(char)*sz);
	return c;
}


char* get_identifier();

// We have 2 states for GERESH treatment:
//  INITIAL:			treated as start of string
//  ExpectQuoteAsCTRANSPOSE:	treated as CTRANSPOSE (follows immediately NUMBER,NUMBER_IM,TRANSPOSE,CTRANSPOSE,],)


#line 673 "lex.tmcpar_.cpp"

#define INITIAL 0
#define ExpectQuoteAsCTRANSPOSE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int tmcpar_lex_destroy (void );

int tmcpar_get_debug (void );

void tmcpar_set_debug (int debug_flag  );

YY_EXTRA_TYPE tmcpar_get_extra (void );

void tmcpar_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *tmcpar_get_in (void );

void tmcpar_set_in  (FILE * in_str  );

FILE *tmcpar_get_out (void );

void tmcpar_set_out  (FILE * out_str  );

yy_size_t tmcpar_get_leng (void );

char *tmcpar_get_text (void );

int tmcpar_get_lineno (void );

void tmcpar_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int tmcpar_wrap (void );
#else
extern int tmcpar_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( tmcpar_text, tmcpar_leng, 1, tmcpar_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( tmcpar_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( tmcpar_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, tmcpar_in))==0 && ferror(tmcpar_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(tmcpar_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int tmcpar_lex (void);

#define YY_DECL int tmcpar_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after tmcpar_text and tmcpar_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 89 "TmcParLexer.l"



#line 860 "lex.tmcpar_.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! tmcpar_in )
			tmcpar_in = stdin;

		if ( ! tmcpar_out )
			tmcpar_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			tmcpar_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				tmcpar__create_buffer(tmcpar_in,YY_BUF_SIZE );
		}

		tmcpar__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of tmcpar_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 162 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 161 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = (yy_more_len); yyl < tmcpar_leng; ++yyl )
				if ( tmcpar_text[yyl] == '\n' )
					   
    tmcpar_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 92 "TmcParLexer.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 94 "TmcParLexer.l"
{
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 97 "TmcParLexer.l"
{BEGIN(ExpectQuoteAsCTRANSPOSE);
	*(tmcpar_text+tmcpar_leng-1) = '\0'; tmcpar_lval.num=atof(tmcpar_text);
	 yyinsert_comma_in_input(NUMBER_IM);
	 yyunput_elipse_of_element_op();
	 return ReturnLspToken( NUMBER_IM);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 104 "TmcParLexer.l"
{BEGIN(ExpectQuoteAsCTRANSPOSE);
  tmcpar_lval.num=atof(tmcpar_text);
	yyinsert_comma_in_input(NUMBER);
	yyunput_elipse_of_element_op();
	return ReturnLspToken( NUMBER);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 110 "TmcParLexer.l"
{ return ReturnLspToken( RETURN);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 111 "TmcParLexer.l"
{ return ReturnLspToken( IF);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 112 "TmcParLexer.l"
{ return ReturnLspToken( ELSEIF);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 113 "TmcParLexer.l"
{ return ReturnLspToken( ELSE);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 114 "TmcParLexer.l"
{ return ReturnLspToken( BREAK);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 115 "TmcParLexer.l"
{ return ReturnLspToken( CONTINUE);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 116 "TmcParLexer.l"
{ return ReturnLspToken( WHILE);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 117 "TmcParLexer.l"
{return ReturnLspToken( SWITCH);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 118 "TmcParLexer.l"
{return ReturnLspToken( CASE);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 119 "TmcParLexer.l"
{return ReturnLspToken( OTHERWISE);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 120 "TmcParLexer.l"
{ return ReturnLspToken( FOR);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 121 "TmcParLexer.l"
{ return ReturnLspToken( TRY);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 122 "TmcParLexer.l"
{ return ReturnLspToken( CATCH);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 123 "TmcParLexer.l"
{ return ReturnLspToken( FUNCTION);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 124 "TmcParLexer.l"
{ return ReturnLspToken( GLOBAL);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 125 "TmcParLexer.l"
{  return ReturnLspToken( END_OF_INPUT); } // HAZARD: added for OCTAVE syntax support
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 126 "TmcParLexer.l"
{
	if (get_indexdeep()>0)
	{
		return ReturnLspToken( MAGIC_END); //like x(end-1)
	}
	else
	{
		 unput(';');return ReturnLspToken( END); //like if .. end
	}
 }
	YY_BREAK
case 22:
*yy_cp = (yy_hold_char); /* undo effects of setting up tmcpar_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up tmcpar_text again */
YY_RULE_SETUP
#line 138 "TmcParLexer.l"
{
							yymore();
							}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 142 "TmcParLexer.l"
{

		register int i, size;
		char* modified;
		const int length = tmcpar_leng-2;
		for (size = 0, i = 1;
		i <= length; size++, i++)
		if (*(tmcpar_text+i) == '\'')
		i++;
		modified = alloc_string(size+1);
		*(modified+size) = '\0';
		for (size = 0, i = 1;
		i <= length; size++, i++)
		{
		*(modified+size) = *(tmcpar_text+i);
		if (*(tmcpar_text+i) == '\'')
		i++;
		}
		tmcpar_lval.str = modified;

	yyinsert_comma_in_input(STRING);

	return ReturnLspToken( STRING);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 167 "TmcParLexer.l"
{
 BEGIN(ExpectQuoteAsCTRANSPOSE);
 get_identifier();
 //tmcpar_lval.str
 yyinsert_comma_in_input(IDENT);
 return ReturnLspToken( IDENT);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 174 "TmcParLexer.l"
{BEGIN(ExpectQuoteAsCTRANSPOSE);
			  tmcpar_lval.int_value = TRANSPOSE; return ReturnLspToken( TRANSPOSE ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 177 "TmcParLexer.l"
{
			tmcpar_lval.int_value = CTRANSPOSE; return ReturnLspToken( CTRANSPOSE );  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 181 "TmcParLexer.l"
{
			 tmcpar_lval.int_value = LEXERROR; return ReturnLspToken( LEXERROR );  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 185 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = PLUS; return ReturnLspToken( PLUS ); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 186 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = MINUS; return ReturnLspToken( MINUS ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 187 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = EMUL; return ReturnLspToken( EMUL ); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 188 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = MUL; return ReturnLspToken( MUL ); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 189 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = BOOL_AND; return ReturnLspToken( BOOL_AND ); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 190 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = BOOL_OR; return ReturnLspToken( BOOL_OR ); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 191 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = AND; return ReturnLspToken( AND ); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 192 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = OR; return ReturnLspToken( OR ); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 193 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = EDIV; return ReturnLspToken( EDIV ); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 194 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = DIV; return ReturnLspToken( DIV ); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 195 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = EPOW; return ReturnLspToken( EPOW ); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 196 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = POW; return ReturnLspToken( POW ); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 197 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = ELDIV; return ReturnLspToken( ELDIV ); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 198 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = LDIV; return ReturnLspToken( LDIV ); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 199 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = GE; return ReturnLspToken( GE ); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 200 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = LE; return ReturnLspToken( LE ); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 201 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = EQL; return ReturnLspToken( EQL ); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 202 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = NE; return ReturnLspToken( NE ); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 203 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = LT; return ReturnLspToken( LT ); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 204 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = GT; return ReturnLspToken( GT ); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 206 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = NOT; return ReturnLspToken( NOT ); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 207 "TmcParLexer.l"
{BEGIN(INITIAL); tmcpar_lval.int_value = ASG; return ReturnLspToken( ASG ); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 208 "TmcParLexer.l"
{BEGIN(INITIAL); return ReturnLspToken( LPAREN ); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 209 "TmcParLexer.l"
{ BEGIN(ExpectQuoteAsCTRANSPOSE); 
					return ReturnLspToken( RPAREN ); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 211 "TmcParLexer.l"
{BEGIN(INITIAL); return ReturnLspToken( LC ); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 212 "TmcParLexer.l"
{ BEGIN(ExpectQuoteAsCTRANSPOSE);
				    return ReturnLspToken( RC ); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 214 "TmcParLexer.l"
{BEGIN(INITIAL); return ReturnLspToken( LBRA ); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 215 "TmcParLexer.l"
{ BEGIN(ExpectQuoteAsCTRANSPOSE);
				    return ReturnLspToken( RBRA ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 217 "TmcParLexer.l"
{ BEGIN(INITIAL);return ReturnLspToken( CM ); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 218 "TmcParLexer.l"
{ BEGIN(INITIAL);return ReturnLspToken( SM ); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 219 "TmcParLexer.l"
{BEGIN(INITIAL); return ReturnLspToken( COMAT ); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 220 "TmcParLexer.l"
{BEGIN(INITIAL); return ReturnLspToken( COLON ); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 221 "TmcParLexer.l"
{ return ReturnLspToken( ELLIP ); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 223 "TmcParLexer.l"
{ return ReturnLspToken( LEXERROR ); }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 226 "TmcParLexer.l"
{BEGIN(INITIAL);
 return ReturnLspToken( LINE ); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 229 "TmcParLexer.l"
{ BEGIN(INITIAL);
return ReturnLspToken( LINE ); }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 233 "TmcParLexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ExpectQuoteAsCTRANSPOSE):
#line 234 "TmcParLexer.l"
{
  // add a LINE at the end of the file to avoid commands without delimiter
  if (lexer_at_end_file)
     return ReturnLspToken( END_OF_INPUT);
  else
    {
     lexer_at_end_file++;
     return ReturnLspToken( LINE);
    }
  }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 244 "TmcParLexer.l"
{}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 245 "TmcParLexer.l"
ECHO;
	YY_BREAK
#line 1363 "lex.tmcpar_.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed tmcpar_in at a new source and called
			 * tmcpar_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = tmcpar_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( tmcpar_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * tmcpar_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of tmcpar_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					tmcpar_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			tmcpar_restart(tmcpar_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) tmcpar_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 162 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 162 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 161);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up tmcpar_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --tmcpar_lineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					tmcpar_restart(tmcpar_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( tmcpar_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve tmcpar_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    tmcpar_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void tmcpar_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        tmcpar_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            tmcpar__create_buffer(tmcpar_in,YY_BUF_SIZE );
	}

	tmcpar__init_buffer(YY_CURRENT_BUFFER,input_file );
	tmcpar__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void tmcpar__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		tmcpar_pop_buffer_state();
	 *		tmcpar_push_buffer_state(new_buffer);
     */
	tmcpar_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	tmcpar__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (tmcpar_wrap()) processing, but the only time this flag
	 * is looked at is after tmcpar_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void tmcpar__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	tmcpar_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE tmcpar__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) tmcpar_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in tmcpar__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) tmcpar_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in tmcpar__create_buffer()" );

	b->yy_is_our_buffer = 1;

	tmcpar__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with tmcpar__create_buffer()
 * 
 */
    void tmcpar__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		tmcpar_free((void *) b->yy_ch_buf  );

	tmcpar_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a tmcpar_restart() or at EOF.
 */
    static void tmcpar__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	tmcpar__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then tmcpar__init_buffer was _probably_
     * called from tmcpar_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void tmcpar__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		tmcpar__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void tmcpar_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	tmcpar_ensure_buffer_stack();

	/* This block is copied from tmcpar__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from tmcpar__switch_to_buffer. */
	tmcpar__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void tmcpar_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	tmcpar__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		tmcpar__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void tmcpar_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)tmcpar_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in tmcpar_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)tmcpar_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in tmcpar_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE tmcpar__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) tmcpar_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in tmcpar__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	tmcpar__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to tmcpar_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       tmcpar__scan_bytes() instead.
 */
YY_BUFFER_STATE tmcpar__scan_string (yyconst char * yystr )
{
    
	return tmcpar__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to tmcpar_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE tmcpar__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) tmcpar_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in tmcpar__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = tmcpar__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in tmcpar__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up tmcpar_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		tmcpar_text[tmcpar_leng] = (yy_hold_char); \
		(yy_c_buf_p) = tmcpar_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		tmcpar_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int tmcpar_get_lineno  (void)
{
        
    return tmcpar_lineno;
}

/** Get the input stream.
 * 
 */
FILE *tmcpar_get_in  (void)
{
        return tmcpar_in;
}

/** Get the output stream.
 * 
 */
FILE *tmcpar_get_out  (void)
{
        return tmcpar_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t tmcpar_get_leng  (void)
{
        return tmcpar_leng;
}

/** Get the current token.
 * 
 */

char *tmcpar_get_text  (void)
{
        return tmcpar_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void tmcpar_set_lineno (int  line_number )
{
    
    tmcpar_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see tmcpar__switch_to_buffer
 */
void tmcpar_set_in (FILE *  in_str )
{
        tmcpar_in = in_str ;
}

void tmcpar_set_out (FILE *  out_str )
{
        tmcpar_out = out_str ;
}

int tmcpar_get_debug  (void)
{
        return tmcpar__flex_debug;
}

void tmcpar_set_debug (int  bdebug )
{
        tmcpar__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from tmcpar_lex_destroy(), so don't allocate here.
     */

    /* We do not touch tmcpar_lineno unless the option is enabled. */
    tmcpar_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    tmcpar_in = stdin;
    tmcpar_out = stdout;
#else
    tmcpar_in = (FILE *) 0;
    tmcpar_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * tmcpar_lex_init()
     */
    return 0;
}

/* tmcpar_lex_destroy is for both reentrant and non-reentrant scanners. */
int tmcpar_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		tmcpar__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		tmcpar_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	tmcpar_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * tmcpar_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *tmcpar_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *tmcpar_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void tmcpar_free (void * ptr )
{
	free( (char *) ptr );	/* see tmcpar_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 244 "TmcParLexer.l"



//<S>";"          { return ReturnLspToken( SM ); }
//<S>{COMMENT_START}          {
//					BEGIN COM;
//				}
//<COM>{NL}       {
//					 BEGIN S;
//				}

//E.g.:
//BEGIN(ExpectQuoteAsCTRANSPOSE);*(tmcpar_text+tmcpar_leng-1) = ’\0’;yylval.imaginaryQ =atof(tmcpar_text);Return("IMAGINARY", IMAGINARY);


char str_buffer[MAX_SRC_STRING];
char* get_string(short bGershaim)
{
  int k=0;
  int c;
  char delim = bGershaim ? '\"' : '\'';
  str_buffer[k++]=delim;
  str_buffer[1]=0;
  while ((c = yyinput ()) != EOF)
  {
	
	
	str_buffer[k++]=c;
	//if ((bGershaim==0) && (c==  '\"'))
	//{ // translate " -> ""
	//	str_buffer[k++]='\"';
	//}
	
	
	if (c==delim)
	{
	
		// check if we have twice '
		c=yyinput();
		if (c != delim)
		{
			unput(c);
			str_buffer[k]=0;
			if (k>0)
				str_buffer[k-1]=0;
				//str_buffer[k++]=0;
			return &str_buffer[1];
		}
		else
		{
		// go to the next letter
		}
	}
  }
  return &str_buffer[1];
}

char str_buffer2[MAX_SRC_STRING];

char* get_identifier()
{
//tmcpar_leng is length
//tmcpar_text is src
  strcpy(&tmcpar_lval.ident[0],tmcpar_text);
  return &tmcpar_lval.ident[0];
}

void reset_tmcpar_lexer()
{
	tmcpar_lval.str = str_buffer;
	
  	  //YY_BUFFER_STATE old_buf = current_buffer ();
	  //YY_BUFFER_STATE new_buf = create_buffer (tmc_in);
	  //switch_to_buffer (new_buf);

  // Start off on the right foot.
  BEGIN (INITIAL);
	
  tmcpar_restart (tmc_in);// switch scanner to tmc_in. Must be used to protect agains parse error on
  // the previous file that had not been read until EOF !!!!
	
  lexer_indexdeep=0;
  lexer_at_end_file=0;
}
////////// LEXER UTILS ///////////////
void yyunput_elipse_of_element_op(void)
{
 //   3.*y must be like 3 .* y and not like 3. * y   
 int latest;
 int current;
 
 latest = *(tmcpar_text+tmcpar_leng-1);
 if (latest != '.')
 {
		return;
 }
 
 current = yyinput();
 {
	if (current=='/' || current=='*' || current=='\\' || current=='^' )
	{
		unput(current);
		unput('.');	// HAZARD_TODO: put warning here
	}
	else
	{
		unput(current);
	}
 }
}


#define LD LBRA

void yyinsert_comma_in_input(const int lastToken)
{//HAZARD: check for '{' and '.'
int count, current, next;

if (lastToken==END)
{
    unput(';');
	return;
}

if (!(BracketDelimiter == LBRA || BracketDelimiter == LD))
return;
for (count = 1; ; count++)
{
current = yyinput();
if (current != ' ' && current != '\t')
break;
}
if (current == ',' || current == ';' || current == ']' ||
current == '*' || current == '^' || current == ':' ||
current == '<' || current == '>' || current == '=' ||
current == '&' || current == '|' ||
current == '/' || current == '\\' ||
current == '\n' || current == '\r' || current == '\f' ||
current == '%' || current == '.' || //HSKOST added '.' for  fields
(current == '\'' && count == 1))
{
unput(current);
return;
}
if ((current == '(' ||current == '{' || current == '.') &&
(BracketDelimiter == LD ||
(lastToken == IDENT && count == 1)))
{
unput(current);
return;
}
if (isalpha(current) &&
(lastToken == NUMBER || lastToken == NUMBER_IM) && count == 1)
{
unput(current);
return;
}
next = yyinput();
++count;
if (current == '.' &&
(next == '\'' || next == '*' || next == '^' ||
next == '/' || next == '\\' || next == '.'))
{
unput(next);
unput('.');
if (next == '\'' && count > 2)
unput(' ');
return;
}
if (current == '~' && next == '=')
{
unput('=');
unput('~');
return;
}
if (current == '+' || current == '-')
{
if (count == 2 || next == ' ' || next == '\t')
{
unput(next);
unput(current);
return;
}
}
unput(next);
unput(current);
unput(',');
}
//////
int  tmc_parse(void)
{
	tmcpar_parse();
	return 1;
}
void  reset_parser(void)
{
	tmcpar_lineno=1;tmcpar_colno=0;
	tmcpar_parsing_module=NULL; // tree result of the parsing
	reset_tmcpar_lexer();
}
void tmcpar_error(const char *)
{
	printf("%s(%d) : error P0001: fatal syntax error\n",curr_fcn_file_full_name.c_str(),(int)tmcpar_lineno);
if (Compiler.bUseDumpFile) fprintf(dump_file,"%s(%d) : error P0001: fatal syntax error\n",curr_fcn_file_full_name.c_str(),(int)tmcpar_lineno);
fprintf(stderr,"%s(%d) : error P0001: fatal syntax error\n",curr_fcn_file_full_name.c_str(),(int)tmcpar_lineno);
throw(CCompilerExcpt());
}
int tmcpar_wrap (void)
{
  return 1;
}
void dbgPrintLspToken(long TokVal)
{
	fprintf(stderr,"Tok=%d, l=%d,c=%d,int_value=%d ",TokVal,(int)tmcpar_lineno,0,tmcpar_lval.int_value);
	if (TokVal==STRING)
		fprintf(stderr,"%s\n",tmcpar_lval.str);
	else if (TokVal==IDENT)
		fprintf(stderr,"%s\n",tmcpar_lval.ident);
	else 
		fprintf(stderr,"\n");
}
long ReturnLspToken(long TokVal)
{
#ifdef _DEBUG
//VANDAL	dbgPrintLspToken(TokVal);
#endif
	return TokVal;
}

