## List of CLAPACK files used for TMC runtime
set(LAPACK_SRCS
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dbdsqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgebak.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgebal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgebd2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgebrd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgeevx.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgehd2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgehrd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgelq2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgelqf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgels.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgeqr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgeqrf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgesvd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgetf2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dgetrf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dhseqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlabad.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlabrd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlacn2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlacpy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dladiv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaexc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlahqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlahr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaln2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlamch.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlange.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlanv2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlapy2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlapy3.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaqr0.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaqr1.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaqr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaqr3.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaqr4.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaqr5.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaqtr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlarf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlarfb.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlarfg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlarft.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlarfx.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlartg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlas2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlascl.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaset.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasq1.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasq2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasq4.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasq5.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasq6.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasrt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlassq.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasv2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlaswp.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlasy2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlazq3.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dlazq4.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorg2l.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorg2r.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorgbr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorghr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorgl2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorglq.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorgql.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorgqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorm2l.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorm2r.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dormbr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dorml2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dormlq.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dormqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dtrevc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dtrexc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dtrsna.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dtrtrs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/dzsum1.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/ieeeck.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/ilaenv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/iparmq.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/izmax1.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/lsame.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/xerbla.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zbdsqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zdrscl.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgebak.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgebal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgebd2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgebrd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgeevx.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgehd2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgehrd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgelq2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgelqf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgels.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgeqr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgeqrf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgesvd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgetf2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zgetrf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zhseqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlabrd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlacgv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlacn2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlacpy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zladiv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlahqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlahr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlange.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaqr0.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaqr1.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaqr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaqr3.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaqr4.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaqr5.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlarf.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlarfb.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlarfg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlarft.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlartg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlascl.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaset.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlasr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlassq.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlaswp.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zlatrs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zrot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/ztrevc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/ztrexc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/ztrsna.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/ztrtrs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zung2r.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zungbr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zunghr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zungl2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zunglq.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zungqr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zunm2r.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zunmbr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zunml2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zunmlq.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC/zunmqr.c
)
set (BLAS_SRCS
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/caxpy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ccopy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cdotc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cdotu.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cgbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cgemm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cgemv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cgerc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cgeru.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/chbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/chemm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/chemv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cher.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cher2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cher2k.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cherk.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/chpmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/chpr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/chpr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/crotg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cscal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/csrot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/csscal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/cswap.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/csymm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/csyr2k.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/csyrk.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctbsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctpmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctpsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctrmm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctrmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctrsm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ctrsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dasum.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/daxpy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dcabs1.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dcopy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ddot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dgbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dgemm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dgemv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dger.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dnrm2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/drot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/drotg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/drotm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/drotmg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dscal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsdot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dspmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dspr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dspr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dswap.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsymm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsymv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsyr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsyr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsyr2k.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dsyrk.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtbsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtpmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtpsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtrmm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtrmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtrsm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dtrsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dzasum.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/dznrm2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/icamax.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/idamax.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/isamax.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/izamax.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sasum.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/saxpy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/scabs1.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/scasum.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/scnrm2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/scopy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sdot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sdsdot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sgbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sgemm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sgemv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sger.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/snrm2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/srot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/srotg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/srotm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/srotmg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ssbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sscal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sspmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sspr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sspr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/sswap.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ssymm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ssymv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ssyr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ssyr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ssyr2k.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ssyrk.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/stbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/stbsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/stpmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/stpsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/strmm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/strmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/strsm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/strsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zaxpy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zcopy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zdotc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zdotu.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zdrot.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zdscal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zgbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zgemm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zgemv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zgerc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zgeru.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zhbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zhemm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zhemv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zher.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zher2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zher2k.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zherk.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zhpmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zhpr.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zhpr2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zrotg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zscal.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zswap.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zsymm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zsyr2k.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/zsyrk.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztbmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztbsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztpmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztpsv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztrmm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztrmv.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztrsm.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_BLAS/ztrsv.c
)
set (F2C_SRCS
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/abort_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/cabs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/c_abs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/c_cos.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/c_div.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/c_exp.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/c_log.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/c_sin.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/c_sqrt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/dtime_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_abs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_acos.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_asin.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_atan.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_atn2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_cnjg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_cos.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_cosh.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_dim.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_exp.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_imag.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_int.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_lg10.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_log.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_mod.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_nint.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_prod.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_sign.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_sin.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_sinh.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_sqrt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_tan.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/d_tanh.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/ef1asc_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/ef1cmc_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/etime_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/exit_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/f77vers.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/f77_aloc.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/fmtlib.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/getenv_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/hl_ge.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/hl_gt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/hl_le.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/hl_lt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_abs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_dim.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_dnnt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_indx.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_len.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_mod.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_nint.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/h_sign.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_abs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_dim.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_dnnt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_indx.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_len.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_mod.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_nint.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/i_sign.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/lbitbits.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/lbitshft.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/l_ge.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/l_gt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/l_le.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/l_lt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_ci.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_dd.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_di.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_hh.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_ii.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_ri.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_zi.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/pow_zz.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_abs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_acos.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_asin.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_atan.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_atn2.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_cnjg.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_cos.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_cosh.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_dim.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_exp.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_imag.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_int.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_lg10.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_log.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_mod.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_nint.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_sign.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_sin.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_sinh.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_sqrt.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_tan.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/r_tanh.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/signal_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/signbit.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/sig_die.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/system_.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/s_cat.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/s_cmp.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/s_copy.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/s_rnge.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/s_stop.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/typesize.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/z_abs.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/z_cos.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/z_div.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/z_exp.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/z_log.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/z_sin.c
${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/z_sqrt.c
)

## ${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/derfc_.c
##${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/derf_.c
##${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/erfc_.c
##${TMCLIB_SRC_DIR}/lapack_lib/SRC_F2C/erf_.c
