set(JsonParser_SRCS
./JsonParser/JMatrix.c
./JsonParser/JMatrix.h
./JsonParser/JsonRead.tab.c
./JsonParser/JsonRead.tab.h
./JsonParser/lex.JsonRead_.c
./JsonParser/tmcjson_read.c
./JsonParser/tmcjson_read.h
)
