//File: TestO.c 
//Generated by TMC Converter(C)2009-2013
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#define	_O_RDONLY O_RDONLY
#define _O_BINARY 0  //O_BINARY
#define  _O_RDWR  O_RDWR
#define  _O_CREAT O_CREAT
#define	 _O_TRUNC O_TRUNC
#define	 _S_IREAD (S_IRUSR|S_IROTH)		// see sys/stat.h.
#define	 _S_IWRITE (S_IWUSR|S_IWOTH)


#include <android/log.h>
#include <string.h>
#include <stdio.h>

void tmcDisplayMatF(FILE *fp,tmsMatrix *x,short bVerb);

// % Lines 1--27:
//function y=TestO(x)

//%addpath('C:\Data_D\HSKOST\OdedCompilation\SIMO_Mex_C\MexDLLS')

//%addpath('C:\Data_D\HSKOST\OdedCompilation\SIMO')

//%addpath('C:\Data_D\HSKOST\Pure\tmcdbg\matscripts')

//

//% X  = [2,3,4 ; 55,66,77];

//% 

//% y = zeros(2,3,4);

//% y(:,:,1)=X;

//% y(:,:,2)=X*2;

//% y(:,:,3)=X*3;

//% y(:,:,4)=X*4;

//% 

//% disp(y);

//% 

//% A = y(:,:,4);

//% disp(A);

//% a = y(1,2,[1,2,4]);

//% disp(a);

//% 

//% % C = cell(2,3,4);

//% % C(1,1,1)=X;

//% % C(1,2,3)=X+200;

//% 

//

//

//www1=load('Costia_v6.mat');

FILE *fp;

//void tmcTestOA(int nargout, int nargin,tmsMatrix *y,tmsMatrix *x)
void tmcTestTuner(int nargout, int nargin,tmsMatrix *plants,tmsMatrix *Fw,
	tmsMatrix *ki,tmsMatrix *kp,tmsMatrix *kd,tmsMatrix *polew,tmsMatrix *x)
  {
int fh;
char sBuf[]="/mnt/sdcard/download/ServoToolLog.txt";
char sBufM[]="/mnt/sdcard/download/Model.txt";

char sOutBuf[1024];

tmsMatrix **reg=tmcCreateRegFrame(130);
tmsMatrix *www1=tmcNewMatrix();
tmsMatrix *www2=tmcNewMatrix();
tmsMatrix *Model=tmcNewMatrix();
tmsMatrix *Success=tmcNewMatrix();
tmsMatrix *Crl=tmcNewMatrix();
tmsMatrix *len=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("TestO",8,
x,"x",
plants,"plants",
www1,"www1",
www2,"www2",
Model,"Model",
Success,"Success",
Crl,"Crl",
len,"len");

tmcCreateString(reg[1],"/mnt/sdcard/download/Costia_v6.mat");
//CALL function
tmcReallocRegister(reg[2]);

//__android_log_print(ANDROID_LOG_VERBOSE, "Servo Tools", "Starting loading %d", 0);

tmcload(1,1, reg[2], reg[1]);

tmcAssign(www1,reg[2]);
//statement here,line 27

// % Lines 28--29:
//% www2=load('Costia1.mat'); % Sys

//www2=www1;



tmcAssign(www2,www1);
//statement here,line 29

// % Lines 30--33:
//

//[Model,Success] = PIDPrepare(www2.Sys,...

//www1.FeedOut,www1.GM,www1.PM,www1.Type,www1.OrderLP,www1.SearchLP,www1.SearchLead,www1.SearchInt,...

//www1.SearchNotch,www1.xi,www1.NumInt,www1.NumUnP,www1.PreFilter,www1.w,www1.Dilution,www1.SenNoise,www1.S,www1.WM);


tmcGetByFieldHcode(reg[8],www2,0x46ad0000);/* Sys */

tmcGetByFieldHcode(reg[11],www1,0x9cb00000);/* FeedOut */

tmcGetByFieldHcode(reg[14],www1,0x08e60000);/* GM */

tmcGetByFieldHcode(reg[17],www1,0x09fd0000);/* PM */

tmcGetByFieldHcode(reg[20],www1,0x035a0000);/* Type */

tmcGetByFieldHcode(reg[23],www1,0x8d320000);/* OrderLP */

tmcGetByFieldHcode(reg[26],www1,0x094c0000);/* SearchLP */

tmcGetByFieldHcode(reg[29],www1,0x41440000);/* SearchLead */

tmcGetByFieldHcode(reg[32],www1,0x19070000);/* SearchInt */

tmcGetByFieldHcode(reg[35],www1,0xe9900000);/* SearchNotch */

tmcGetByFieldHcode(reg[38],www1,0x0ef10000);/* xi */

tmcGetByFieldHcode(reg[41],www1,0x6aa90000);/* NumInt */

tmcGetByFieldHcode(reg[44],www1,0x97910000);/* NumUnP */

tmcGetByFieldHcode(reg[47],www1,0xc3db0000);/* PreFilter */

tmcGetByFieldHcode(reg[50],www1,0x00770000);/* w */

tmcGetByFieldHcode(reg[53],www1,0xad020000);/* Dilution */

tmcGetByFieldHcode(reg[56],www1,0x383e0000);/* SenNoise */

tmcGetByFieldHcode(reg[59],www1,0x00530000);/* S */

tmcGetByFieldHcode(reg[62],www1,0x0ad60000);/* WM */



fh = open(sBuf,_O_RDWR  | _O_CREAT | _O_TRUNC | _O_BINARY, _S_IREAD | _S_IWRITE );
sprintf(sOutBuf,"w=%f\n", reg[50]->m_rData[0]);
write(fh,sOutBuf,strlen(sOutBuf));
close(fh);




//CALL function
tmcReallocRegister(reg[63]);
tmcReallocRegister(reg[64]);
 tmcPIDPrepare(2,19, reg[63], reg[64], reg[8], reg[11], reg[14], reg[17], reg[20], reg[23], reg[26], reg[29],
 reg[32], reg[35], reg[38], reg[41], reg[44], reg[47], reg[50], reg[53],
 reg[56], reg[59], reg[62],NULL,NULL,NULL,NULL);


tmcAssign(Model,reg[63]);

tmcAssign(Success,reg[64]);
//statement here,line 33

fp = fopen(sBufM,"w");
fprintf(fp,"MODEL=:\n");
tmcDisplayMatF(fp,Model,1);
//fprintf(fp,"Success=:\n");
//tmcDisplayMatF(fp,Success,1);
fclose(fp);

// % Lines 34--34:
//save('ModelPrep.mat','Model','Success');

tmcCreateString(reg[67],"/mnt/sdcard/download/ModelPrep.mat");
//CALL function save
tmcsave(0,3, reg[67], Model, "Model", Success, "Success");
//statement here,line 34

tmcCreateString(reg[67], "/mnt/sdcard/download/klum.mat");
tmcsave(0, 2, reg[67], reg[67], "stam");

//tested:tmcerror(0, 1, reg[67], reg[67]);

//tmcCreateString(reg[67],"/mnt/sdcard/download/w.mat");
////CALL function save
//tmcsave(0,2, reg[67], reg[50], "w" );

tmcCreateString(reg[1],"/mnt/sdcard/download/ModelPrep.mat");
tmcReallocRegister(reg[2]);
tmcload(1,1, reg[2], reg[1]);
//"Model",0x0b090000,

tmcGetByFieldHcode(reg[69],reg[2],0x0b090000);/* Model */

fp = fopen("/mnt/sdcard/download/ModelSaved.txt","w");
fprintf(fp,"MODEL=:\n");
tmcDisplayMatF(fp,reg[69],1);
fclose(fp);
// % Lines 35--35:
//[Crl,Model,Success] = QFD(Model);
fp = fopen("/mnt/sdcard/download/Input.txt","w");
fprintf(fp,"www1=:\n");
tmcDisplayMatF(fp,www1,1);
fclose(fp);

//CALL function
tmcReallocRegister(reg[69]);
tmcReallocRegister(reg[70]);
tmcReallocRegister(reg[71]);

if (x->m_rData[0]==7)
{
	// only load existing result
	tmcCreateString(reg[75],"/mnt/sdcard/download/Out.mat");
	tmcReallocRegister(reg[68]);
	tmcload(1,1, reg[68], reg[75]);

	tmcGetByFieldHcode(Crl,reg[68],0x09bd0000);/* Crl */
	tmcGetByFieldHcode(Model,reg[68],0x0b090000);/* Model */
//HAZARD	tmcGetByFieldHcode(Success,reg[68], );/* Success */
	tmcScalar(Success,1.000000000000000e+000);

}
else
{
tmcQFD(3,1, reg[69], reg[70], reg[71], Model,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL);


tmcAssign(Crl,reg[69]);

tmcAssign(Model,reg[70]);

tmcAssign(Success,reg[71]);
//statement here,line 35

// % Lines 36--36:
//save('Out.mat','Crl','Model','Success');


fp = fopen("/mnt/sdcard/download/Output.txt", "w");
fprintf(fp, "Success=:\n");
tmcDisplayMatF(fp, Success, 1);
fprintf(fp, "Crl=:\n");
tmcDisplayMatF(fp, Crl, 1);
fclose(fp);

tmcCreateString(reg[75],"/mnt/sdcard/download/Out.mat");
//CALL function save
tmcsave(0,4, reg[75], Crl, "Crl", Model, "Model", Success, "Success");
//statement here,line 36
} // if

// % Lines 37--38:
//

//len=length(Crl.KP);


tmcGetByFieldHcode(reg[78],Crl,0x09650000);/* KP */
//CALL function
tmcReallocRegister(reg[79]);
tmclength(1,1, reg[79], reg[78]);

tmcAssign(len,reg[79]);
//statement here,line 38

// % Lines 39--39:
//figure;

//CALL function
tmcReallocRegister(reg[81]);
tmcfigure(0,0, reg[81],NULL);
//statement here,line 39

// % Lines 40--40:
//subplot(4,1,1);

tmcScalar(reg[82],4.000000000000000e+000);
tmcScalar(reg[83],1.000000000000000e+000);
tmcScalar(reg[84],1.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[85]);
tmcsubplot(0,3, reg[85], reg[82], reg[83], reg[84]);
//statement here,line 40

// % Lines 41--41:
//plot(1:len,Crl.KP,'b');

tmcScalar(reg[86],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[88],reg[86],len);

tmcGetByFieldHcode(reg[91],Crl,0x09650000);/* KP */
tmcCreateString(reg[92],"b");
//CALL function
tmcReallocRegister(reg[93]);
tmcplot(0,3, reg[93], reg[88], reg[91], reg[92]);
//statement here,line 41

// % Lines 42--42:
//subplot(4,1,2);

tmcScalar(reg[94],4.000000000000000e+000);
tmcScalar(reg[95],1.000000000000000e+000);
tmcScalar(reg[96],2.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[97]);
tmcsubplot(0,3, reg[97], reg[94], reg[95], reg[96]);
//statement here,line 42

// % Lines 43--43:
//plot(1:len,Crl.KD,'b');

tmcScalar(reg[98],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[100],reg[98],len);

tmcGetByFieldHcode(reg[103],Crl,0x09590000);/* KD */
tmcCreateString(reg[104],"b");
//CALL function
tmcReallocRegister(reg[105]);
tmcplot(0,3, reg[105], reg[100], reg[103], reg[104]);
//statement here,line 43

// % Lines 44--44:
//subplot(4,1,3);

tmcScalar(reg[106],4.000000000000000e+000);
tmcScalar(reg[107],1.000000000000000e+000);
tmcScalar(reg[108],3.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[109]);
tmcsubplot(0,3, reg[109], reg[106], reg[107], reg[108]);
//statement here,line 44

// % Lines 45--45:
//plot(1:len,Crl.KI,'b');

tmcScalar(reg[110],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[112],reg[110],len);

tmcGetByFieldHcode(reg[115],Crl,0x095e0000);/* KI */
tmcCreateString(reg[116],"b");
//CALL function
tmcReallocRegister(reg[117]);
tmcplot(0,3, reg[117], reg[112], reg[115], reg[116]);
//statement here,line 45

// % Lines 46--46:
//subplot(4,1,4);

tmcScalar(reg[118],4.000000000000000e+000);
tmcScalar(reg[119],1.000000000000000e+000);
tmcScalar(reg[120],4.000000000000000e+000);
//CALL function
tmcReallocRegister(reg[121]);
tmcsubplot(0,3, reg[121], reg[118], reg[119], reg[120]);
//statement here,line 46

// % Lines 47--47:
//plot(1:len,Crl.w,'b');

tmcScalar(reg[122],1.000000000000000e+000);

tmcCreateColonBaseLimit(reg[124],reg[122],len);

tmcGetByFieldHcode(reg[127],Crl,0x00770000);/* w */
tmcCreateString(reg[128],"b");
//CALL function
tmcReallocRegister(reg[129]);
tmcplot(0,3, reg[129], reg[124], reg[127], reg[128]);
//statement here,line 47

// % Lines 48--48:
//

// HAZARD TODO: OrderLP, DampLP, Ts, Type
// Assign result here: plants = Model.P1
tmcGetByFieldHcode(plants,Model,0x09e10000);/* P1 */
// Assign result here: Fw = Model.w
tmcGetByFieldHcode(Fw,Model,0x00770000);/* w */
// Assign result here: ki = Crl.KI
tmcGetByFieldHcode(ki,Crl,0x095e0000);/* KI */
// Assign result here: kp = Crl.KP
tmcGetByFieldHcode(kp,Crl,0x09650000);/* KP */
// Assign result here: kd = Crl.KD
tmcGetByFieldHcode(kd,Crl,0x09590000);/* KD */
// Assign result here: polew = Crl.w
tmcGetByFieldHcode(polew,Crl,0x00770000);/* w */


label_1: ; //end Function
FINALLY
tmcFreeLocalVar(len);
tmcFreeLocalVar(Crl);
tmcFreeLocalVar(Success);
tmcFreeLocalVar(Model);
tmcFreeLocalVar(www2);
tmcFreeLocalVar(www1);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(8);

ENDFINALLY
}

//FUNCTION DEFINITION BEGIN
