//File: TestO.c 
//Generated by TMC Converter(C)2009-2016
#include "tmc.h"
#include "stdtmc.h"

#include "TestO.globals.h"

// User provided C-code header (must be included in include path):
#include "External_func.h"

// % Lines 1--3:
//function [PropGain,IntGain,FreqLen,FreqHz,OL_Mag,OL_Ph,CL_Mag,CL_Ph,RespLen,RespTime,Resp]=TestO(R,L,Ts,Ovs)

//

//COMM=MPI_Comm_Load;

void tmcTestO(int nargout, int nargin,tmsMatrix *PropGain,tmsMatrix *IntGain,tmsMatrix *FreqLen,tmsMatrix *FreqHz,tmsMatrix *OL_Mag,tmsMatrix *OL_Ph,tmsMatrix *CL_Mag,tmsMatrix *CL_Ph,tmsMatrix *RespLen,tmsMatrix *RespTime,tmsMatrix *Resp
,tmsMatrix *R,tmsMatrix *L,tmsMatrix *Ts,tmsMatrix *Ovs) {
tmsMatrix **reg=tmcCreateRegFrame(33);
tmsMatrix *COMM=tmcNewMatrix();
tmsMatrix *numproc=tmcNewMatrix();

TRY
TMC_DBG_PUSH_STACK_VAR("TestO",17,
R,"R",
L,"L",
Ts,"Ts",
Ovs,"Ovs",
PropGain,"PropGain",
IntGain,"IntGain",
FreqLen,"FreqLen",
FreqHz,"FreqHz",
OL_Mag,"OL_Mag",
OL_Ph,"OL_Ph",
CL_Mag,"CL_Mag",
CL_Ph,"CL_Ph",
RespLen,"RespLen",
RespTime,"RespTime",
Resp,"Resp",
COMM,"COMM",
numproc,"numproc");

//CALL function
tmcReallocRegister(reg[1]);
tmcMPI_Comm_Load(1,0, reg[1],NULL);

tmcAssign(COMM,reg[1]);
//statement here,line 3

// % Lines 4--4:
//numproc = MPI_Comm_size(COMM);


//CALL function
tmcReallocRegister(reg[4]);
tmcMPI_Comm_size(1,1, reg[4], COMM);

tmcAssign(numproc,reg[4]);
//statement here,line 4

// % Lines 5--17:
//%my_rank = MPI_Comm_rank(COMM);

//%str = ['We are running on ',num2str(numproc), ' cores. I am ',num2str(my_rank)];

//%disp(str);

//

//%RANKS  = [0:numproc-1];

//%if (my_rank==0)

//%	INFO = MPI_Send([1,-2 ; 3+2i,i],RANKS(2:end),0,COMM);

//%else

//%	[Y, INFO] = MPI_Recv(0,0,COMM);

//%	disp('Received matrix:');

//%	disp(Y);

//%end

//save ('in1.mat','R','L','Ts','Ovs','numproc');

tmcCreateString(reg[6],"in1.mat");
//CALL function save
tmcsave(0,6, reg[6], R, "R", L, "L", Ts, "Ts", Ovs, "Ovs", numproc, "numproc");
//statement here,line 17

// % Lines 18--18:
//[PropGain,IntGain,FreqLen,FreqHz,OL_Mag,OL_Ph,CL_Mag,CL_Ph,RespLen,RespTime,Resp]=getcurloop(R,L,Ts,Ovs);




//CALL function
tmcReallocRegister(reg[11]);
tmcReallocRegister(reg[12]);
tmcReallocRegister(reg[13]);
tmcReallocRegister(reg[14]);
tmcReallocRegister(reg[15]);
tmcReallocRegister(reg[16]);
tmcReallocRegister(reg[17]);
tmcReallocRegister(reg[18]);
tmcReallocRegister(reg[19]);
tmcReallocRegister(reg[20]);
tmcReallocRegister(reg[21]);
tmcgetcurloop(11,4, reg[11], reg[12], reg[13], reg[14], reg[15], reg[16], reg[17], reg[18],
 reg[19], reg[20], reg[21], R, L, Ts, Ovs);

tmcAssign(PropGain,reg[11]);

tmcAssign(IntGain,reg[12]);

tmcAssign(FreqLen,reg[13]);

tmcAssign(FreqHz,reg[14]);

tmcAssign(OL_Mag,reg[15]);

tmcAssign(OL_Ph,reg[16]);

tmcAssign(CL_Mag,reg[17]);

tmcAssign(CL_Ph,reg[18]);

tmcAssign(RespLen,reg[19]);

tmcAssign(RespTime,reg[20]);

tmcAssign(Resp,reg[21]);
//statement here,line 18

label_1: ; //end Function
FINALLY
tmcFreeLocalVar(numproc);
tmcFreeLocalVar(COMM);
tmcFreeRegFrame(reg);

TMC_DBG_POP_STACK_VAR(17);

ENDFINALLY
}

//FUNCTION DEFINITION ENDED
//statement here,line 18

// % Lines 19--19:
